<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Entities;
use Application\Entity\Activitycategories;


/**
 * ActivitycategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitycategoriesRepository extends EntityRepository
{
	public function getActivitycategoriesByName($orderby="ASC"){
		$em=$this->getEntityManager();
		$category=$em->createQuery("Select ac from Application\Entity\Activitycategories ac Order by ac.name $orderby")->getArrayResult();
		return $category;
	}
	
}
