<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityLogRepository extends EntityRepository
{
}
