<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Entity\Activitystatuses;

/**
 * ActivitystatusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitystatusesRepository extends EntityRepository
{
	
	public function getActivitystatuses($OrderBy="ASC"){
		$em=$this->getEntityManager();
		$Activitystatuses = $em->createQuery("SELECT a FROM Application\Entity\Activitystatuses a Order by a.name $OrderBy")->getArrayResult();
		return $Activitystatuses;
	}
	
	public function getActivitystatusesById($id){
		$em=$this->getEntityManager();
		$Activitystatuses = $em->createQuery("SELECT a FROM Application\Entity\Activitystatuses a where a.id=$id")->getArrayResult();
		return $Activitystatuses;
	}
}