<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityhistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityhistoryRepository extends EntityRepository
{
}
