<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Entity\Leaves;
use Application\Entity\Sentmail;

/**
 * LeavesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeavesRepository extends EntityRepository
{
	function getLeaveList(){
	 	$em = $this->getEntityManager();
		$leaveList=$em->createQuery("Select l.id as id,l.title as title,l.start_date as start_date,l.end_date as end_date,l.description as description,l.is_sanctioned as is_sanctioned,l.created_date as created_date,l.created_time as created_time,l.user_id as userid from Application\Entity\Leaves l ")->getResult();
		return $leaveList;
	}
	
	function getuserLeaveList($userid){
		$em = $this->getEntityManager();
		$leaveList=$em->createQuery("Select l.id as id,l.title as title,l.start_date as start_date,l.end_date as end_date,l.description as description,l.is_sanctioned as is_sanctioned,l.created_date as created_date,l.created_time as created_time,l.user_id as userid from Application\Entity\Leaves l where l.user_id=$userid")->getResult();
		return $leaveList;
	}
}
