<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Zend\Authentication\AuthenticationService;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends EntityRepository
{
	public function getTodayLoginTime($userid,$activityDate){
		$auth = new AuthenticationService();
		$em=$this->getEntityManager();
		$users = $em->createQuery("SELECT min(l.logintime) as mindt,l.created_date as cdate FROM Application\Entity\Login l  WHERE l.user_id=$userid AND l.created_date=$activityDate")->getResult();
		return $users;
	}
	
}
