<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Entities;
use Application\Entity\Milestones;



/**
 * MilestonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilestonesRepository extends EntityRepository
{
	public function getMilestonsOrderByName($orderby="ASC"){
		$em=$this->getEntityManager();
		$milestones = $em->createQuery("SELECT m FROM Application\Entity\Milestones m Order by m.name $orderby")->getArrayResult();
		return $milestones;
	}
	 
	public function getMilestonsByProjectId($projectid,$milestoneid=0){
		
		$em=$this->getEntityManager();
		$where='';
		if ($projectid>0){
		if ($where==''){
			$where="m.project_id=$projectid";
		}else {
			$where.="AND m.project_id=$projectid";
		}
		}		
		if ($milestoneid>0 && $milestoneid!=0){
			if ($where==''){
				$where="m.id=$milestoneid";
			}else {
				$where.="AND m.id=$milestoneid";
			}
		}
		if ($where==''){
			$where="1=1";
		}
		$milestone=$em->createQuery("Select m.id as id,m.name as name,p.name as pname from Application\Entity\Milestones m JOIN Application\Entity\Projects p WITH m.project_id=p.id Where $where  Order by m.name ASC")->getArrayResult();
		return $milestone;
	}
}
