<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferencesRepository extends EntityRepository
{
}
