<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectstatusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectstatusesRepository extends EntityRepository
{
}
