<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjecttypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjecttypesRepository extends EntityRepository
{
}
