<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjecthistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjecthistoryRepository extends EntityRepository
{
}
