<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SentmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentmailRepository extends EntityRepository
{
}
