<script type="text/javascript" src="/js/bootbox.min.js"></script>
<?php
use IntranetUtils\Common;
$common=new Common();
?>

<div id="addallocation">
<form action="" method="post" id="form1" class="form-horizontal">
				<div class="row-fluid">
						<div class="control-group">
							<label class="control-label" for="inputProject">Project:<sup style="color:#FF0000;">*</sup></label>
							<div class="controls">
								<select id="project" name="project" title="Project" tabindex="1">
									<option value="">--Select--</option>
									<?php if(isset($project) && count($project)>0){
										for($i=0;$i<count($project);$i++){
											?>
									<option value="<?php echo $project[$i]['id'];?>"
									<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project[$i]['id']){echo 'selected="selected"';}?>  >
										<?php echo ucwords($project[$i]['name']); ?>
									</option>
									<?php }?>
									<?php }?>
								</select>
							</div>
							<div class="controls"><div id="project_error"></div></div>
						</div>
				</div>
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label" for="inputProject">Title:<sup style="color:#FF0000;">*</sup></label>
						<div class="controls">
							<input type="text" id="title" name="title" title="Title" />
						</div>
					</div>
				</div>
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">Strat Date: </label>
						<div class="controls">
							<input type="text" id="strat_date" name="strat_date"title="Strat Date" value="" />
							<input type="hidden" id="alternate_strat_date" name="alternate_strat_date" title="Strat Date" value="" />
						</div>
				<div class="controls small-margin"><div id="spent_error"></div></div>
					</div>
				</div>
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">End Date: </label>
						<div class="controls">
							<input type="text" id="end_date" name="end_date" title="End Date" value="" /> 
							<input type="hidden" id="alternate_end_date" name="alternate_end_date" title="End Date" value="" />
						</div>
					</div>
				</div>
</form>
</div>
	<script type="text/javascript">
 $(document).ready(function(){	 
	 $("#strat_date").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       onSelect: function (selectedDate){
	       
	       },
	       altField: "#alternate_strat_date",
	       altFormat: "yy-mm-dd",
     });
	   $("#end_date").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       onSelect: function (selectedDate){
	       
	       },
	       altField: "#alternate_end_date",
	       altFormat: "yy-mm-dd",
     });
     $("#btnaddallocation").unbind('click');   
     $("#btnaddallocation").bind('click',function(){add();});
});
 
function add(id){ 
	$.ajax({
        type: "POST",
        url:  "<?php echo $this->url('addallocation'); ?>",
        dataType:"json",
        data: $("#form1").serialize()+"&id="+id,
        beforeSend: function () {
			$('#addallocation').mask("Loading...");
	 	 },
	     success: function(response)
	     {   	    		
	    	if(response['returnvalue']=="valid")
		    {
     	  		alert("Allocation added successful");
     	  		$("#addallocationdialog").modal('hide');
	       	  	$("#list").trigger('reloadGrid');	        	         
	     	}
	     	else if(response.returnvalue=="exception")
		    {
          	  bootbox.alert("This Operation Could not be Completed,Please contact administrator");
              return false;
         	}
            else
            {
                 for(var key in response.data){
                     if(response.data[key]=="null"){
                  	   $("#"+key+"_error").attr("style","color:red");
                         $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
                     }
                     else if(response.data[key]=="valid"){
                         $("#"+key+"_error").html(" ");                                   
                     }
                       else if(response.data[key]=="invalid"){
							$("#"+key+"_error").attr("style","color:red");
							$("#"+key+"_error").html("Invalid value for "+$("#"+key).attr("title"));                           
                         
                     }
                     else if(response.data[key]=="duplicate"){
                  	   bootbox.alert("field aleady exist");
                        }
                  }
           }
	     },
		complete: function(){
	    	setTimeout(function(){		    	
	    		$('#addallocation').unmask();	
	    		//unmaskloading('addProjects');
			},500);
		}
	
      });
     return false; 
}
</script>

