	<script type="text/javascript" src="/js/jquery.autocomplete.multiselect.js"></script>
	<div id="addskillsdilog" class="modal hide fade" tabindex="-1" data-focus-on="input:first">
		
		<div class="modal-header">
			<h3>Add Skills</h3>
		</div>
		<div class="modal-body">
		<label class="control-label small-label">Skills:<sup style="color:#FF0000;">*</sup></label>
						<div class="controls small-margin">
							<input type="text" id="skillname" name="skillname"
								title="Skill Name" <?php if(isset($skill) && $skill->getName()!=''){?>
								value="<?php echo $skill->getName();}?>">
						</div>
						<div class="controls small-margin"><div id="skillname_error" class="error"></div></div>
		</div>
		<div class="modal-footer">
		<button type="button" id="closeskillmodal" class="btn btn-primary">Close</button>
		<button type="button" class="btn btn-primary" onclick="addSkills()">ADD</button>
		</div>
</div>	
		

<button id="btnAddskills" class="btn btn-success" data-toggle="modal" name="btnAddskills"  href="#addskillsdilog" style="margin-bottom:1em";>Add New Skills</button>




<?php foreach ($allocationarray as $rw) { 
			 $dater= $rw['date']; ?>
			 
<!-- Free User List Start  -->
<?php if ($type=="free"){?>			 
<div id="freeuserlist">
<table>
<?php foreach ($rw['freeuser'] as $rows){?>
<tr style="background-color: #DCD6D6;border: 1px solid #000;">

	<td style="background-color: #DCD6D6; border: 1px solid #000;">
	<div onclick="openaddresourceallocationdialog('<?php echo $rows['id']."','".$dater;?>')">
	<div>
		<label   id='userid' class='control-label' value="<?php echo $rows['id'];?>" for='inputUserSkills'>
					<?php if($rows['fname']!=null ){
								echo ucwords($rows['fname']." ".$rows['lname']);
							} ?>
		</label>
	</div>
	</div>
</td>
<td style="background-color: #DCD6D6; border: 1px solid #000;">
	<div >
	     <select name='skills' id='<?php echo "skills".$rows['id'] ?>'; data-placeholder='Choose a Skills' class='chosen-select' multiple='multiple'  style="background-color: #DCD6D6; width:350px;" tabindex='4'; onchange="adduserskills(<?php echo $rows['id'] ?>)")>
							<?php if(isset($skills) && sizeof($skills)>0){
									foreach ($skills as $row) { 
									$selected='';
									if(isset($rows['skills']) && $rows['skills'] > 0){
									foreach ($rows['skills'] as $skill){ 
									if($row->getId() == $skill['id']){
									$selected='selected';
									 } } }?>
									<option value='<?php echo $row->getId();?>' <?php echo $selected; ?> ><?php echo $row->getName(); ?> </option>
									<?php  } }?>
						</select>
	</div>
	</td>

</tr>

<?php } ?>
</table>
</div>
<?php } elseif ($type=="partial"){?>



<div id="partialallocated">
<table>
<?php foreach ($rw['user'] as $rows){?>
<tr>

	<td>
	<div class="row-fluid" href="openaddresourceallocationdialog('<?php echo $rows['id'];?>')" title="Allocate work"" >
		
		<label   id='allocateduserid' class='control-label' value="<?php echo $rows['id'];?>" for='inputUserSkills'>
					<?php if($rows['name']!=null ){
								echo ucwords($rows['name']);
							} ?>
		</label>
	</div>
</td>
<td>
	<div>
	     <select name='allocatedskills' id='skills' data-placeholder='Choose a Skills' class='chosen-select' multiple='multiple'  style='width:350px;' tabindex='4' onchange="adduserskills('<?php echo $rows['id']; ?>')")>
							<?php if(isset($skills) && sizeof($skills)>0){
									foreach ($skills as $skillrow) { 
										$selected='';
									if(isset($rows['skills']) && $rows['skills'] > 0){
									foreach ($rows['skills'] as $skill){ 
									 if($skillrow->getId() == $skill['id']){
										$selected='selected';
										break;
									 } } }?>
									<option value='<?php echo $skillrow->getId();?>' <?php echo $selected; ?> ><?php echo $skillrow->getName(); ?> </option>
									<?php  } }?>
						</select>
	</div>
	</td>

</tr>

<?php } ?>
</table>
</div>


<?php } ?>




<!-- Free User List End  -->
<?php } ?>
<?php if ($type=="allfree" && isset($freeuser) && count($freeuser)>0){ ?>

<div id="allfree">
<table>

<?php  foreach ($freeuser as $urw){?>
<tr>

	<td>
	<button class="btn" data-toggle="modal" onclick="openaddresourceallocationdialog('<?php echo $urw['id']."','$planningdate"?>')">
	<div>
		<label   id='userid' class='control-label' value="<?php echo $urw['id'];?>" for='inputUserSkills'>
					<?php if($urw['fname']!=null ){
								echo ucwords($urw['fname']." ".$urw['lname']);
							} ?>
		</label>
	</div>
	</button>
</td>
<td>
	<div>
	     <select name='allocatedskills' id='skills' data-placeholder='Choose a Skills' class='chosen-select' multiple='multiple'  style='width:350px;' tabindex='4' onchange="adduserskills('<?php echo $rows['id']; ?>')")>
							<?php if(isset($skills) && sizeof($skills)>0){
									foreach ($skills as $skillrow) { 
										$selected='';
									if(isset($urw['skills']) && $urw['skills'] > 0){  
									foreach ($urw['skills'] as $skill){ 
									 if($skillrow->getId() == $skill['id']){ ?>
									 
									 
									 <?php 
										$selected='selected';
										break;
									 } } }?>
									<option value='<?php echo $skillrow->getId();?>' <?php echo $selected; ?> ><?php echo $skillrow->getName(); ?> </option>
									<?php  } }?>
						</select>
	</div>
	</td>

</tr>

<?php } ?>
</table>
</div>


<?php }?>


<script type="text/javascript">
$(document).ready(function () {
    
    
	 $("#startdate").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       altField: "#altstartdate",
	       altFormat: "yy-mm-dd",
	    });
		$("#enddate").datepicker({
		       changeMonth: true,
		       changeYear: true,
		       showSecond: false,
		       dateFormat: 'dd/mm/yy',
		       altField: "#altenddate",
		       altFormat: "yy-mm-dd",
		    });
	$("#spent").timepicker({timeOnly:true});


}) ;



function addSkills() {
    var skills = $("#skillname").val();
    if(skills==""){
    	alert("skills cannot be left blank.");
		return false;
	}	
    $.ajax({
        type: "POST",
        url: "<?php echo $this->url('addskills');?>",
        data: {
            skills: skills
        },
        dataType: 'json',
        success: function (response) {
            if (response['returnvalue'] == "valid") {
            	alert("skills added succesfully");
            }
        },
        error: function (XMLHttpRequest, textStatus) {
        	alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
        },
    });
}
function addResourceAllocation(){
	var projectid = $("#projectlist").val();
	var userid = $("#userlist").val();
	var duration = $("#spent").val();
	var startdate = $("#altstartdate").val();
	var enddate = $("#altenddate").val();
	
	$.ajax({
		type: "POST",
		url: "<?php echo $this->url('addresourceallocation');?>",	         
		data: {projectid: projectid , userid :userid, duration :duration, startdate :startdate,enddate :enddate },
		dataType:'json',
		beforeSend: function () {
 			$('#addResourceAllocation').mask("Loading...");
 	 	 },
		success: function(response)
		{
			if(response['returnvalue']=="valid"){
				alert("Record has been added Successfully");
            }                       
            else if(response.returnvalue=="exception"){
            	alert("This Operation Could not be Completed,Please contact administrator");
                return false;
           }
           
            else{
                 for(var key in response.data){
                     if(response.data[key]=="null"){
                  	   $("#"+key+"_error").attr("style","color:red");
                         $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
                     }
                     
                     else if(response.data[key]=="valid"){
                  	   $("#"+key+"_error").html("");  
                     }
                    
                  }}
		},
		error: function(XMLHttpRequest,textStatus){
			alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		},
		
		complete: function(){
	    	setTimeout(function(){		    	
	    		$('#addResourceAllocation').unmask();	
	    		//unmaskloading('addProjects');
			},500);
		}	 
	});
	
}

var config = {
	    '.chosen-select': {},
	    '.chosen-select-deselect': {
	        allow_single_deselect: true
	    },
	    '.chosen-select-no-single': {
	        disable_search_threshold: 10
	    },
	    '.chosen-select-no-results': {
	        no_results_text: 'Oops, nothing found!'
	    },
	    '.chosen-select-width': {
	        width: "95%"
	    }
	}

$(".chosen-select").chosen(".chosen-select");
// 	for (var selector in config) {
// 	    $(".chosen-select").chosen(".chosen-select");
// 	}

function adduserskills(userid) {

    var skills = $("#skills" + userid).val();
    
	
    $.ajax({
        type: "POST",
        url: "<?php echo $this->url('adduserskills');?>",
        data: {
            userid: userid,
            skills: skills
        },
//         		dataType:'json',
        success: function (response) {

        },
        error: function (XMLHttpRequest, textStatus) {
        	alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
        },
    });

} 
$("#closeaddresourcemodel").click(function( event ) {
	$( "#addResourceAllocationModal" ).modal('hide');
});
$("#closeskillmodal").click(function( event ) {
	$( "#addskillsdilog" ).modal('hide');
});


</script>


<div id="addResourceAllocationModal" title="AddResourceAllocation" class="modal hide fade" tabindex="-1" data-focus-on="input:first" >
	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right:5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:1px;">Resource Allocation </h6>
    </div>
    <!-- dialog contents -->
	<div class="modal-body">
		<div id="addResourceAllocation" name="addResourceAllocation" title="Add Resource Allocation">
			
				<div class="row-fluid">
				<input id="userlist" style="display: none;"> </input>
				<div class="controls"><div id="userlist_error" ></div></div>
				</div>
				
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label" for="inputProject">Project:<sup style="color:#FF0000;">*</sup></label>
							<div class="controls">
								<select id="projectlist" name="project" title="Project" tabindex="1">
									<option value="">--Select--</option>
									<?php if(isset($project) && count($project)>0){
										for($i=0;$i<count($project);$i++){
											?>
									<option value="<?php echo $project[$i]['id'];?>"
									<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project[$i]['id']){echo 'selected="selected"';}?>  >
										<?php echo ucwords($project[$i]['name']); ?>
									</option>
									<?php }?>
									<?php }?>
								</select>
							</div>
							<div class="controls"><div id="projectlist_error"></div></div>
						</div>
				</div>
				

				
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">Duration: </label>
						<div class="controls">
							<input id="spent" name="spent" title="Spent Time" type="text" value=""/>
				<div class="controls"><div id="spent_error" ></div></div>
				</div>
				<div class="controls small-margin"><div id="spent_error"></div></div>
					</div>
				</div>
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">Start Date: </label>
						<div class="controls">
							<input type="text" id="startdate" name="startdate" title="Date" value="" /> 
							<input type="hidden" id="altstartdate" name="altstartdate" title="Date" value="" />
						</div>
					</div>
					
						<div class="control-group">
						<label class="control-label">End Date: </label>
						<div class="controls">
							<input type="text" id="enddate" name="enddate" title="End Date" value="" /> 
							<input type="hidden" id="altenddate" name="altenddate" title="Date" value="" />
						</div>
					</div>
				</div>
			
		</div>
    </div>
    <div class="modal-footer">
    	  <button type="button" id="closeaddresourcemodel"  class="btn btn-success">Close</button>
		  <button class="btn btn-success" data-toggle="modal" style="margin-left:33px" 
	    	type="button"  onclick="addResourceAllocation()">Submit</button>
    	  
    </div>
</div>