<button id="btnAddResourceAllocation" style="float:right;"  class="btn btn-success" name="btnAddResourceAllocation" style="margin-bottom:1em;">Allocate New Resource</button>

<script type="text/javascript" src="/js/bootbox.min.js"></script>
<?php 
use Zend\Authentication\AuthenticationService;
$auth=new AuthenticationService();
$currentuser= $auth->getIdentity()->id;
?>

<div id="addResourceAllocationModal" title="Add ResourceAllocation" class="modal hide fade" data-backdrop="static" 
	data-toggle="modal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right:5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:1px;">Enter Resource Allocation Details</h6>
    </div>
    <!-- dialog contents -->
	<div class="modal-body">
		<div id="addResourceAllocation" name="addResourceAllocation" title="Add Resource Allocation">
			<form  id="form" name="form" class="form-horizontal">
			<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Company:</label>
				<div class="controls">
					<select id="company" name="company" title="Company">
						<option value="0">--Select--</option>
						<?php for($i=0;$i<count($comanys);$i++){?>
						<option value='<?php echo $comanys[$i]['id'];?>'>
							<?php echo ucfirst($comanys[$i]['name']);?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="company_error" class="error"></div></div>
			</div>
		</div>
				<div class="row-fluid" style="display: inline;">
							<div class="control-group" style="float: left;">
							<label class="control-label" for="inputProject">Project:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
				<div style="float: left;">	
								<select id="project" name="project" title="Project" tabindex="1" disabled>
										<option value="0">--Select--</option>
										<?php if(isset($project) && count($project)>0){
											for($i=0;$i<count($project);$i++){
												?>
										<option value="<?php echo $project[$i]['id'];?>"
										<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project[$i]['id']){echo 'selected="selected"';}?>  >
											<?php echo ucwords($project[$i]['name']); ?>
										</option>
										<?php }?>
										<?php }?>
								</select>
					</div>			
						<div id="projectallocationAtAddForm" style="float: right; display: none;">
						<table   class="table-bordered" >
						<tr>
						<td>Project Estimate:<span id="projectEstimatedAtAddForm"></span></td>
						
						<td>Allocated: <span id="totalAllocatedAtAddForm"></span></td>
						
						<td>Spent:<span id="totalSpentAtAddForm"></span></td>
						</tr>
				        </table>
						</div>
				</div>
				<div class="controls"><div id="project_error"></div></div>
				</div>
				</div>
				
				
				<div class="row-fluid">
				<div class="control-group">
						<label class="control-label" for="inputProject">User:<sup style="color:#FF0000;">*</sup></label>
						<div class="controls">
						<div>
								<select id="userid" name="user" title="User" class="input-medium" disabled>
										<option value="0">--Select--</option>
										<?php if(isset($users) && $users!=null && $users!=""){?>
										<?php if(isset($users) && count($users)>0){
											for($i=0;$i<count($users);$i++){
												?>
										<option value="<?php echo $users[$i]->__get('id');?>"
										<?php if($currentuser==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
											<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
												echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
											}else{ echo ucwords($users[$i]->__get('fname'));
												} ?>
										</option>
										<?php }?>
										<?php }?>
										<?php }?>
								</select>
							</div>
							<div id="userallocationAtAddForm" style="float: right;display: none;">
								<table   class="table-bordered">
									<tr>
										<td>Allocated:<span id="userAllocatedAtAddForm"></span></td>
										<td>Spent:<span id="userSpentAtAddForm"></span></td>
									</tr>
						       </table>
						</div>
						</div>
				</div>
				</div>
				
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">Duration:<sup style="color:#FF0000;">*</sup> </label>
						<div class="controls">
							<input id="duration" name="Duration" title="Duration" type="text" value=""/>
						</div>
				<div class="controls small-margin "><div id="duration_error"></div></div>
					</div>
					<div class="control-group">
						<label class="control-label">Per Day Duration: </label>
						<div class="controls">
							<input id="perDayDuration" name="perDayDuration" title="perDayDuration" type="text" value=""/>
						</div>
				<div class="controls small-margin "><div id="duration_error"></div></div>
					</div>
					
				</div>
				<div class="row-fluid inline" style="display: inline">
						<div class="control-group">
						<label class="control-label">Start Date:<sup style="color:#FF0000;">*</sup> </label>
						<div class="controls">
							<input type="text" id="startdate" name="startdate" title="Date" value="" /> 
							<input type="hidden" id="altstartdate" name="altstartdate" title="Date" value="" />
						</div>
					</div>
					
						<div class="control-group" style="float: left;display: none;" >
						<label class="control-label">End Date: </label>
						<div class="controls">
							<input type="text" id="enddate" name="enddate" title="End Date" value="" /> 
							<input type="hidden" id="altenddate" name="altenddate" title="Date" value="" />
						</div>
					</div>
						
				</div>
			</form>
		</div>
    </div>
    <div class="modal-footer">
    	<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="closemodeldilog" data-dismiss="modal" >Close</button>
	    <button class="btn btn-success" data-toggle="modal" style="margin-left:33px" 
	    	type="button" value="Ok" id="ok" name="ok" onclick="addResourceAllocation()">Submit</button>
    </div>
</div>
<h2 class="title">Resource Allocation</h2><hr />

<div  class="form-horizontal" name="form" >
	<div class="row-fluid">
	
		<div class="span4 control-group">
				<label class="control-label">Company:</label>
				<div class="controls">
					<select id="companyFilter" name="companyFilter" title="CompanyFilter">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($comanys);$i++){?>
						<option value='<?php echo $comanys[$i]['id'];?>'>
							<?php echo ucfirst($comanys[$i]['name']);?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="companyFilter_error" class="error"></div></div>
			</div>
	
	
	
		<div class="span4 control-group">
							<label class="control-label" for="inputProject">Project:</label>
							<div class="controls">
					
			<select id="allocatedproject" name="allocatedproject" title="allocatedProject" tabindex="1">
									<option value="">--Select--</option>
									<?php if(isset($project) && count($project)>0){
										for($i=0;$i<count($project);$i++){
											?>
									<option value="<?php echo $project[$i]['id'];?>"
									<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project[$i]['id']){echo 'selected="selected"';}?>  >
										<?php echo ucwords($project[$i]['name']); ?>
									</option>
									<?php }?>
									<?php }?>
								</select>
							</div>
							<div class="controls"><div id="project_error"></div></div>
						</div>
	
	
	
	
	
					<div class="span4 control-group">
						<label class="control-label" for="inputProject">User:</label>
						<div class="controls">
							<select id="allocateduserid" name="user" title="User" class="input-medium">
								<option value="">--Select--</option>
								<?php if(isset($users) && $users!=null && $users!=""){?>
								<?php if(isset($users) && count($users)>0){
									for($i=0;$i<count($users);$i++){?>
										
								<option value="<?php echo $users[$i]->__get('id');?>">
									<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
										echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
									}else{ echo ucwords($users[$i]->__get('fname'));
										} ?>
								</option>
								<?php }?>
								<?php }?>
								<?php }?>
							</select>
						</div>
					</div>
			
	</div>
	
	<div class="row-fluid" >
	<div class="span4 control-group">
			<label class="control-label">Date: </label>
			<div class="controls">
				<input type="text" id="allocationDate" name="allocationDate" title="Date" value="" />
				<input type="hidden" id="alternate_allocationDate" name="alternate_allocationDate" title="Date" value="" />
<!--			<div id="activity_date_error"></div>-->
				</div>
			</div>	
		<div class="span6 control-group">
			<div class="controls">
				<button id="clear" name="clear" class="btn btn-success right-margin">Reset Filters</button>
				<button id="filterAllocation" name="filterAllocation" class="btn btn-success right-margin">Apply Filter</button>
				
			</div>
		</div>
	</div>			
		</div>	
			
		
		
<div style="height: 100%;" id="gridContainer">
	<table id="list">
	</table>
	<div id="pager"></div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	 $('#company').bind('change', function(ev) {
		 getProjectByCompany('add');
		 getUserByCompany('add');
	  });
	 $('#companyFilter').bind('change', function(ev) {
		 getProjectByCompany('filter');
		 getUserByCompany('filter');
	  });

	 
	 $("#allocationDate").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       onSelect: function (selectedDate){
	       
	       },
	       altField: "#alternate_allocationDate",
	       altFormat: "yy-mm-dd",
     });

	
	jQuery("#list").jqGrid({
		url:"<?php echo $this->url('gridresourceallocation');?>",
		datatype: "json",
		mtype: 'POST',
		colNames:['User Name','Project','Allocation Date','Duration','Action'],
		colModel :[
		{name:'user',index:'user',sortable:true},
		{name:'project',index:'status',sortable:true},
		{name:'allocation_date',index:'allocation_date',sortable:true},
		{name:'duration', index:'duration',sortable:true},
		{name:'action', index:'action',editable: true}
		],
		rowNum:100,
	    rowList:[100,200,500],
	    navigator:true,
	    pager: '#pager',
	    sortname: 'id',
	    viewrecords: true,
	    sortorder: "desc",
	    height:"400px",
	});
	jQuery("#list").setGridWidth($('#gridContainer').width(), true);
	$("#startdate").datepicker({
       changeMonth: true,
       changeYear: true,
       showSecond: false,
      // minDate: 0 ,
       dateFormat: 'dd/mm/yy',
       altField: "#altstartdate",
       altFormat: "yy-mm-dd",
    });
	$("#enddate").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       minDate: 0 ,
	       dateFormat: 'dd/mm/yy',
	       altField: "#altenddate",
	       altFormat: "yy-mm-dd",
	    });

// 	$("#perDayDuration").timepicker({timeOnly:true,showHour:8});
	$('#project').bind('change', function(ev) {
		getprojectallocationdetail();
		getuserallocationdetailbyproject();
	});
	$('#userid').bind('change', function(ev) {
		getuserallocationdetailbyproject();
	});
	$('#duration').bind('change', function(ev) {
		
		var duration = $("#duration").val();
		if(8<=duration ){
			$("#perDayDuration").val('8');
			}else {
				$("#perDayDuration").val(duration);
				}
		var allocated=0;
			allocated = $("#totalAllocatedAtAddForm").val();
		if(allocated ==""){
			allocated=0;
			}
		var projectEstimate= parseInt($("#projectEstimatedAtAddForm").val());
		var allocationRemain= 0;
		if(projectEstimate > allocated)
		allocationRemain = projectEstimate - allocated;

		var extraAllocation =0;
		if(allocated >projectEstimate )
		extraAllocation = allocated - projectEstimate;
		
		if(duration > allocationRemain &&  allocationRemain>0){
			alert("Project remain allocation is "+allocationRemain+"Hr");
// 			$("#duration").val(allocationRemain);
			}

		if(extraAllocation>0){
			alert("Already allocated "+extraAllocation +"hr extra");
			}
		
	  });
	  
	$('#perDayDuration').bind('change', function(ev) {
		var duration = $("#duration").val();
		var perdayDuration=$("#perDayDuration").val();
		if( perdayDuration > duration || perdayDuration > 24  ){
				if(perdayDuration > 24 ){
					alert("Per Day Duration is more than one day duration");
					if(duration > 24)
					$("#perDayDuration").val("24");

					if(duration <= 24)
						$("#perDayDuration").val(duration);
					}
				if(perdayDuration > duration ){
						alert("Per Day Duration is more than duration");
						$("#perDayDuration").val(duration);
				}
			
			}
		});
	
	$("#btnAddResourceAllocation").click(function( event ) {
		$("#addResourceAllocationModal" ).modal({show:true});
		clrAddAllocationForm();
	});
	$("#clear").click(function( event ) {
		  event.preventDefault();
		  clr();
		});	
	$("#filterAllocation").click(function( event ) {
		   event.preventDefault();
		   filterAllocation();
		});
});

function filterAllocation(){
	var  companyId=$("#companyFilter").val();
	var  projectId=$("#allocatedproject").val();
	var   userid = $("#allocateduserid").val();
	var   date = $("#allocationDate").val();
	var   altdate = " ";
	 if(date!=""){
		 altdate = $("#alternate_allocationDate").val();
		 }else{
			 altdate = "";
			 }
		    $("#list").setGridParam({ postData: {companyid:companyId,userid:userid,altdate:altdate,projectid:projectId} });
	    $("#list").trigger('reloadGrid');
}

function clr(){
	 document.getElementById("companyFilter").value='';
	 document.getElementById("allocatedproject").value='';
	 

	 document.getElementById("allocateduserid").value='';
   	 document.getElementById("allocationDate").value='';
     document.getElementById("alternate_allocationDate").value='';
     filterAllocation();
}

function addResourceAllocation(){
	var projectid = $("#project").val();
	var userid = $("#userid").val();
	var duration = $("#duration").val();
	var perDayDuration = $("#perDayDuration").val();
	var startdate = $("#altstartdate").val();
	var enddate = $("#altenddate").val();
	
	
	$.ajax({
		type: "POST",
		url: "<?php echo $this->url('addresourceallocation');?>",	         
		data: {projectid: projectid , userid :userid, duration :duration,perdayduration :perDayDuration ,startdate :startdate,enddate :enddate },
		dataType:'json',
	
		success: function(response)
		{
			if(response['returnvalue']=="valid"){
          	 	$( "#addResourceAllocationModal" ).modal('hide');
         		alert("Record has been added Successfully");
         		$("#list").trigger("reloadGrid");
			}
		},
		error: function(XMLHttpRequest,textStatus){
			alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		},
	});
	
}


function deleteResourceAllocation(id){
	$.ajax({
		type: "POST",
		url: "<?php echo $this->url('deleteresourceallocation');?>",	         
		data: {id: id },
		dataType:'json',
	
		success: function(response)
		{
			if(response['returnvalue']=="valid"){
          		alert("Record has been deleted Successfully");
         		$("#list").trigger("reloadGrid");
			}
		},
		error: function(XMLHttpRequest,textStatus){
			alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		},
	});
}

function getProjectByCompany(flag){
	 var companyId ="";
	 var projectDropDown="";
	 var op="";
	if(flag=='add'){
		companyId = $("#company").val();
		projectDropDown = document.getElementById('project');		     		     
		 projectDropDown.options.length=0;
       op = document.createElement("option");		     
	    op.value="0";
	    op.text="--Select--";
	    projectDropDown.options.add(op);
	}
	else{
		 companyId = $("#companyFilter").val();
		  projectDropDown = document.getElementById('allocatedproject');		     		     
		 projectDropDown.options.length=0;
	      op = document.createElement("option");		     
		    op.value="";
		    op.text="--Select--";
		    projectDropDown.options.add(op);
		}
     $.ajax({	
    	 type: "POST",	      
    	 url: "<?php echo $this->url('getProjectByCompany');?>",
        data: {companyid: companyId},	
        dataType:"json",
        success: function(response)
         {
        	 if(response['returnvalue']=="valid"){
            var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    projectDropDown.options.add(op);
		    $("#project").removeAttr("disabled");
		    }	
        	 }else{
//                  alert("Project not found");
     	    }
         }       
     });

}

function getUserByCompany(flag){
	 var companyId ="";
	 var userDropDown="";
	 var op="";
	if(flag=='add'){
		companyId = $("#company").val();
		userDropDown = document.getElementById('userid');		     		     
		userDropDown.options.length=0;
      op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
	    userDropDown.options.add(op);
	}
	else{
		 companyId = $("#companyFilter").val();
		 userDropDown = document.getElementById('allocateduserid');		     		     
		 userDropDown.options.length=0;
	      op = document.createElement("option");		     
		    op.value="";
		    op.text="--Select--";
		    userDropDown.options.add(op);
		}
    $.ajax({	
   	 type: "POST",	      
   	 url: "<?php echo $this->url('getUserByCompany');?>",
       data: {companyid: companyId},	
       dataType:"json",
       success: function(response)
        {
       	 if(response['returnvalue']=="valid"){
           var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");
		    if(response.data[$i]['needallocation']==1){
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    userDropDown.options.add(op);
		    }
		     $("#userid").removeAttr("disabled");
		    }	
       	 }else{
//                 alert("User not found");
    	    }
        }       
    });

}

function getprojectallocationdetail(){
	var projectId = $("#project").val();
	 $("#projectEstimatedAtAddForm").html("0");
   	 $("#totalAllocatedAtAddForm").html("0");
   	 $("#totalSpentAtAddForm").html("0");
   	 
   	 $("#projectEstimatedAtAddForm").val("0");
   	 $("#totalAllocatedAtAddForm").val("0");
   	 $("#totalSpentAtAddForm").val("0");
	   $.ajax({	
		   	 type: "POST",	      
		   	 url: "<?php echo $this->url('getprojectallocationdetail');?>",
		       data: {projectid: projectId},	
		       dataType:"json",
		       success: function(response)
		        {  
		       	 if(response['returnvalue']=="valid"){
		       		if(parseInt(response.estimatedHours)>0)
			       	 $("#projectEstimatedAtAddForm").html(response.estimatedHours);

					if(parseInt(response.allocated)>0)	
				      $("#totalAllocatedAtAddForm").html(response.allocated);

					if(parseInt(response.totalSpent)>0)
			       	 $("#totalSpentAtAddForm").html(response.totalSpent);

					if(parseInt(response.estimatedHours)>0)
			       	 $("#projectEstimatedAtAddForm").val(response.estimatedHours);
					if(parseInt(response.allocated)>0)
			       	 $("#totalAllocatedAtAddForm").val(response.allocated);
					if(parseInt(response.totalSpent)>0)
			       	 $("#totalSpentAtAddForm").val(response.totalSpent);
					if(parseInt(response.estimatedHours)>0 || parseInt(response.allocated) > 0 || parseInt(response.totalSpent) > 0){
						document.getElementById("projectallocationAtAddForm").style.display = "block";
						}
			       	
			       	 
		       	 }else{
//		                 alert("User not found");
		    	    }
		        }       
		    });
	}

function getuserallocationdetailbyproject(){
	var projectId = $("#project").val();
	var userId= $("#userid").val();
	   $.ajax({	
		   	 type: "POST",	      
		   	 url: "<?php echo $this->url('getuserallocationdetailbyproject');?>",
		       data: {projectid: projectId,userid:userId},	
		       dataType:"json",
		       success: function(response)
		        {  
		       	 if(response['returnvalue']=="valid"){
		       		if(parseInt(response.allocated)>0){
					       	 $("#userAllocatedAtAddForm").html(response.allocated);
					       	 $("#userAllocatedAtAddForm").val(response.allocated);
		       			}else{
		       				$("#userAllocatedAtAddForm").html("0");
				       	 	$("#userAllocatedAtAddForm").val("0");
			       		}
		       		if(parseInt(response.totalSpent)>0){
					       	 $("#userSpentAtAddForm").html(response.totalSpent);
					       	 $("#userSpentAtAddForm").val(response.totalSpent);
		       		}else{
				       		 $("#userSpentAtAddForm").html("0");
					       	 $("#userSpentAtAddForm").val("0");
			       		}
			       	if(parseInt(response.allocated)>0 || parseInt(response.totalSpent)>0 ){
				     
						document.getElementById("userallocationAtAddForm").style.display = "block";
						}
		       	 }else{
//		                 alert("User not found");
		    	    }
		        }       
		    });	
}

function clrAddAllocationForm(){
	 $("#projectEstimatedAtAddForm").html("");
   	 $("#totalAllocatedAtAddForm").html("");
   	 $("#totalSpentAtAddForm").html("");
   	 
   	 $("#projectEstimatedAtAddForm").val("");
   	 $("#totalAllocatedAtAddForm").val("");
   	 $("#totalSpentAtAddForm").val("");
	
	 $("#userAllocatedAtAddForm").val("");
   	 $("#userSpentAtAddForm").val("");
   	 $("#userAllocatedAtAddForm").html("");
  	 $("#userSpentAtAddForm").html("");

  	$("#project").val("");
	$("#userid").val("");
	$("#duration").val("");
	$("#perDayDuration").val("");
	$("#startdate").val("");
	$("#enddate").val("");
	$("#altstartdate").val("");
	$("#altenddate").val("");
	document.getElementById("userallocationAtAddForm").style.display = "none";
	document.getElementById("projectallocationAtAddForm").style.display = "none";
}


	</script>