<script type="text/javascript" src="/js/bootbox.min.js"></script>
<link rel="stylesheet" href="/css/chosen.css">
<div id="skillssets">

	<div id="addskillsdilog" class="groove-table signupddivie" style="display:none" >
		<h2 class="title">Add Skills</h2><hr/>
			<div class="span4 control-group">
				<label class="control-label small-label">Skills:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls small-margin">
					<input type="text" id="skillname" name="skillname"
						title="Skill Name" <?php if(isset($skill) && $skill->getName()!=''){?>
						value="<?php echo $skill->getName();}?>">
				</div>
				<div class="controls small-margin"><div id="skillname_error" class="error"></div></div>
				<button onclick="addSkills()">ADD</button>
			</div>
		
	</div>
<h2 class="title">Skills sets</h2><hr />
<button id="btnAddskills" class="btn btn-success" name="btnAddskills"  onclick="openSkillsDilog()" style="margin-bottom:1em";>Add New Skills</button>


<?php if(isset($userskills) && count($userskills)>0){
foreach($userskills as $userskills){?>
<div>
	<div class="span5 control-group">
					<label   id="userid" class="control-label" value="<?php echo $userskills['id'];?>" for="inputUserSkills">
					<?php if($userskills['name']!=null ){
								echo ucwords($userskills['name']);
							} ?>
					</label>
	</div>
					
	<div class="span5 control-group" style="">
				<select name="skills" id="<?php echo "skills".$userskills['id']?>" data-placeholder="Choose a Skills" class="chosen-select" multiple="multiple" style="width:350px;" tabindex="4" onchange="adduserskills(<?php echo $userskills['id']?>)">
					<?php if(isset($skills) && sizeof($skills)>0){
					foreach ($skills as $row) { 
					$selected="";
					 foreach ($userskills['skills'] as $skill){
					if($row->getId() == $skill['id']){
					  $selected="selected";
						 } }?>
					<option value="<?php echo $row->getId(); ?>" <?php echo $selected; ?> ><?php echo $row->getName(); ?></option>
					<?php  }
							}?>
				</select>
						
  	</div>
				
</div>
<?php } }?>
</div>




<script type="text/javascript">
$(document).ready(function () {
    $("#addskillsdilog").dialog({
        autoOpen: false,
        width: 400,
        title: 'Add Skills',
    });
    

});

function openSkillsDilog() {
    //	$( "#addskillsdilog" ).modal({show:true});
    $("#addskillsdilog").dialog("open");
}

function addSkills() {
    var skills = $("#skillname").val();
    $.ajax({
        type: "POST",
        url: "<?php echo $this->url('addskills');?>",
        data: {
            skills: skills
        },
        dataType: 'json',
        success: function (response) {
            if (response['returnvalue'] == "valid") {
            	alert("skills added succesfully");
            }
        },
        error: function (XMLHttpRequest, textStatus) {
        	alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
        },
    });
}


var config = {
	    '.chosen-select': {},
	    '.chosen-select-deselect': {
	        allow_single_deselect: true
	    },
	    '.chosen-select-no-single': {
	        disable_search_threshold: 10
	    },
	    '.chosen-select-no-results': {
	        no_results_text: 'Oops, nothing found!'
	    },
	    '.chosen-select-width': {
	        width: "95%"
	    }
	}
	for (var selector in config) {
	    $(selector).chosen(config[selector]);
	}

function adduserskills(userid) {

    var skills = $("#skills" + userid).val();

    $.ajax({
        type: "POST",
        url: "<?php echo $this->url('adduserskills');?>",
        data: {
            userid: userid,
            skills: skills
        },
//         		dataType:'json',
        success: function (response) {

        },
        error: function (XMLHttpRequest, textStatus) {
        	alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
        },
    });

} 
</script>
