<?php // print_r($response); exit;
use IntranetUtils\Common;
$common=new Common();
// echo $allocationId;exit;
// print_r($allocationRecord);exit;
?>

<div id="record">
<h2 class="title">Allocation Detail</h2>
	<hr/>
<table class="table table-striped table-condensed">
	<tr>
		<td style="width:15%;"><b>Project:</b></td>
		<td>
			<label id="project" name="project" title="project"><?php if(isset($project)){echo $project[0]['name'];}?></label>
			<input type="hidden" id="projectid" name="projectid"
				value="<?php if(isset($allocationRecord) && $allocationRecord->getProject_id()!=null){echo $allocationRecord->getProject_id();}?>" />			
		</td>
	</tr>
	<tr>
		<td><b>Title:</b></td>
		<td>
			<label id="title" name="title" title="Title">
				<?php if(isset($allocationRecord) && $allocationRecord->getTitle()!=null){echo $allocationRecord->getTitle();}?>
			</label>
		</td>
	</tr>
		<tr>
		<td><b>Start Date:</b></td>
		<td><label id="start_date" name="start_date" title="Start Date">
				<?php if(isset($startDate) && $startDate!=""){echo $startDate;}?>
			</label>
			<input type="hidden" id="alternate_start_date"
			name="alternate_start_date" title="Start Date"
			value="<?php if(isset($startDate) && $startDate!=""){echo $startDate;}?>" />
			<div id="start_date_error"></div>
		</td>
	</tr>
	
		<tr>
		<td><b>End Date:</b></td>
		<td><label id="end_date" name="end_date" title="End Date">
				<?php if(isset($endDate) && $endDate!=""){echo $endDate;}?>
			</label>
			<input type="hidden" id="alternate_end_date"
			name="alternate_end_date" title="End Date"
			value="<?php if(isset($endDate) && $endDate!=""){echo $endDate;}?>" />
			<div id="end_date_error"></div>
		</td>
	</tr>
	<tr>
		<td><b>Created By:</b></td>
		<td><label id="priority" name="priority" title="priority">
				<?php if(isset($activityRecord) && $activityRecord->getPriority_id()!=null){echo $activityRecord->getPriority_id();}?>
			</label>
		</td>
	</tr>
</table>

</div>



<div id="addResourceAllocationModal" title="Add ResourceAllocation" class="modal hide fade" data-backdrop="static" 
	data-toggle="modal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right:5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:1px;">Enter Resource Allocation Details</h6>
    </div>
    <!-- dialog contents -->
	<div class="modal-body">
		<div id="addResourceAllocation" name="addResourceAllocation" title="Add Resource Allocation">
			
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label" for="inputProject">User:<sup style="color:#FF0000;">*</sup></label>
						<div class="controls">
								<select id="userid" name="userid">
								<option value="">--Select--</option>
								<?php if(isset($userlog) && count($userlog)>0){
									for($i=0;$i<count($userlog);$i++){?>
										<option value="<?php echo $userlog[$i]->__get('id');?>"
										<?php if($currentLoggedInUser==$userlog[$i]->__get('id')){echo 'selected="selected"';}?>>
											<?php if($userlog[$i]->__get('lname')!=null && $userlog[$i]->__get('lname')!=""){
												echo ucwords($userlog[$i]->__get('fname')." ".$userlog[$i]->__get('lname'));
											}else{ echo ucwords($userlog[$i]->__get('fname'));
										} ?>
										</option>
									<?php }?>
								<?php }?>
							</select>
						</div>
					</div>
				</div>
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">Duration: </label>
						<div class="controls">
							<input id="spent" name="spent" title="Spent Time" type="text" value=""/>
						</div>
				<div class="controls small-margin"><div id="spent_error"></div></div>
					</div>
				</div>
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">Date: </label>
						<div class="controls">
							<input type="text" id="date" name="date" title="Date" value="" /> 
							<input type="hidden" id="altdate" name="altdate" title="Date" value="" />
						</div>
					</div>
				</div>
			
		</div>
    </div>
    <div class="modal-footer">
    	<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="closemodeldilog" data-dismiss="modal" >Close</button>
	    <button class="btn btn-success" data-toggle="modal" style="margin-left:33px" 
	    	type="button" value="Ok" id="ok" name="ok" onclick="addResourceAllocation(<?php echo $allocationId;?>)">Submit</button>
    </div>
</div>

	<div class="tab-content" style="border-top:2px solid gray;margin-top:-1em;">
		<div id="subactivities" title="Sub Activities" class="tab-pane active" style="margin-top:1em;">
				<div class="row-fluid">
					<div class="span4 control-group">
						<label class="control-label">User:<sup style="color:#FF0000;">*</sup></label>
						<div class="controls">
							<select id="seluser" name="seluser">
								<option value="">--Select--</option>
								<?php if(isset($userlog) && count($userlog)>0){
									for($i=0;$i<count($userlog);$i++){?>
										<option value="<?php echo $userlog[$i]->__get('id');?>"
										<?php if($currentLoggedInUser==$userlog[$i]->__get('id')){echo 'selected="selected"';}?>>
											<?php if($userlog[$i]->__get('lname')!=null && $userlog[$i]->__get('lname')!=""){
												echo ucwords($userlog[$i]->__get('fname')." ".$userlog[$i]->__get('lname'));
											}else{ echo ucwords($userlog[$i]->__get('fname'));
										} ?>
										</option>
									<?php }?>
								<?php }?>
							</select>
						</div>
					</div>
					<div class="span4 control-group">
						<label class="control-label">Allocation Date:</label>
						<div class="controls">
							<input type="text" id="filterbydate" name="filterbydate" value="">
							<input type="hidden" id="alternate_filterbydate" name="alternate_filterbydate" value="">
						</div>
					</div>
					<div class="span4 control-group">
						<div class="controls">
							<button class="btn btn-success" id="searchlog" name="searchlog">Apply Filter</button>
							<button class="btn btn-success" id="clear" name="clear">Clear Filter</button>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span4 control-group">
						<label class="control-label">Total Spent Hours:</label>
						<div class="controls">
							<input type="text" id="totalspenttime" name="totalspenttime" size="1" readonly="readonly" value="" />
						</div>
					</div>
					<div class="span4 control-group">
						<div class="controls">
							<button class="btn btn-success" id="btnAddResourceAllocation" name="btnAddResourceAllocation">Add New Resource</button>
						</div>
					</div>
				</div>
			
			
<div style="min-height: 500px;" id="gridContainer">
	<table id="list">
	</table>
	<div id="pager"></div>
</div>
		</div>
		
	</div>


<script type="text/javascript">
$(document).ready(function(){
	jQuery("#list").jqGrid({
		url:"<?php echo $this->url('gridresourceallocation');?>",
		datatype: "json",
		mtype: 'POST',
		colNames:['User Name','Project','Allocation Date','Duration','Action'],
		colModel :[
		{name:'user',index:'user',sortable:false},
		{name:'project',index:'status',sortable:false},
		{name:'allocation_date',index:'allocation_date',sortable:false},
		{name:'duration', index:'duration',sortable:false},
		{name:'action', index:'action',editable: false}
		],
	  	rowNum:20,
	    rowList:[100,300,500],
	    navigator:true,
	    pager: '#pager',
	    sortname: 'id',
	    viewrecords: true,
	    sortorder: "desc",
	    height:"400px",
	});

	resizegrid("gridContainer","list"); 
	 jQuery("#list").setGridWidth($('#gridContainer').width()-10, true);
	 
	$("#date").datepicker({
       changeMonth: true,
       changeYear: true,
       showSecond: false,
       dateFormat: 'dd/mm/yy',
       altField: "#altdate",
       altFormat: "yy-mm-dd",
    });

	 $("#filterbydate").datepicker({	
	     changeMonth: true,
	     changeYear: true,     
	     dateFormat: 'dd/mm/yy',     
	     onSelect: function (selectedDate){
	     
	     },
	     altField: "#alternate_filterbydate",
	     altFormat: "yy-mm-dd",     
	     });
	 $("#searchlog")//.button()
	 .click(function( event ) {
	  event.preventDefault();
	  filterActivitylog();
	});
	 $("#clear")//.button()
	 .click(function( event ) {
	  event.preventDefault();
	  clr();
	});
	    
	$("#spent").timepicker({timeOnly:true});
	$("#btnAddResourceAllocation").click(function( event ) {
		$( "#addResourceAllocationModal" ).modal({show:true});
	});
});

function addResourceAllocation(id){
	var projectid = $("#projectid").val();
	var userid = $("#userid").val();
	var duration = $("#spent").val();
	var date = $("#altdate").val();
	
	$.ajax({
		type: "POST",
		url: "<?php echo $this->url('addresourceallocation');?>",	         
		data: {id: id,projectid: projectid , userid :userid, duration :duration, date :date },
		dataType:'json',
		beforeSend: function () {
 			//$('#addResourceAllocation').mask("Loading...");
 	 	 },
		success: function(response)
		{
			if(response['returnvalue']=="valid")
		    {
     	  		alert("Added successful");
     	  		$("#addResourceAllocationModal").modal('hide');
	       	  	$("#list").trigger('reloadGrid');	        	         
	     	}
		},
		error: function(XMLHttpRequest,textStatus){
			alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		},
	});
	
}

function filterAllocationResource(){
	 var   userid = $("#seluser").val();
	 var   altdate = $("#alternate_filterbydate").val();
	 
		$("#list").setGridParam({ postData: {seluser:userid,alternate_adate:altdate} });
	    $("#list").trigger('reloadGrid');
   }
function clr(){
	 document.getElementById("seluser").value='';
	 document.getElementById("filterbydate").value='';
	 document.getElementById("alternate_filterbydate").value='';
	   }

function deleteResourceAllocation(id){
	 if(window.confirm('Are you sure you want to delete this Allocation?'))
		{	 
	 $.ajax({ 
	     type: "POST",
	     url: "<?php echo $this->url('deleteresourceallocation'); ?>",             
	     data: {id: id },
	     dataType:"json",
	     beforeSend: function () {
				$('#list').mask("Loading...");
		 	 },
	     success: function(response)
	     {   	    		
	     if(response['returnvalue']=="valid"){
    	 		 alert("record deleted");
	       	  $("#list").trigger('reloadGrid');	        	         
	      }   else{
		        if(response.data['user']=="null"){
		      	  	alert("you are not allowed to delete this Allocation");
				}
			}
    
	     },
	     error: function(XMLHttpRequest,textStatus){
	    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
	   	},
		complete: function(){
	    	setTimeout(function(){		    	
	    		$('#list').unmask();	
	    		//unmaskloading('addProjects');
			},500);
		}
	   });
		}
	 }
	   

</script>