
<?php
use IntranetUtils\Common;
use Zend\Authentication\AuthenticationService;
$auth=new AuthenticationService();

$common=new Common();

?>
<div id="addactivity">
	<h2 class="title">
		<?php if(isset($activityRecord) && $activityRecord->getId()!=null){ 
			echo "Edit";
		}else{echo "Add";
		}?>
		Activity
	</h2>
	<hr />
	<form action="" method="post" id="frmaddactivity" class="form-horizontal">
		
			<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Company:</label>
				<div class="controls">
					<select id="company" name="company" title="Company">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($comanys);$i++){?>
						<?php if($auth->getIdentity()->isadmin==1){?>
						<option value='<?php echo $comanys[$i]['id'];?>'>
							<?php echo ucfirst($comanys[$i]['name']);?>
						</option>
						<?php }elseif ($auth->getIdentity()->company_id==$comanys[$i]['id']){?>
						<option value='<?php echo $comanys[$i]['id'];?>' selected="selected">
							<?php echo ucfirst($comanys[$i]['name']);?>
						</option>
						<?php }}?>
					</select>
				</div>
				<div class="controls"><div id="company_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="span5 control-group">
				<label class="control-label" for="inputProject">Project:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="project" name="project" title="Project" tabindex="1">
						<option value="">--Select--</option>
						<?php if(isset($project) && count($project)>0){
							foreach ($project as $project){
								?>
						<option value="<?php echo $project['id'];?>"
						<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project['id']){
							$selected_company=$project['company_id'] ;
							$selected_project=$project['id'] ;
							echo 'selected="selected"';}?>  >
							<?php echo ucwords($project['name']); ?>
						</option>
						<?php }?>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="project_error"></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputMilestone">Milestone:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="milestone" name="milestone" title="Milestone" tabindex="2">
						<option value="">--Select--</option>
						<?php if(isset($milestone) && count($milestone)>0){
							 for($i=0;$i<count($milestone);$i++){?>
						<option value="<?php echo $milestone[$i]['id'];?>"
						<?php if(isset($activityRecord) && $activityRecord->getMilestone_id()!=null && $activityRecord->getMilestone_id()==$milestone[$i]['id']){echo 'selected="selected"';}?> ">
							<?php echo ucwords($milestone[$i]['name'])."(".ucwords($milestone[$i]['pname'].")"); ?>
						</option>
						<?php }?>
						<?php }?>
				</select>					
				</div>
				<div class="controls"><div id="milestone_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span5 control-group">
				<label class="control-label" for="inputMilestone">Subject:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="subject" name="subject" tabindex="3" title="Subject"
					<?php if(isset($activityRecord) && $activityRecord->getSubject()!=null){echo 'value="'.$activityRecord->getSubject().'"';}?> />
				</div>
				<div class="controls"><div id="subject_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputCategory">Category:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="category" name="category" title="Category" tabindex="4">
						<option value="">--Select--</option>
						<?php if(isset($category) && count($category)>0){
							for($i=0;$i<count($category);$i++){
								?>
						<option value="<?php echo $category[$i]['id'];?>"
						<?php if(isset($activityRecord) && $activityRecord->getCategory_id()!=null && $activityRecord->getCategory_id()==$category[$i]['id']){echo 'selected="selected"';}?>>
							<?php echo ucwords($category[$i]['name']); ?>
						</option>
						<?php }?>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="category_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span5 control-group">
				<label class="control-label" for="inputStatus">Status:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="status" name="status" title="Status" tabindex="5">
						<option value="">--Select--</option>
						<?php if(isset($status) && count($status)>0){
							for($i=0;$i<count($status);$i++){
								?>
						<option value="<?php echo $status[$i]['id'];?>"
						<?php if(isset($activityRecord) && $activityRecord->getStatus_id()!=null && $activityRecord->getStatus_id()==$status[$i]['id']){echo 'selected="selected"';}?>>
							<?php echo ucwords($status[$i]['name']); ?>
						</option>
						<?php }?>
						<?php }?>
					</select>					
				</div>
				<div class="controls"><div id="status_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputPriority">Priority:</label>
				<div class="controls">
					<select id="priority" name="priority" title="Priority" tabindex="6">
						<?php for($i=1;$i<=5;$i++){?>
						<option value="<?php echo $i;?>"
						<?php if(isset($activityRecord) && $activityRecord->getPriority_id()!=null && $activityRecord->getPriority_id()==$i){echo 'selected="selected"';}?>>
							<?php echo $i;?>
						</option>
						<?php }?>
					</select>					
				</div>
				<div class="controls"><div id="priority_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span5 control-group">
				<label class="control-label" for="inputAssignedUser">Assigned User:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<textarea name="assigneduser" id="assigneduser" tabindex="7" title="Assigned User" rows="4" class="input-xlarge"><?php if(isset($auName) && $auName!=null){echo $auName;}?></textarea>	
				</div>
				<div class="controls"><div id="assigneduser_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputDescription">Description:</label>
				<div class="controls">
					<textarea id="description" name="description" tabindex="8" title="Description" rows="4" 
						class="input-xlarge"><?php if(isset($activityRecord) && $activityRecord->getDescription()!=null){
							echo $activityRecord->getDescription();
						}?></textarea>
				</div>
				<div class="controls"><div id="description_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span5 control-group">
				<label class="control-label" for="inputDescription">Estimated Hours:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="esthours" name="esthours" title="Estimated Hours" tabindex="9"
					<?php if(isset($activityRecord) && $activityRecord->getEstimated_hours() !="null" ){?>
						value="<?php echo $common->convertSpentTime($activityRecord->getEstimated_hours());}?>" />
				</div>
				<div class="controls"><div id="esthours_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputDueDate">Due Date:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="due_date" name="due_date1" title="Due Date" tabindex="10"
					<?php if(isset($activityRecord) && $activityRecord->getDue_date() !="null" ){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$activityRecord->getDue_date()+$activityRecord->getDue_time()),"Asia/Calcutta","d/m/Y H:i");}?>" />
					<input type="hidden" id="alternate_due_date"
					name="alternate_due_date" title="Due Date"
					<?php if(isset($activityRecord) && $activityRecord->getDue_date() !="null" ){?>
					value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$activityRecord->getDue_date()+$activityRecord->getDue_time()),"Asia/Calcutta","Y-m-d H:i");}?>" />
					<button id="clear" name="clear" class="btn btn-success">Clear DueDate</button>
				</div>
				<div class="controls"><div id="due_date_error" ></div></div>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<button id="ok" name="ok" tabindex="11" class="btn btn-success">Submit</button>
			</div>
		</div>
	</form>
	<script type="text/javascript"> 
	$(document).ready(function(){

		<?php if (isset($selected_company) && $selected_company>0){?>
			$('#company option[value="<?php echo $selected_company;?>"]').attr('selected', true);
		<?php }?>
		
		getProjectByCompany();
		 $('#company').bind('change', function(ev) {
		 getProjectByCompany();
		  });
		  
		$("#due_date").datetimepicker({	
		    changeMonth: true,
		    changeYear: true,
		    showSecond: false,
		    dateFormat: 'dd/mm/yy',
		    timeFormat: 'hh:mm:ss',
		    altField: "#alternate_due_date",
		    altFormat: "yy-mm-dd",
		    altFieldTimeOnly:false,
		    beforeShow: function(input, inst)
		    {
		        inst.dpDiv.css({marginTop: '4em'});
		    }
	    });
		$("#clear")//.button()
		   .click(function( event ) {
	          event.preventDefault();
	          clear();
	      });
		$("#ok")//.button()
	   .click(function( event ) {
          event.preventDefault();
          add();
      });
	  $('#project').bind('change', function(ev) {
		  //$("#project_error").html(" ");
	     var value = $(this).val();		     	     
	     var selectmilestone = document.getElementById('milestone');		     		     
	     selectmilestone.options.length=0;
	     var op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
	    selectmilestone.options.add(op);
	    if(value!=""){
	     $.ajax({	
	    	 type: "POST",	      
	    	 url: "<?php echo $this->url('getmilestone');?>",
	        data: {projectid: value},	
	        dataType:"json",
	       success: function(response)
	         {					   
			    var $i;
			    if(typeof(response.data)!='undefined')
			    {				    	
				    for($i=0;$i<response.data.length;$i++)
					{
					    var op = document.createElement("option");
					    op.value=response.data[$i]['id'];
					    op.text=response.data[$i]['name'];
					    selectmilestone.options.add(op);
				    }				    
			    }				    
		     },
		 	 	error: function(XMLHttpRequest,textStatus){
		 	 		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
			   	},
				        
	     });
	    }
	  });

	  
	  $( "#assigneduser" )
      // don't navigate away from the field on tab when selecting an item
      .bind( "keydown", function( event ) {
          if ( event.keyCode === $.ui.keyCode.TAB &&
                  $( this ).data( "autocomplete" ).menu.active ) {
               event.preventDefault();
          }
      })
      .autocomplete({
          source: function( request, response ) {
              $.getJSON( "<?php echo $this->url('getmultiuser');?>", {
                  term: extractLast( request.term ),
                  company:$("#company").val(),
              }, response );
          },
          search: function() {
              
              var term = extractLast( this.value );
              if ( term.length < 1 ) {
                  return false;
              }
          },
          focus: function() {
              // prevent value inserted on focus
              return false;
          },
          select: function( event, ui ) {
        	  //this.value = '';
              var terms = split( this.value );
              // remove the current input
              terms.pop();
              // add the selected item
              terms.push( ui.item.value );
              // add placeholder to get the comma-and-space at the end
              terms.push( "" );
              this.value = terms.join( "," );
              //$(this).css("height","150px;")
              
              return false;
          }
      });
   });
function split( val ) {
	return val.split( /,\s*/ );
}
function extractLast( term ) {
	return split( term ).pop();
}		   
function getProjectByCompany(){
	var companyId = $("#company").val();
	 var projectDropDown = document.getElementById('project');		     		     
 projectDropDown.options.length=0;
     var op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
	    projectDropDown.options.add(op);
     $.ajax({	
    	 type: "POST",	      
    	 url: "<?php echo $this->url('getProjectByCompany');?>",
        data: {companyid: companyId},	
        dataType:"json",
        success: function(response)
         {
        	 if(response['returnvalue']=="valid"){
            var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    projectDropDown.options.add(op);
			<?php if (isset($selected_project) && $selected_project>0){?>
			$('#project option[value="<?php echo $selected_project;?>"]').attr('selected', true);
			<?php }?>
 		 //   $("#company").removeAttr("disabled");
		    }	
        	 }else{
        	//	 alert("Project not found");
     	    }
         }       
     });

}
function add(){ 
     $.ajax({
         type: "POST",
         <?php if(isset($activityRecord) && $activityRecord->getId()!=null){?>
         url: "<?php echo $this->url('addactivity',array('id'=>$activityRecord->getId()));?>",	
         <?php }else{?>
         url: "<?php echo $this->url('addactivity');?>",
         <?php }?>
         dataType:"json",
         data: $("#frmaddactivity").serialize(),
         beforeSend: function () {
	 			$('#addactivity').mask("Loading...");
	 	 	 },
	     success: function(response)
         {   
              if(response['returnvalue']=="valid"){
            	  
            	  <?php if(isset($activityRecord) && $activityRecord->getId()!=null){?>
            	  alert("Record has been updated Successfully");
            	  <?php }else{?>
            	  alert("Record has been added Successfully");
            	  <?php }?>            	  
             	window.location.href="<?php echo $this->url('activities');?>";
              }                       
              else if(response.returnvalue=="exception"){
            	  alert("This Operation Could not be Completed,Please contact administrator");
                  return false;
             }
             
              else{
                   for(var key in response.data){
                       if(response.data[key]=="null"){
                    	   $("#"+key+"_error").attr("style","color:red");
                           $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
                       }
                       else if(response.data[key]=="invalid"){
                    	   $("#"+key+"_error").attr("style","color:red");
                    	   $("#"+key+"_error").html("Invalid value for "+$("#"+key).attr("title"));  
                       }
                       else if(response.data[key]=="valid"){
                    	   $("#"+key+"_error").html("");  
                       }
                       else if(response.data[key]=="milestonemissmatch"){
                    	   alert("Project and Milestone Miss match");  
                       }
                    }}
           },
        	error: function(XMLHttpRequest,textStatus){
        		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	},
			complete: function(){
		    	setTimeout(function(){		    	
		    		$('#addactivity').unmask();	
		    		//unmaskloading('addProjects');
				},500);
			}	        
      
       });
      return false; 
}
function clear(){
	this.document.getElementById("due_date").value="";
	this.document.getElementById("alternate_due_date").value="";
}
</script>
</div>