<?php 
use Zend\Authentication\AuthenticationService;
$auth=new AuthenticationService();
$currentuser= $auth->getIdentity()->id; 
?>

		 
<button id="btnAddActivity"  style="float:right;" name="btnAddActivity" class="btn btn-success"  aligne="left" style="">Add New Activity</button>

<h2 class="title">Activities</h2>

<hr/>

<form action="" method="post" id="form" name="form" class="form-horizontal">
	<div class="row-fluid">
			<div class="span4 control-group">
				<label class="control-label">Company:</label>
				<div class="controls">
					<select id="company" name="company" title="Company">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($comanys);$i++){?>
						<option value='<?php echo $comanys[$i]['id'];?>'>
							<?php echo ucfirst($comanys[$i]['name']);?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="company_error" class="error"></div></div>
			</div>
			
	<div class="span4 control-group">
		<label class="control-label">Project: </label>
			<div class="controls">
				<select id="project" name="project">
					<option value=""></option>
					<?php if(isset($project) && count($project)>0){
						for($i=0;$i<count($project);$i++){
							?>
					<option value="<?php echo $project[$i]['id'];?>"
					<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project[$i]['id']){echo 'selected="selected"';}?>>
						<?php echo ucwords($project[$i]['name']); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
			
	
	</div>
	
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Assigned User: </label>
			<div class="controls">
				<select id="assigneduser" name="assigneduser">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>"
					<?php if($currentLoggedInUser==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">Assigned By: </label>
			<div class="controls">
				<select id="assignedby" name="assignedby">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>">
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Due Date: </label>
			<div class="controls">
				<input type="text" id="due_date" name="due_date" title="Due Date" value="" />
				<input type="hidden" id="alternate_due_date" name="alternate_due_date" title="Due Date" value="" />
<!--			<div id="due_date_error"></div>-->
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">Activity Date: </label>
			<div class="controls">
				<input type="text" id="activity_date" name="activity_date" title="Activity Date" value="" />
				<input type="hidden" id="alternate_activity_date" name="alternate_activity_date" title="activity Date" value="" />
<!--			<div id="activity_date_error"></div>-->
			</div>
		</div>
	
	</div>
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Subject: </label>
			<div class="controls">
				<input type="text" id="subject" name="subject" title="Subject"/>
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">Activity By: </label>
			<div class="controls">
				<select id="activityloguser" name="activityloguser">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>">
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>

	</div>
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Activity Status: </label>
			<div class="controls">
				<select id="activitystatus" name="activitystatus">
					<option value="">--Select--</option>
					<?php if(isset($activityStatuse) && count($activityStatuse)>0){
						for($i=0;$i<count($activityStatuse);$i++){
							?>
					<option value="<?php echo $activityStatuse[$i]['id'];?>">
						<?php if($activityStatuse[$i]['name']!=null && $activityStatuse[$i]['name']!=""){
							echo ucwords($activityStatuse[$i]['name']);
						} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		
		<div class="span4 control-group">
			<label class="control-label">Filters: </label>
			<div class="controls">
				<select id="savefilterid" name="savefilterid">
					<option value=""></option>
					<?php if(isset($saveFilters) && count($saveFilters)>0){
						for($i=0;$i<count($saveFilters);$i++){
						if($auth->getIdentity()->isadmin==1){?>
					<option value="<?php echo $saveFilters[$i]['id'];?>">
						<?php if($saveFilters[$i]['name']!=null && $saveFilters[$i]['name']!=""){
							echo ucwords($saveFilters[$i]['name']);
							if($saveFilters[$i]['userid']!=$currentuser){
							echo " (".ucwords($saveFilters[$i]['fname']).")";
						}
						} ?>
					</option>
					<?php }elseif ( $saveFilters[$i]['userid']==$currentuser){?>
						<option value="<?php echo $saveFilters[$i]['id'];?>">
						<?php if($saveFilters[$i]['name']!=null && $saveFilters[$i]['name']!=""){
							echo ucwords($saveFilters[$i]['name']);
						} ?>
					</option>
					<?php } }?>
					<?php }?>
				</select>
			</div>
		</div>
		
		
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
		</div>
		
		<div class="span6 control-group">
			<div class="controls">
				<button id="filterActivity" name="filterActivity" class="btn btn-success right-margin">Apply Filter</button>
				<button id="clear" name="clear" class="btn btn-success right-margin">Reset Filters</button>
				<button type="button" id="savefilter" name="savefilter" class="btn btn-success right-margin">Save Filter</button>
				
			</div>
		</div>
	</div>
</form>
<hr />
<div style="height: 100%;" id="gridContainer">
	<table id="list"  class="table table-striped table-bordered dataTable" style="width: 100%;">
	</table>
	<div id="pager"></div>
</div>
<script type="text/javascript">

$(document).ready(function(){
	$('#company').bind('change', function(ev) {
		 getProjectByCompany();
	  });
	
	jQuery("#list").jqGrid({
		url:"<?php echo $this->url('gridactivities'); ?>",
		datatype: "json",
		mtype: 'POST',
		colNames:['Project Name','Subject','Priority','Status','Category','Milestone','Assigned User','Due Date','Estimated Hours',"Spent Hours","Action"],
		colModel :[
		{name:'pname', index:'pname',align:'right', width:35, editable:true},
		{name:'subject',index:'subject', width:85},
		{name:'priority',index:'priority', width:20},
		{name:'status',index:'status', width:30},
		{name:'category', index:'category',align:'right', width:40, editable:true},
		{name:'mname', index:'mname',align:'right', width:25, editable:true},
		{name:'auser', index:'auser', editable:true, width:55,sortable:false},
		{name:'due_date', index:'due_date', width:55,editable: true},
		{name:'esthours', index:'esthours', width:35,editable: true},
		{name:'spenthours', index:'spenthours', width:30,editable: true,sortable:false},
		{name:'action', index:'action', width:55,editable: false,sortable:false}		
		],
		postData: {assignedid:<?php echo $currentLoggedInUser;?>},
	  	rowNum:100,
	    rowList:[100,200,500],
	    navigator:true,
	    pager: '#pager',
	    sortname: 'due_date',
	    viewrecords: true,
	    sortorder: "desc",
	    height:"400px",
	});
	
	   $("#due_date").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       onSelect: function (selectedDate){
	       
	       },
	       altField: "#alternate_due_date",
	       altFormat: "yy-mm-dd",
       });

	   $("#activity_date").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       onSelect: function (selectedDate){
	       
	       },
	       altField: "#alternate_activity_date",
	       altFormat: "yy-mm-dd",
       });
	   $("#clear").click(function( event ) {
		  event.preventDefault();
		  clr();
		});
	   $("#savefilter").click(function( event ) {
		   $("#addActivityFilterModal" ).modal({show:true});
		   var text=$("#savefilterid :selected").text();
		   $("#activityFilterName").val(text.trim());
			});
		$("#addActivityFilter").click(function( event ) {
			saveFilterActivity();
			});	
			
	   	jQuery("#list").setGridWidth($('#gridContainer').width(), true);
		$("#filterActivity").click(function( event ) {
		   event.preventDefault();
		   filterActivity();
		});
		$("#btnAddActivity").click(function( event ) {
		   event.preventDefault();
		   window.location.href = "<?php echo $this->url('addactivity');?>";
		});
		
		 $('#savefilterid').bind('change', function(ev) {
			 getFilter();	
		  });
		
	    });
	    	    
	
	function filterActivity(){
	     var   activitystatus = $("#activitystatus").val();
		 var   userid = $("#assigneduser").val();
		 var   assignedby = $("#assignedby").val();
		 var   projectid = $("#project").val();
		 var   alterdate = $("#due_date").val();
		 var   activitydate = $("#activity_date").val();
		 var   subject = $("#subject").val();
		 var   activityloguser = $("#activityloguser").val();
		 var   duedate = " ";
		 var   altactivitydate = " ";
		 if(alterdate!=""){
		    duedate = $("#alternate_due_date").val();
		 }
		 if(activitydate!=""){
			 altactivitydate = $("#alternate_activity_date").val();
			 }
 		    $("#list").setGridParam({ postData: {activityloguser:activityloguser,subject:subject,activitystatus:activitystatus,assignedby:assignedby,assignedid:userid,projectid:projectid,duedate:duedate,activitydate:altactivitydate} });
		    $("#list").trigger('reloadGrid');
	    }
	   
	    function deleteActivity(id){
	    	if(window.confirm('Are you sure you want to delete this activity?'))
	    	{
	    	 $.ajax({
	    	     type: "POST",
	    	     url: "<?php echo $this->url('deleteactivity');?>",             
	    	     data: {id: id },
	    	     dataType:'json',
	    	     beforeSend: function () {
	    				$('#list').mask("Loading...");
	    		 	 },
	    	     success: function(response)
	    	     {    
	    	        if(response['returnvalue']=="valid"){
	    	        		alert("record deleted");
			    	        $("#list").trigger('reloadGrid');
					}
			        else{
				        if(response.data['user']=="null"){
				        	alert("you are not allowed to delete this activity");
						}
					}
    	        },
		 	 	error: function(XMLHttpRequest,textStatus){
		 	 		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
			   	},
				complete: function(){
			    	setTimeout(function(){		    	
			    		$('#list').unmask();	
					},500);
				}
	    	   });
	    	}
	    }
	    function saveFilterActivity(){

			 var   savefilterid = $("#savefilterid").val();
			 var   activityFilterName=$("#activityFilterName").val();	
		     var   activitystatus = $("#activitystatus").val();
		     var   company = $("#company").val();
			 var   userid = $("#assigneduser").val();
			 var   assignedby = $("#assignedby").val();
			 var   projectid = $("#project").val();
			 var   duedates = $("#due_date").val();

			 var   alterduedate=$("#alternate_due_date").val();	
			 var   activitydate = $("#activity_date").val();
			
		     var   altactivitydates = $("#alternate_activity_date").val();
		   
			 var   subject = $("#subject").val();
			 var   activityloguser = $("#activityloguser").val();
			 
				<?php if(isset($saveFilters) && count($saveFilters)>0){
						for($i=0;$i<count($saveFilters);$i++){
					if($auth->getIdentity()->id==$saveFilters[$i]['userid']){?>
						if(activityFilterName=="<?php echo $saveFilters[$i]['name'];?>"){
								if(savefilterid ==""){
									alert("Duplicate Filter Name");
									$("#activityFilterName").val("");
									return;
									}
							}		
					<?php }?>
							
						
				<?php }}?>
			
		 $.ajax({
		     type: "POST",
		     url: "<?php echo $this->url('savefilteractivity');?>",             
		     data: {'savefilter':savefilterid,'activityFilterName':activityFilterName,'company':company,'activitystatus':activitystatus,'userid':userid,'assignedby':assignedby,'projectid':projectid,'duedates':duedates
			       ,'alterduedate':alterduedate,'activitydate':activitydate,'altactivitydate':altactivitydates,'subject':subject,'activityloguser':activityloguser
			        },
		     dataType:'json',
		    
		     success: function(response)
		     	{    
		    	 if(response['returnvalue']=="valid"){
			    	 if(savefilterid>0){
			    		 alert("Filter successfully updated");
				    	 }else{
				    		 alert("Filter Save successfully");
				    		 }
			    	 $("#addActivityFilterModal" ).modal('hide');
			    	 }
	        },
	 	 	error: function(XMLHttpRequest,textStatus){
	 	 		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	}
	 	 	
		   });
			 
		}
	function getFilter(){
		var savefilterid=$("#savefilterid").val();
		 $.ajax({
    	     type: "POST",
    	     url: "<?php echo $this->url('getfilteractivity');?>",  
    	     data: {'savefilterid':savefilterid},           
    	     dataType:'json',
    	     success: function(response)
    	     {   
                if(response['returnvalue']=="valid"){
                	
					$("#company").val(response.data['company']);
					$("#assigneduser").val(response.data['userid']);
					$("#assignedby").val(response.data['assignedby']);
					$("#activitystatus").val(response.data['activitystatus']);
					$("#project").val(response.data['projectid']);	
					$("#due_date").val(response.data['duedates']);	
					$("#alternate_due_date").val(response.data['alterduedate']);
					
					$("#activity_date").val(response.data['activitydate']);	
					$("#alternate_activity_date").val(response.data['altactivitydate']);
					
					$("#subject").val(response.data['subject']);	
					$("#activityloguser").val(response.data['activityloguser']);	
					filterActivity();
    	        }
		    },
	 	 	error: function(XMLHttpRequest,textStatus){
	 	 		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	}
    	   });
		 
		}
	
	function clr(){
		 document.getElementById("company").value='';	
	   	 document.getElementById("assigneduser").value='';
	   	 document.getElementById("assignedby").value='';
	   	 document.getElementById("project").value='';
	   	 document.getElementById("due_date").value='';
	   	 document.getElementById("activity_date").value='';
	   	 document.getElementById("alternate_activity_date").value='';
	   	 document.getElementById("alternate_due_date").value='';
		 document.getElementById("activityloguser").value='';
		 document.getElementById("activitystatus").value='';
		 document.getElementById("subject").value='';
		 filterActivity();
	    }
    
	function getProjectByCompany(){
		var companyId = $("#company").val();
		 var projectDropDown = document.getElementById('project');		     		     
		 projectDropDown.options.length=0;
	     var op = document.createElement("option");		     
		    op.value="";
		    op.text="--Select--";
		    projectDropDown.options.add(op);
	     $.ajax({	
	    	 type: "POST",	      
	    	 url: "<?php echo $this->url('getProjectByCompany');?>",
	        data: {companyid: companyId},	
	        dataType:"json",
	        success: function(response)
	         {
	        	 if(response['returnvalue']=="valid"){
	            var $i;				    	
			    for($i=0;$i<response.data.length;$i++){
			    var op = document.createElement("option");
			    op.value=response.data[$i]['id'];
			    op.text=response.data[$i]['name'];
			    projectDropDown.options.add(op);
//	 		    $("#company").removeAttr("disabled");
			    }	
	        	 }else{
	        		 alert("Project not found");
	     	    }
	         }       
	     });

	}
	    
	</script>
	
<div id="addActivityFilterModal" title="Add ActivityFilter" class="modal hide fade" data-backdrop="static" 
	data-toggle="modal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right:5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:1px;">Add Activity Filter</h6>
    </div>
    <!-- dialog contents -->
	<div class="modal-body">
		<div id="addActivityFilterBody">
		<div class="span4 control-group">
			<label class="control-label">Filter Name: </label>
			<div class="controls">
				<input type="text" id="activityFilterName" name="activityFilterName" title="activityFilterName" /></div>
		</div>
		</div>
    </div>
    	<div class="modal-footer">
    	<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="closemodeldilog" data-dismiss="modal" >Close</button>
	    <button class="btn btn-success" data-toggle="modal" style="margin-left:33px" 
	    	type="button" value="addActivityFilter" id="addActivityFilter" name="addActivityFilter">Submit</button>
    </div>
		</div>
    
</div>
