<h2 class="title">Activities</h2><hr/>
<form action="" method="post" id="form" name="form" class="form-horizontal">
	<div class="row-fluid">
		<div class="span4 control-group">
		<label class="control-label">Project: </label>
			<div class="controls">
				<select id="project" name="project">
					<option value=""></option>
					<?php if(isset($project) && count($project)>0){
						for($i=0;$i<count($project);$i++){
							?>
					<option value="<?php echo $project[$i]['id'];?>"
					<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project[$i]['id']){echo 'selected="selected"';}?>>
						<?php echo ucwords($project[$i]['name']); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">Assigned User: </label>
			<div class="controls">
				<select id="assigneduser" name="assigneduser">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>"
					<?php if($currentLoggedInUser==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="span3 control-group">
			<label class="control-label">Assigned By: </label>
			<div class="controls">
				<select id="assignedby" name="assignedby">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>">
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Due Date: </label>
			<div class="controls">
				<input type="text" id="due_date" name="due_date" title="Due Date" value="" />
				<input type="hidden" id="alternate_due_date" name="alternate_due_date" title="Due Date" value="" />
<!--			<div id="due_date_error"></div>-->
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">Activity Date: </label>
			<div class="controls">
				<input type="text" id="activity_date" name="activity_date" title="Activity Date" value="" />
				<input type="hidden" id="alternate_activity_date" name="alternate_activity_date" title="activity Date" value="" />
<!--			<div id="activity_date_error"></div>-->
			</div>
		</div>
		<div class="span3 control-group">
			<label class="control-label">Activity Status: </label>
			<div class="controls">
				<select id="activitystatus" name="activitystatus">
					<option value="">--Select--</option>
					<?php if(isset($activityStatuse) && count($activityStatuse)>0){
						for($i=0;$i<count($activityStatuse);$i++){
							?>
					<option value="<?php echo $activityStatuse[$i]['id'];?>">
						<?php if($activityStatuse[$i]['name']!=null && $activityStatuse[$i]['name']!=""){
							echo ucwords($activityStatuse[$i]['name']);
						} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Subject: </label>
			<div class="controls">
				<input type="text" id="subject" name="subject" title="Subject"/>
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">Activity By: </label>
			<div class="controls">
				<select id="activityloguser" name="activityloguser">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>">
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>

	</div>
	<div class="row-fluid">
		<div class="span4 control-group">
			<div class="controls">
				<button id="btnAddActivity" name="btnAddActivity" class="btn btn-success">Add New Activity</button>
			</div>
		</div>
		<div class="span6 control-group">
			<div class="controls">
				<button id="filterActivity" name="filterActivity" class="btn btn-success right-margin">Apply Filter</button>
				<button id="clear" name="clear" class="btn btn-success right-margin">Reset Filters<sup>*</sup></button>
				<span class="help-block">
					<sup>*</sup>Use <i>Reset Filters &nbsp;</i> button to clear the filters, especially for dates.
				</span>
			</div>
		</div>
	</div>
</form>
<hr />
<div style="min-height: 500px;" id="gridContainer">
	<table id="list">
	</table>
	<div id="pager"></div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	jQuery("#list").jqGrid({
		url:"<?php echo $this->url('gridactivities'); ?>",
		datatype: "json",
		mtype: 'POST',
		colNames:['Project Name','Subject','Priority','Status','Category','Milestone','Assigned User','Due Date','Estimated Hours',"Spent Hours","Action"],
		colModel :[
		{name:'pname', index:'pname',align:'right', width:35, editable:true},
		{name:'subject',index:'subject', width:85},
		{name:'priority',index:'priority', width:20},
		{name:'status',index:'status', width:30},
		{name:'category', index:'category',align:'right', width:40, editable:true},
		{name:'mname', index:'mname',align:'right', width:25, editable:true},
		{name:'auser', index:'auser', editable:true, width:55,sortable:false},
		{name:'due_date', index:'due_date', width:55,editable: true},
		{name:'esthours', index:'esthours', width:35,editable: true},
		{name:'spenthours', index:'spenthours', width:30,editable: true,sortable:false},
		{name:'action', index:'action', width:55,editable: false,sortable:false}		
		],
		postData: {assignedid:<?php echo $currentLoggedInUser;?>},
	  	rowNum:20,
	    rowList:[10,20,25],
	    navigator:true,
	    pager: '#pager',
	    sortname: 'due_date',
	    viewrecords: true,
	    sortorder: "desc",
	    height:"400px",
	});
	   $("#due_date").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       onSelect: function (selectedDate){
	       
	       },
	       altField: "#alternate_due_date",
	       altFormat: "yy-mm-dd",
       });

	   $("#activity_date").datepicker({
	       changeMonth: true,
	       changeYear: true,
	       showSecond: false,
	       dateFormat: 'dd/mm/yy',
	       onSelect: function (selectedDate){
	       
	       },
	       altField: "#alternate_activity_date",
	       altFormat: "yy-mm-dd",
       });
	   $("#clear").click(function( event ) {
		  event.preventDefault();
		  clr();
		});	
	   jQuery("#list").setGridWidth($('#gridContainer').width(), true);
		$("#filterActivity").click(function( event ) {
		   event.preventDefault();
		   filterActivity();
		});
		$("#btnAddActivity").click(function( event ) {
		   event.preventDefault();
		   window.location.href = "<?php echo $this->url('addactivity');?>";
		});
	    });
	    	    
	    function filterActivity(){
	     var   activitystatus = $("#activitystatus").val();
		 var   userid = $("#assigneduser").val();
		 var   assignedby = $("#assignedby").val();
		 var   projectid = $("#project").val();
		 var   alterdate = $("#due_date").val();
		 var   activitydate = $("#activity_date").val();
		 var   subject = $("#subject").val();
		 var   activityloguser = $("#activityloguser").val();
		 var   duedate = " ";
		 var   altactivitydate = " ";
		 if(alterdate!=""){
		    duedate = $("#alternate_due_date").val();
		 }
		 if(activitydate!=""){
			 altactivitydate = $("#alternate_activity_date").val();
			 }
 		    $("#list").setGridParam({ postData: {activityloguser:activityloguser,subject:subject,activitystatus:activitystatus,assignedby:assignedby,assignedid:userid,projectid:projectid,duedate:duedate,activitydate:altactivitydate} });
		    $("#list").trigger('reloadGrid');
	    }
	   
	    function deleteActivity(id){
	    	if(window.confirm('Are you sure you want to delete this activity?'))
	    	{
	    	 $.ajax({
	    	     type: "POST",
	    	     url: "<?php echo $this->url('deleteactivity');?>",             
	    	     data: {id: id },
	    	     dataType:'json',
	    	     beforeSend: function () {
	    				$('#list').mask("Loading...");
	    		 	 },
	    	     success: function(response)
	    	     {    
	    	        if(response['returnvalue']=="valid"){
			            	alert("record deleted");
			    	        $("#list").trigger('reloadGrid');
					}
			        else{
				        if(response.data['user']=="null"){
				      	  	alert("you are not allowed to delete this activity");
						}
					}
    	        },
		 	 	error: function(XMLHttpRequest,textStatus){
			    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
			   	},
				complete: function(){
			    	setTimeout(function(){		    	
			    		$('#list').unmask();	
					},500);
				}
	    	   });
	    	}
	    }
	    function clr(){
	   	 document.getElementById("assigneduser").value='';
	   	 document.getElementById("assignedby").value='';
	   	 document.getElementById("project").value='';
	   	 document.getElementById("due_date").value='';
	   	 document.getElementById("activity_date").value='';
	   	 document.getElementById("alternate_activity_date").value='';
	   	 document.getElementById("alternate_due_date").value='';
		 document.getElementById("activityloguser").value='';
		 document.getElementById("activitystatus").value='';

	    }
	</script>

