<?php
use IntranetUtils\Common;
$common=new Common();
use Zend\Authentication\AuthenticationService;
$auth = new AuthenticationService();?>
<div id="report">
<h2 class="title">Send Report</h2>
<hr/>
<form action="" method="post" id="form1" class="form-horizontal">
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">To:<sup style="color:#FF0000">*</sup></label>
			<div class="controls">
				<textarea name="to" id="to" tabindex="1" rows="4" class="input-xlarge"><?php if (isset($preferences) ){ echo $preferences[0]->getTomail();}?></textarea>
			</div>
			<div class="controls"><div id="to_error" class="error"></div></div>
		</div>
		<div class="span5 control-group">
			<label class="control-label">Cc:<sup style="color:#FF0000">*</sup></label>
			<div class="controls">
				<textarea name="cc" id="cc" tabindex="1" rows="4" class="input-xlarge"><?php if (isset($preferences)){ echo $preferences[0]->getCc();};?></textarea>
			</div>
			<div class="controls"><div id="cc_error" class="error"></div></div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">Activity Date:<sup style="color:#FF0000">*</sup></label>
			<div class="controls">
				<input type="text" id="activitydate" title="Activity Date" name="activitydate" value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s"),"Asia/Calcutta","d/m/Y");?>" /> 
				<input type="hidden" id="altactivitydate" name="altactivitydate" value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s"),"Asia/Calcutta","Y-m-d");?>"/>
				<button id="btnActivityDate" name="btnActivityDate" class="btn btn-success">Clear Activity Date</button>
			</div>
			<div class="controls"><div id="activitydate_error"></div></div>
		</div>

        <?php if($auth->getIdentity()->isadmin==1){?>
        <div class="span5 control-group">
			<label class="control-label">User:</label>
			<div class="controls">
				<select id="user" name="user">
					<option value=""></option>
					<?php if(isset($user) && count($user)>0){
						for($i=0;$i<count($user);$i++){
							?>
					<option value="<?php echo $user[$i]->__get('id');?>"
					<?php if(isset($user) && $user[$i]->__get('id')!=null && $user[$i]->__get('id')==$auth->getIdentity()->id){echo 'selected="selected"';}?>>
						<?php echo ucwords($user[$i]->__get('fname')." ".$user[$i]->__get('lname')); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<?php }?>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<?php /*<button id="sendmail" name="sendmail">Send Mail</button>&nbsp;&nbsp;&nbsp;*/?>
			<div class="controls">
				<button id="filtermaildescription" name="filtermaildescription" class="btn btn-success">Get Report</button>
			</div>
		</div>
	</div>
		<!--  <tr>
			<td width="10%" valign="top"><label for="lblsubject" id="lblsubject" class="el"><b>Subject</b></label></td>
			<td width="40%" valign="top">
				<input type="text" name="subject" id="subject"  class="dK nr" spellcheck="false" tabindex="1" dir="ltr" aria-haspopup="true"
					style="overflow-y: hidden; height: 24px;" value="Daily Report <?php //echo date("d/m/Y");?>"/>
			<button id="filtermaildescription" name="filtermaildescription">Get Report</button>
			</td>
			<td colspan="2" width="50%"></td>
		</tr>-->
</form>

<script
	type="text/javascript" src="/js/tinymce/tiny_mce.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$("#filtermaildescription")//.button()
	.click(function( event ) {
	    event.preventDefault();
	    filter();
	});
	$("#btnActivityDate")//.button()
	.click(function( event ) {
	    event.preventDefault();
	    $("#activitydate").val('');
	    $("#altactivitydate").val('');
	});
	<?php
	/* 
	$("#sendmail").button()
	.click(function( event ) {
	    event.preventDefault();
	    sendmail();
	});*/
	?>
	$("#discardmail")//.button()
	.click(function( event ) {
	    event.preventDefault();
	    filter();
	});

	tinyMCE.init({
	 mode : "exact",
     elements : "contenttext",
        theme : "advanced",
        readonly : true,
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        
        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        },
		height : 300
});

$( "#activitydate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altactivitydate",  changeMonth: true,
       changeYear: true,
	      altFormat: "yy-mm-dd" });

$( "#to" )
// don't navigate away from the field on tab when selecting an item
.bind( "keydown", function( event ) {
    if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).data( "autocomplete" ).menu.active ) {
         event.preventDefault();
    }
})
.autocomplete({
	minLength:1,
    source: function( request, response ) {
        $.getJSON( "<?php echo $this->url('getmultiuser');?>", {
            term: extractLast( request.term )
        }, response );
    },
    search: function() {
        
        var term = extractLast( this.value );
        if ( term.length < 1 ) {
            return false;
        }
    },
    focus: function() {
        // prevent value inserted on focus
        return false;
    },
    select: function( event, ui ) {
        var terms = split( this.value );
        // remove the current input
        terms.pop();
        // add the selected item
        terms.push( ui.item.value );
        // add placeholder to get the comma-and-space at the end
        terms.push( "" );
        this.value = terms.join( "," );
        //$(this).css("height","150px;")
        
        return false;
    }
});

$( "#cc")
//don't navigate away from the field on tab when selecting an item
.bind( "keydown", function( event ) {
 if ( event.keyCode === $.ui.keyCode.TAB &&
         $( this ).data( "autocomplete" ).menu.active ) {
      event.preventDefault();
 }
})
.autocomplete({
 minLength:1,
 source: function( request, response ) {
     $.getJSON( "<?php echo $this->url('getmultiuser');?>", {
         term: extractLast( request.term )
     }, response );
 },
 search: function() {
     
     var term = extractLast( this.value );
     if ( term.length < 1 ) {
         return false;
     }
 },
 focus: function() {
     // prevent value inserted on focus
     return false;
 },
 select: function( event, ui ) {
     var terms = split( this.value );
     // remove the current input
     terms.pop();
     // add the selected item
     terms.push( ui.item.value );
     // add placeholder to get the comma-and-space at the end
     terms.push( "" );
     this.value = terms.join( "," );
     //$(this).css("height","150px;")
     
     return false;
 }
});
filter();
});
function split( val ) {
	return val.split( /,\s*/ );
}
function extractLast( term ) {
	return split( term ).pop();
}
function filter(){
	var activity = $('#activitydate').val();
	var altactivity= $('#altactivitydate').val();
  	var userid= $('#user').val();
    $.ajax({
        type: "POST",
        url: "<?php echo $this->url('sendmail');?>",
        dataType:"json",
        data:{"activitydate" : altactivity,"flag":"getreport","userid":userid},
        success: function(response){
        	var ed = tinyMCE.get('contenttext');            
	        	if(response['returnvalue']=="valid"){
	        		ed.setContent(response['html']);
		            $("#contenttext_error").html("");
		            //document.getElementById("contenthtml").value= response['html'];
	        	}
	        	else if(response.returnvalue=="exception"){
	                   alert("This Operation Could not be Completed,Please contact administrator");
	                   return false;
	            }
	        	else{
	                   for(var key in response.data){
		                   if(key=="contenttext"){
		                	   ed.setContent('');
		                   }
	                       if(response.data[key]=="null"){
	                    	   $("#"+key+"_error").attr("style","color:red");
	                           $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
	                       }
	                       else if(response.data[key]=="invalid"){
	                    	   $("#"+key+"_error").attr("style","color:red");
	                    	   $("#"+key+"_error").html("Invalid value for "+$("#"+key).attr("title"));  
	                       }
	                    }
	                  
	            }
        	},
	 	 	error: function(XMLHttpRequest,textStatus){
		    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	},
	    });
	}
	<?php /*
function sendmail(){
	var to = $("#to").val();
	var cc = $("#cc").val();
	var subject = $("#subject").val();
	var selecteddate = $('#activitydate').val();
	var content = tinyMCE.get('contenttext').getContent();
	var userid= $('#user').val();
	 $.ajax({
	        type: "POST",
	        url: "<?php echo $this->url('sendmail');?>",
	        dataType:"json",
	        data:{"userid":userid,"to" : to,"cc" : cc,"content" : content,"flag":"sendmail","selecteddate":selecteddate},
	        beforeSend: function () {
	 			$('#reportData').mask("Loading...");
	 	 	 },
	        success: function(response){
	              if(response['returnvalue']=="valid"){
	            	  alert("report has been sent successfully");
	            	  window.location.reload();
	              }                       
	              else if(response.returnvalue=="exception"){
	                   alert("This Operation Could not be Completed,Please contact administrator");
	                   return false;
	              }
	             
	              else{
	                   for(var key in response.data){
	                       if(response.data[key]=="null"){
	                           $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
	                       }
	                       else if(response.data[key]=="invalid"){
	                    	   $("#"+key+"_error").html("Invalid value for "+$("#"+key).attr("title"));  
	                       }
	                    }}
	           },
		 	 	error: function(XMLHttpRequest,textStatus){
			    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
			   	},
				complete: function(){
			    	setTimeout(function(){		    	
			    		$('#reportData').unmask();	
			    		//unmaskloading('addProjects');
					},500);
				}
	 });
		
}
*/
	?>
</script>
<div id="reportData">
<form method="post" action="sendmail">
	<div id="contenttext_error" class="error"></div>
	<textarea name="contenttext" id="contenttext" style="width: 100%" cols="10" rows="100" title="Content"></textarea>
	<!-- <textarea name="contenthtml" id="contenthtml" style="width: 100%" cols="10" title="Content"></textarea> -->
	</form>
</div>
</div>




