<?php // print_r($response); exit;
use IntranetUtils\Common;
$common=new Common();
?>

<div id="record">
<h2 class="title">View Activity</h2>
	<hr/>
<table class="table table-striped table-condensed">
	<tr>
		<td style="width:15%;"><b>Project:</b></td>
		<td>
			<label id="project" name="project" title="project"><?php if(isset($project)){echo $project[0]['name'];}?></label>
			<input type="hidden" id="projectid" name="projectid"
				value="<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null){echo $activityRecord->getProject_id();}?>" />			
		</td>
	</tr>
	<tr>
		<td><b>Subject:</b></td>
		<td>
			<label id="subject" name="subject" title="subject">
				<?php if(isset($activityRecord) && $activityRecord->getSubject()!=null){echo $activityRecord->getSubject();}?>
			</label>
		</td>
	</tr>
	<tr>
		<td><b>Category:</b></td>
		<td><label id="category" name="category" title="category">
				<?php if(isset($category)){echo $category[0]['name'];}?>
			</label>
			<input type="hidden" id="categoryid" name="categoryid"
				value="<?php if(isset($category)){ echo $category[0]['id']; }?>" />
		</td>
	</tr>
	<tr>
		<td><b>Status:</b></td>
		<td><label id="status" name="status" title="status">
				<?php if(isset($status)){echo $status[0]['name'];}?>
			</label>
		</td>
	</tr>
	<tr>
		<td><b>Priority:</b></td>
		<td><label id="priority" name="priority" title="priority">
				<?php if(isset($activityRecord) && $activityRecord->getPriority_id()!=null){echo $activityRecord->getPriority_id();}?>
			</label>
		</td>
	</tr>
	<tr>
		<td><b>Assigned User:</b></td>
		<td><label id="user" name="user" title="user">
				<?php if(isset($assigneeName) && $assigneeName!=""){echo $assigneeName;}?>
			</label>
		</td>
	</tr>
	<tr>
		<td><b>Description:</b></td>
		<td><label id="description" name="description" title="Description"><?php if(isset($activityRecord) && $activityRecord->getDescription()!=null){
					echo nl2br($activityRecord->getDescription());
				}?></label>
		</td>
	</tr>
	<tr>
		<td><b>Due Date:</b></td>
		<td><?php
		$dueDateInInt='';
		$dueDateInStr='';
		if(isset($activityRecord) && $activityRecord->getDue_Date()!=null){
			if(isset($activityRecord) && $activityRecord->getDue_Time()>0){
				$dueDateInInt=$activityRecord->getDue_Date()+$activityRecord->getDue_Time();
			}
			else{
				$dueDateInInt=$activityRecord->getDue_Date();
			}
			$dueDateInStr=date("Y-m-d H:i:s",$dueDateInInt);
		}
		?> <label id="due_date" name="due_date" title="Due Date">
				<?php if($dueDateInStr!=""){echo $common->ConvertGMTToLocalTimezone($dueDateInStr,"Asia/Calcutta");}?>
			</label>
			<input type="hidden" id="alternate_due_date"
			name="alternate_due_date" title="Due Date"
			value="<?php if($dueDateInStr!=""){echo $common->ConvertGMTToLocalTimezone($dueDateInStr,"Asia/Calcutta","Y-m-d H:i:s");}?>" />
			<div id="due_date_error"></div>
		</td>
	</tr>
	<tr>
		<td><b>Estimated Hours:</b></td>
		<td><label id="esthours" name="esthours" title="esthours"><?php if(isset($esthours)){echo $esthours;}?></label>			
		</td>	
	</tr>
	<tr>
		<td><b>Total Spent Time:</b></td>
		<td><label id="spenttime" name="spenttime" title="spenttime"><?php if(isset($totalTime)){echo $totalTime;}?></label>
			<input type="hidden" id="activityid" name="activityid"
			value="<?php if(isset($activityRecord) && $activityRecord->getId()!=null){echo $activityRecord->getId();}?>" />			
		</td>	
	</tr>
</table>

</div>

<div id="addactivitylogModal" class="modal hide fade" data-backdrop="static" data-toggle="modal" 
	tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right: 5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:2px;">Activity Log</h6>
    </div>
	<!-- dialog contents -->
	<div class="modal-body">
		<div id="addactivitylog" name="addactivitylog" title="ActivityLog"></div>
    </div>
    <div class="modal-footer">
		<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="closemodeldilog" data-dismiss="modal" >Close</button>
		<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="btnaddactivitylog" name="btnaddactivitylog" >Submit</button>
    </div>
    <!-- dialog buttons -->
</div>

<?php if(isset($activityRecord) && $activityRecord->getId()!=null){ ?>
<div style="border:2px solid gray;padding:5px;width:99%;margin-bottom:2em;">
	<ul id="tabs" class="nav nav-pills" data-tabs="pill">
		<li class="active"><a href="#subactivities" data-toggle="pill">Sub Activities</a></li>
		<li><a href="#activitylog" data-toggle="pill">Activity Log</a></li>
	</ul>
	
	<div class="tab-content" style="border-top:2px solid gray;margin-top:-1em;">
		<div id="subactivities" title="Sub Activities" class="tab-pane active" style="margin-top:1em;">
			<form action="" method="post" id="filterrecord" class="form-horizontal">
				<div class="row-fluid">
					<div class="span4 control-group">
						<label class="control-label">User:<sup style="color:#FF0000;">*</sup></label>
						<div class="controls">
							<select id="seluser" name="seluser">
								<option value="">--Select--</option>
								<?php if(isset($userlog) && count($userlog)>0){
									for($i=0;$i<count($userlog);$i++){?>
										<option value="<?php echo $userlog[$i]->__get('id');?>"
										<?php if($currentLoggedInUser==$userlog[$i]->__get('id')){echo 'selected="selected"';}?>>
											<?php if($userlog[$i]->__get('lname')!=null && $userlog[$i]->__get('lname')!=""){
												echo ucwords($userlog[$i]->__get('fname')." ".$userlog[$i]->__get('lname'));
											}else{ echo ucwords($userlog[$i]->__get('fname'));
										} ?>
										</option>
									<?php }?>
								<?php }?>
							</select>
						</div>
					</div>
					<div class="span4 control-group">
						<label class="control-label">Activity Date:</label>
						<div class="controls">
							<input type="text" id="actdate" name="actdate" value="">
							<input type="hidden" id="alternate_adate" name="alternate_adate" value="">
						</div>
					</div>
					<div class="span4 control-group">
						<div class="controls">
							<button class="btn btn-success" id="searchlog" name="searchlog">Apply Filter</button>
							<button class="btn btn-success" id="clear" name="clear">Clear Filter</button>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span4 control-group">
						<label class="control-label">Total Spent Hours:</label>
						<div class="controls">
							<input type="text" id="totalspenttime" name="totalspenttime" size="1" readonly="readonly" value="" />
						</div>
					</div>
					<div class="span4 control-group">
						<div class="controls">
							<button class="btn btn-success" id="addnew" name="addnew">Add Spent Time</button>
						</div>
					</div>
				</div>
			</form>
			<div style="min-height: 470px;" id="gridContainer">
				<table id="list" width="100%">
				</table>
				<div id="pager"></div>
	
			</div>
		</div>
		<div id="activitylog" title="ActivityLog" class="tab-pane" 
			style="overflow:auto; max-height:300px;margin-bottom:1.250em;margin-top:1em;">
			<table class="table table-striped" width="1115px" cellpadding="3">
				<tr>
					<th width="800px">Description</th>
					<th>Activity By</th>
					<th>Created Date</th>
				</tr>
				<?php foreach($this->getacthistory as $acthistory) {?>
				<tr>
					<td><?php echo $acthistory['description'];?></td>
					<td><?php echo $acthistory['name'];?></td>
					<td><?php echo $acthistory['cdate'];?></td>
				</tr>
				<?php }?>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$( "#tabs" ).tab();
	jQuery("#list").jqGrid({
		url:"<?php echo $this->url('gridactivitylog',array('activityid' => $activityRecord->getId())); ?>",
		datatype: "json",
		mtype: 'POST',
		colNames:['id','User Name','Description','Category Name','Created DateTime','Activity Date','Time spent','Action'],
		colModel :[
		{name:'id', index:'id',hidden:true},		
		{name:'username', index:'username',align:'right', editable:true},
		{name:'description', index:'description', editable:true,sortable:false},
		{name:'category', index:'category', editable:true},
		{name:'created_datetime', index:'created_datetime', editable:true},
		{name:'activity_date', index:'activity_date', editable:true},
		{name:'seconds_spent', index:'seconds_spent', editable:true},
		{name:'action', index:'action',editable: false}
		],
		postData: {seluser:<?php echo $currentLoggedInUser;?>},
	    rowNum:20,
	    rowList:[10,20,25],
	    navigator:true,
	    pager: '#pager',
	    sortname: 'activity_date',
	    viewrecords: true,
	    sortorder: "desc",
	    height:"400px",
	    loadComplete:function(response){
		    $("#totalspenttime").val(response.totalspenttime);
	    },
	});
 //$( "#addactivitylog" ).dialog({ autoOpen:false, width:450,});
 
 resizegrid("gridContainer","list"); 
 jQuery("#list").setGridWidth($('#gridContainer').width()-10, true);
 $("#actdate").datepicker({	
     changeMonth: true,
     changeYear: true,     
     dateFormat: 'dd/mm/yy',     
     onSelect: function (selectedDate){
     
     },
     altField: "#alternate_adate",
     altFormat: "yy-mm-dd",     
     });
 $("#searchlog")//.button()
 .click(function( event ) {
  event.preventDefault();
  filterActivitylog();
});
 $("#clear")//.button()
 .click(function( event ) {
  event.preventDefault();
  clr();
});
 $("#addnew")//.button()
 .click(function( event ) {
  event.preventDefault();
//  filterActivitylog();
 	addactivitylog('');
 });
 
});
function addactivitylog(id){
	 $( "#addactivitylogModal" ).modal({show:true});
	  $.ajax({
	       type: "POST",
	       url: "<?php echo $this->url('addactivitylog'); ?>",             
	       data: {flag: "view", id: id,activityid:<?php echo $activityRecord->getId();?>,projectid:<?php echo $activityRecord->getProject_id(); ?>},
	      
	       success: function(response)
	       {   
	          $("#addactivitylog").html(response);
	          $("#list").trigger("reloadGrid");
	       },
		 	error: function(XMLHttpRequest,textStatus){
		 		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	},
	     });
}
 function filterActivitylog(){
	 var   userid = $("#seluser").val();
	 var   altdate = $("#alternate_adate").val();
	 
		    $("#list").setGridParam({ postData: {seluser:userid,alternate_adate:altdate} });
	    $("#list").trigger('reloadGrid');
    }
 function clr(){
	 document.getElementById("seluser").value='';
	 document.getElementById("actdate").value='';
	 document.getElementById("alternate_adate").value='';
	    				}
 function deleteactivitylog(id){
	 if(window.confirm('Are you sure you want to delete this project?'))
		{	 
	 $.ajax({ 
	     type: "POST",
	     url: "<?php echo $this->url('deleteactivitylog'); ?>",             
	     data: {id: id },
	     dataType:"json",
	     beforeSend: function () {
				$('#list').mask("Loading...");
		 	 },
	     success: function(response)
	     {   	    		
	    	              	 
	    	 if(response['returnvalue']=="valid"){
	    		 alert("record deleted");
	       	  $("#list").trigger('reloadGrid');	        	         
	      }   else{
		        if(response.data['user']=="null"){
		        	alert("you are not allowed to delete this activity");
				}
			}
        
	     },
	     error: function(XMLHttpRequest,textStatus){
	    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
	   	},
		complete: function(){
	    	setTimeout(function(){		    	
	    		$('#list').unmask();	
	    		//unmaskloading('addProjects');
			},500);
		}
	   });
		}
 }	 		
</script>
<?php }?>