<?php
use IntranetUtils\Common;
$common=new Common();
?>
<div id="addasset">
	<h2 class="title">
		<?php if(isset($assetRecord) && $assetRecord->getAssetId()!=null){ 
			echo "Edit ";
		}else{echo "Add ";
		}?>
		Asset
	</h2>
	<hr />
	<form action="" method="post" id="frmaddasset" class="form-horizontal">
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputName">Name:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="name" name="name" tabindex="1" title="Name" <?php if(isset($assetRecord) && $assetRecord->getAssetName()!=null){echo 'value="'.$assetRecord->getAssetName().'"';}?> />
				</div>
				<div class="controls"><div id="name_error"></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputMake">Make:</label>
				<div class="controls">
					<input type="text" id="make" name="make" tabindex="2" title="Make" <?php if(isset($assetRecord) && $assetRecord->getAssetMake()!=null){echo 'value="'.$assetRecord->getAssetMake().'"';}?> />
				</div>
				<div class="controls"><div id="make_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputModel">Model:</label>
				<div class="controls">
					<input type="text" id="model" name="model" tabindex="3" title="Model" <?php if(isset($assetRecord) && $assetRecord->getAssetModel()!=null){echo 'value="'.$assetRecord->getAssetModel().'"';}?> />
				</div>
				<div class="controls"><div id="model_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputSerialNumber">Serial Number:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="serialnumber" name="serialnumber" tabindex="4" title="Serial Number" <?php if(isset($assetRecord) && $assetRecord->getSerialNumber()!=null){echo 'value="'.$assetRecord->getSerialNumber().'"';}?> />
				</div>
				<div class="controls"><div id="serialnumber_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputCode">Code:</label>
				<div class="controls">
					<input type="text" id="code" name="code" tabindex="5" title="Code" <?php if(isset($assetRecord) && $assetRecord->getAssetCode()!=null){echo 'value="'.$assetRecord->getAssetCode().'"';}?> />
				</div>
				<div class="controls"><div id="code_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputManufactureDate">Manufacture Date:</label>
				<div class="controls">
					<input type="text" id="manufacturedate" name="manufacturedate" title="Manufacture Date" tabindex="6" <?php if(isset($assetRecord) && $assetRecord->getManufactureDate() !="null" && $assetRecord->getManufactureDate() !=""){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getManufactureDate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="alternate_manufacturedate" name="alternate_manufacturedate" title="Manufacture Date" <?php if(isset($assetRecord) && $assetRecord->getManufactureDate() !="null" ){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getManufactureDate()),"Asia/Calcutta","Y-m-d");}?>" />
					<button id="clearmanufacturedate" name="clearmanufacturedate" class="btn btn-success">Clear</button>
				</div>
				<div class="controls"><div id="manufacturedate_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputPurchaseDate">Purchase Date:</label>
				<div class="controls">
					<input type="text" id="purchasedate" name="purchasedate" title="Purchase Date" tabindex="7" <?php if(isset($assetRecord) && $assetRecord->getPurchaseDate() !="null" && $assetRecord->getPurchaseDate() !=""){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getPurchaseDate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="alternate_purchasedate" name="alternate_purchasedate" title="Purchase Date" <?php if(isset($assetRecord) && $assetRecord->getPurchaseDate() !="null" ){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getPurchaseDate()),"Asia/Calcutta","Y-m-d");}?>" />
					<button id="clearpurchasedate" name="clearpurchasedate" class="btn btn-success">Clear</button>	
				</div>
				<div class="controls"><div id="purchasedate_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputWarrantyExpiryDate">Warranty Expiry Date:</label>
				<div class="controls">
					<input type="text" id="warrantyexpirydate" name="warrantyexpirydate" title="Warranty Expiry Date" tabindex="8" <?php if(isset($assetRecord) && $assetRecord->getWarrantyExpiryDate() !="null" && $assetRecord->getWarrantyExpiryDate() !=""){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getWarrantyExpiryDate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="alternate_warrantyexpirydate" name="alternate_warrantyexpirydate" title="Warranty Expiry Date" <?php if(isset($assetRecord) && $assetRecord->getWarrantyExpiryDate() !="null" ){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getWarrantyExpiryDate()),"Asia/Calcutta","Y-m-d");}?>" />
					<button id="clearwarrantyexpirydate" name="clearwarrantyexpirydate" class="btn btn-success">Clear</button>
				</div>
				<div class="controls"><div id="warrantyexpirydate_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputScrapDate">Scrap Date:</label>
				<div class="controls">
					<input type="text" id="scrapdate" name="scrapdate" title="Scrap Date" tabindex="9" <?php if(isset($assetRecord) && $assetRecord->getScrapDate() !="null" && $assetRecord->getScrapDate() !=""){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getScrapDate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="alternate_scrapdate" name="alternate_scrapdate" title="Scrap Date" <?php if(isset($assetRecord) && $assetRecord->getScrapDate() !="null" ){?> value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$assetRecord->getScrapDate()),"Asia/Calcutta","Y-m-d");}?>" />
					<button id="clearscrapdate" name="clearscrapdate" class="btn btn-success">Clear</button>
				</div>
				<div class="controls"><div id="scrapdate_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputPurchasePrice">Purchase Price:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="purchaseprice"  onkeyup='allnumeric();' name="purchaseprice" tabindex="10" title="Purchase Price" <?php if(isset($assetRecord) ){echo 'value="'.$assetRecord->getPurchasePrice().'"';}?> />
				</div>
				<div class="controls"><div id="purchaseprice_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputCurrentUser">Current User:</label>
				<div class="controls">
					<select id="currentuser" name="currentuser" title="Current User" tabindex="11">
						<option value="">--Select--</option>
						<?php if(isset($currentUser) && count($currentUser)>0){
							foreach($currentUser as $key=>$value){?>
								<option value="<?php echo $key;?>"
								<?php if(isset($assetRecord) && $assetRecord->getCurrentUserId()!=null && $assetRecord->getCurrentUserId()==$key){echo 'selected="selected"';}?>>
									<?php echo $value;?>
								</option>
							<?php }
						}?>
					</select>
				</div>
				<div class="controls"><div id="currentuser_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputIsAlive">Is Alive:</label>
				<div class="controls">
					<select id="isalive" name="isalive" title="Is Alive" tabindex="12">
						<option value="0" <?php if(isset($assetRecord) && $assetRecord->getIsAlive()!=null && $assetRecord->getIsAlive()==0){ echo 'selected="selected"';}?> >
						No</option>
						<option value="1" <?php if(isset($assetRecord) && $assetRecord->getIsAlive()!=null && $assetRecord->getIsAlive()==1){ echo 'selected="selected"';}?> >
						Yes</option>
					</select>
				</div>
				<div class="controls"><div id="isalive_error"></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputIsPrimary">Is Primary:</label>
				<div class="controls">
					<select id="isprimary" name="isprimary" title="Is Primary" tabindex="13">
						<option value="0" <?php if(isset($assetRecord) && $assetRecord->getIsPrimary()!=null && $assetRecord->getIsPrimary()==0){ echo 'selected="selected"';}?> >
						No</option>
						<option value="1" <?php if(isset($assetRecord) && $assetRecord->getIsPrimary()!=null && $assetRecord->getIsPrimary()==1){ echo 'selected="selected"';}?> >
						Yes</option>
					</select>
				</div>
				<div class="controls"><div id="isprimary_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputPrimaryAsset">Primary Asset:</label>
				<div class="controls">
					<select id="primaryasset" name="primaryasset" title="Primary Asset" tabindex="14" >
					<option value="">-</option>
						<?php if(isset($primaryAssets) && count($primaryAssets)>0){
							foreach($primaryAssets as $key=>$value){?>
						<option value="<?php echo $key;?>" <?php if(isset($assetRecord) && $assetRecord->getPrimaryAssetId()!=null && $assetRecord->getPrimaryAssetId()==$key){echo 'selected="selected"';}?>>
							<?php echo ucwords($value); ?>
						</option>
						<?php }?>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="primaryasset_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputCompany">Company:</label>
				<div class="controls">
					<select id="company" name="company" title="Company" tabindex="15">
						<?php if(isset($company) && count($company)>0){
							foreach($company as $key=>$value){?>
						<option value="<?php echo $key;?>" <?php if(isset($assetRecord) && $assetRecord->getCompanyId()!=null && $assetRecord->getCompanyId()==$key){echo 'selected="selected"';}?>>
							<?php echo ucwords($value); ?>
						</option>
						<?php }?>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="company_error" ></div></div>
			</div>
			<div class="span5 control-group">
				<label class="control-label" for="inputAssetLocation">Asset Location<sup style="color:#FF0000;">*</sup>:</label>
				<div class="controls">
					<select id="assetlocation" name="assetlocation" title="Asset Location" tabindex="16">
						<option value="">--Select--</option>
						<?php if(isset($assetLocation) && count($assetLocation)>0){
							foreach($assetLocation as $key=>$value){?>
						<option value="<?php echo $key;?>" <?php if(isset($assetRecord) && $assetRecord->getAssetLocationId()!=null && $assetRecord->getAssetLocationId()==$key){echo 'selected="selected"';}?>>
							<?php echo ucwords($value); ?>
						</option>
						<?php }?>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="assetlocation_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label" for="inputAssetType">Asset Category<sup style="color:#FF0000;">*</sup>:</label>
				<div class="controls">
					<select id="assettype" name="assettype" title="Asset Type" tabindex="17">
					<option value="">--Select--</option>
						<?php if(isset($assetType) && count($assetType)>0){
							foreach($assetType as $key=>$value){?>
						<option value="<?php echo $key;?>" <?php if(isset($assetRecord) && $assetRecord->getAssetTypeId()!=null && $assetRecord->getAssetTypeId()==$key){echo 'selected="selected"';}?>>
							<?php echo ucwords($value); ?>
						</option>
						<?php }?>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="assettype_error" ></div></div>
			</div>
		</div>
		<?php if(isset($assetRecord) && $assetRecord->getIsPrimary()==1 && isset($secondaryAssets) && count($secondaryAssets)>0){?>
		<div class="row-fluid">
			<div class="span10 control-group">
				<label class="control-label" for="inputSecondaryAsset">Secondary Assets:</label>
				<div class="controls">
					<label style="margin-top:5px;">
					<?php foreach($secondaryAssets as $key=>$value){
						echo $value.', ';
					}?>
					</label>
				</div>
				<div class="controls"><div id="secondaryasset_error" ></div></div>
			</div>
		</div>
		<?php }?>
		<div class="control-group">
			<div class="controls">
				<button id="ok" name="ok" tabindex="18" class="btn btn-success">Submit</button>
			</div>
		</div>
	</form>
	<?php if(isset($assetHistory) && sizeof($assetHistory) > 0){?>
	<div id="assetHistory" title="assetHistory" class="tab-pane" style="overflow:auto; max-height:300px;margin-bottom:1.250em;margin-top:1em;">
		<table class="table table-striped" width="1115px" cellpadding="3">
			<tr>
				<th width="800px">Description</th>
				<th>Activity By</th>
				<th>Activity Date</th>
			</tr>
			<?php foreach($assetHistory as $hist) {?>
				<tr>
					<td><?php echo $hist['ah_desc'];?></td>
					<td><?php echo $hist['act_by_name'];?></td>
					<td><?php echo $hist['ah_date'];?></td>
				</tr>
			<?php }?>
		</table>
	</div>
	<?php }?>
	<script type="text/javascript">
		$(document).ready(function(){
			$("#clearmanufacturedate").click(function( event ) {
				event.preventDefault();
				clear('manufacturedate');
				clear('alternate_manufacturedate');
			});
			$("#clearpurchasedate").click(function( event ) {
				event.preventDefault();
				clear('purchasedate');
				clear('alternate_purchasedate');
			});
			$("#clearwarrantyexpirydate").click(function( event ) {
				event.preventDefault();
				clear('warrantyexpirydate');
				clear('alternate_warrantyexpirydate');
			});
			$("#clearscrapdate").click(function( event ) {
				event.preventDefault();
				clear('scrapdate');
				clear('alternate_scrapdate');
			});
			$("#manufacturedate").datetimepicker({	
			    changeMonth: true,
			    changeYear: true,
			    showSecond: false,
			    dateFormat: 'dd/mm/yy',
			    timeFormat: 'hh:mm:ss',
			    altField: "#alternate_manufacturedate",
			    altFormat: "yy-mm-dd",
			    altFieldTimeOnly:false,
			    beforeShow: function(input, inst)
			    {
			        inst.dpDiv.css({marginTop: '4em'});
			    }
			});
			$("#purchasedate").datetimepicker({	
			    changeMonth: true,
			    changeYear: true,
			    showSecond: false,
			    dateFormat: 'dd/mm/yy',
			    timeFormat: 'hh:mm:ss',
			    altField: "#alternate_purchasedate",
			    altFormat: "yy-mm-dd",
			    altFieldTimeOnly:false,
			    beforeShow: function(input, inst)
			    {
			        inst.dpDiv.css({marginTop: '4em'});
			    }
			});
			$("#warrantyexpirydate").datetimepicker({	
			    changeMonth: true,
			    changeYear: true,
			    showSecond: false,
			    dateFormat: 'dd/mm/yy',
			    timeFormat: 'hh:mm:ss',
			    altField: "#alternate_warrantyexpirydate",
			    altFormat: "yy-mm-dd",
			    altFieldTimeOnly:false,
			    beforeShow: function(input, inst)
			    {
			        inst.dpDiv.css({marginTop: '4em'});
			    }
			});
			$("#scrapdate").datetimepicker({	
			    changeMonth: true,
			    changeYear: true,
			    showSecond: false,
			    dateFormat: 'dd/mm/yy',
			    timeFormat: 'hh:mm:ss',
			    altField: "#alternate_scrapdate",
			    altFormat: "yy-mm-dd",
			    altFieldTimeOnly:false,
			    beforeShow: function(input, inst)
			    {
			        inst.dpDiv.css({marginTop: '4em'});
			    }
			});

			$("#ok").click(function( event ) {
	          event.preventDefault();
	          add();
	      });
			if($("#isprimary").val() == 1){
				$("#primaryasset").prop("disabled",true);
				 $("#primaryasset")[0].selectedIndex = 0;
			}
			$("#isprimary").change(function(event){
				if($("#isprimary").val() == 1){
					$("#primaryasset").prop("disabled",true);
					$("#primaryasset")[0].selectedIndex = 0;
				}
				if($("#isprimary").val() == 0){
					$("#primaryasset").prop("disabled",false);
				}
			});
		});
		
		function clear(dataType){
			dataType = '#'+dataType;
			$(dataType).val('');
		}
		function add(){
		     $.ajax({
		         type: "POST",
		         <?php if(isset($assetRecord) && $assetRecord->getAssetId()!=null){?>
		         url: "<?php echo $this->url('addasset',array('id'=>$assetRecord->getAssetId()));?>",	
		         <?php }else{?>
		         url: "<?php echo $this->url('addasset');?>",
		         <?php }?>
		         dataType:"json",
		         data: $("#frmaddasset").serialize(),
		         beforeSend: function () {
			 			$('#addasset').mask("Loading...");
			 	 	 },
			     success: function(response)
		         {   
		              if(response['returnvalue']=="valid"){
		            	  <?php if(isset($assetRecord) && $assetRecord->getAssetId()!=null){?>
		            	  alert("Record has been updated Successfully");
		            	  <?php }else{?>
		            	  alert("Record has been added Successfully");
		            	  <?php }?>            	  
		             	window.location.href="<?php echo $this->url('asset');?>";
		              }                       
		              else if(response.returnvalue=="exception"){
		            	  alert("This Operation Could not be Completed,Please contact administrator");
		                  return false;
		             }
		             
		              else{
		                   for(var key in response.data){
		                       if(response.data[key]=="null"){
		                    	   $("#"+key+"_error").attr("style","color:red");
		                           $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
		                       }
		                       else if(response.data[key]=="invalid"){
		                    	   $("#"+key+"_error").attr("style","color:red");
		                    	   $("#"+key+"_error").html("Invalid value for "+$("#"+key).attr("title"));  
		                       }
		                       else if(response.data[key]=="valid"){
		                    	   $("#"+key+"_error").html("");  
		                       }
	                       }
                       }
		           },
		        	error: function(XMLHttpRequest,textStatus){
		        		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
				   	},
					complete: function(){
				    	setTimeout(function(){		    	
				    		$('#addasset').unmask();	
				    		//unmaskloading('addProjects');
						},500);
					}	        
		      
		       });
		      return false; 
		}

		function allnumeric()  
		  {		 
			  
			  var val = $('#purchaseprice').val();
			if(isNaN(val)){
				   //$("#purchaseprice_error").attr("style","color:red");
            	 //  $("#purchaseprice_error").html("Insert numeric characters only for "+$("#purchaseprice").attr("title"));
				document.getElementById("purchaseprice").value="";
				alert('Please insert numeric characters only');
				return false;
					
		  	}   
		  }
		
			
	</script>
	
</div>