<h2 class="title">Asset Categories</h2><hr/>
<div class="row-fluid">
	<div class="span4 control-group">
		<div class="controls">
			<button onclick="editAssetCatg('')" id="btnAddCategory" name="btnAddCategory" class="btn btn-success">Add New Asset Category</button>
		</div>
	</div>
</div>
<div style="min-height: 500px;margin:10px 5px;">
	<table class="table table-striped table-bordered span3">
		<thead><tr><th>Existing categories:</th></tr></thead>
		<?php foreach ($catg as $key=>$value){
			echo '<tr><td id="'.$key.'">'.$value.'</td>';
			echo "<td><a href='javascript:void(0);' onclick='editAssetCatg(".$key.")'><i class='icon-edit'></i></a>&nbsp;<a href='javascript:deleteAssetCatg(".$key.')'."'><i class='icon-trash'></i></a></td></tr>";
		}?>
	</table>
</div>
<div id="editAssetCatgModal" class="modal hide fade" data-backdrop="static" data-toggle="modal" 
	tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right: 5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:2px;">Edit Asset Category</h6>
    </div>
	<!-- dialog contents -->
	<div class="modal-body">
		<div id="editCatgName" title="Category Name">
			<label class="span2">Add/New category name: </label>
			<input id="catgName" type="text" value="" />
			<input id="catgId" type="hidden" value="" />
		</div>
    </div>
    <div class="modal-footer">
		<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="closemodeldilog" data-dismiss="modal" >Close</button>
		<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="btnEditCatg" name="btnEditCatg" >Submit</button>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#btnEditCatg").click(function( event ) {
		//event.preventDefault();
		$.ajax({
		    type: "POST",
		    url: "<?php echo $this->url('asset_categories'); ?>",             
		    data: {id: $("#catgId").val(),value:$("#catgName").val()},
		    success: function(response)
		    {
				//console.log(response);
				alert('Asset Category successfully added/updated.');
				window.location.reload();
		    },
		 	error: function(XMLHttpRequest,textStatus){
		 		alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	},
		  });
	});	
});
function editAssetCatg(id){
	if(id > 0){
		var c_id = "#"+id;
		$("#catgName").val($(c_id).text());
		$("#catgId").val(id);
	}
	$( "#editAssetCatgModal" ).modal({show:true});
}
function deleteAssetCatg(del_id){
	if(window.confirm('Are you sure you want to delete this asset category?')){	 
	 	$.ajax({
	     type: "POST",
	     url: "<?php echo $this->url('asset_categories'); ?>",             
	     data: {id: del_id },
	     dataType:"json",
	     success: function(response)
	     {   	    		
	    	if(response['returnvalue']=="valid"){
	    		alert("Asset Category deleted.");
	    	  window.location.reload();
	      	}
	    	else {
	    		alert("Sorry, asset category was not deleted. Please try again later.");
	    	}
	     },
	     error: function(XMLHttpRequest,textStatus){
	    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
	   	},
	   });
	}
}
</script>