<table id="projecttable" class="table table-striped table-bordered">
	<tr class="success">
		<td style="width:10%;text-align:center;">Min Date</td>
		<td style="text-align:center;">Health</td>
		<td style="width:10%;text-align:center;">Max Date</td>
	</tr>
	<?php use IntranetUtils\Common as Misc;
	      $common =new Misc();
	
	
	?>
	<?php foreach($projects as $p){
		echo '<tr><td>'.$common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$p['minDate']), 'Asia/Calcutta',"d/m/Y").'</td>';
		
			echo "<td style='background-color:".$p['color']."';>".ucwords($p['name']).'</td>';
		
	echo	 '<td>'.$common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$p['maxDate']), 'Asia/Calcutta',"d/m/Y").'</td></tr>';
	}?>
</table>