<h2 class="title">Report</h2><hr/>
<form action="" method="post" id="rpt" name="report" class="form-horizontal">
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">Project:</label>
			<div class="controls">
				<select id="project" name="project">
					<option value=""></option>
					<?php if(isset($project) && count($project)>0){
						for($i=0;$i<count($project);$i++){
							?>
					<option value="<?php echo $project[$i]['id'];?>"
					<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null )?>>
						<?php echo ucwords($project[$i]['name']); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="span6 control-group">
			<label class="control-label">User:</label>
			<div class="controls">
				<select id="user" name="user">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>">
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">From Date:<sup style="color:#FF0000;">*</sup></label>
			<div class="controls">
				<input type="text" id="fromdate" title="From Date">
				<input type="hidden"  id="altfromdate" name="altfromdate">
			</div>
			<div class="controls"><div id="fromdate_error" class="error"></div></div>
		</div>
		<div class="span6 control-group">
			<label class="control-label">To Date:<sup style="color:#FF0000;">*</sup></label>
			<div class="controls">
				<input type="text" id="todate" title="To Date">
				<input type="hidden"  id="alttodate" name="alttodate">
			</div>
		</div>
		<div class="controls"><div id="todate_error" class="error"></div></div>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">Category:</label>
			<div class="controls">
				<select id="category" name="category" title="Category" tabindex="4">
					<option value="">--Select--</option>
					<?php if(isset($category) && count($category)>0){
						for($i=0;$i<count($category);$i++){?>
					<option value="<?php echo $category[$i]['id'];?>"
					<?php if(isset($activityRecord) && $activityRecord->getCategory_id()!=null && $activityRecord->getCategory_id()==$category[$i]['id']){echo 'selected="selected"';}?>>
						<?php echo ucwords($category[$i]['name']); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="span6 control-group">
			<label class="control-label">Group By:<sup style="color:#FF0000;">*</sup></label>
			<div class="controls">
				<select id="groupby" name="groupby" title="Groupby">
					<option value="">--Select--</option>
					<option value="1">Project</option>
					<option value="2">Project User</option>
					<option value="3">Project User Date</option>
					<option value="4">Project User Date Description</option>
				</select> 
				<div class="controls"><div id="groupby_error" class="error"></div></div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<div class="controls">
				<button id="clear" class="btn btn-success" name="clear">Clear Filter</button>
				<button id="filterReport" class="btn btn-success" name="filterReport" style="margin-left:10px;">Apply Filter</button>
				<span class="help-block"><sup class="required">*</sup>Please use <i>Clear Filter&nbsp;</i> button to clear the filters, especially for dates.</span>
			</div>
		</div>
		<div class="span6 control-group">
			<div class="controls">
				<button width='100%' id="summaryReport" class="btn btn-success" name="summaryReport">Summary report</button>
			</div>
		</div>
	</div>
	</form>
	<div id="reportphtml">
	</div>
	<script type="text/javascript">
	$(document).ready(function(){
	$( "#fromdate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altfromdate",  changeMonth: true,
	       changeYear: true,
		      altFormat: "yy-mm-dd 00:00:00" });
	$( "#todate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#alttodate",  changeMonth: true,
	       changeYear: true,
		      altFormat: "yy-mm-dd 00:00:00" });

	$("#filterReport")//.button()
	   .click(function( event ) {
		   $("#groupby_error").html("");
		   $("#todate_error").html("");
		   $("#fromdate_error").html("");
	       event.preventDefault();
           ProjectUser();
  });
	$("#summaryReport")//.button()
	   .click(function( event ) {
		   $("#groupby_error").html("");
		   $("#todate_error").html("");
		   $("#fromdate_error").html("");
            event.preventDefault();
            SummaryReport();
});

	$("#clear")//.button()
	   .click(function( event ) {
 event.preventDefault();
 clr();
});

	});

	function ProjectUser(){
		 
    	$.ajax({
	        type: "POST",
	        url: "<?php echo $this->url('reportbyproject');?>",
	        dataType:"json",
	        data:$("#rpt").serialize(),
	        success: function(response){
	        	for(var key in response.data){
                    if(response.data[key]=="null"){
                        $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
                    }
	        	}
	        	 $("#reportphtml").html("");
		        $("#reportphtml").html(response['html']);
		       
	        	},

		    });
		}
	

	function SummaryReport(){
    	$.ajax({
	        type: "POST",
	        url: "<?php echo $this->url('summaryreport');?>",
	        dataType:"json",
	        data:$("#rpt").serialize(),
	        success: function(response){
	        	for(var key in response.data){
                    if(response.data[key]=="null"){
                       
                        $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
                    }
	        	}
	        	  $("#reportphtml").html("");
		        $("#reportphtml").html(response['html']);
		       
	        	},

		    });
		}
	function clr(){
		 document.getElementById("project").value='';
	   	 document.getElementById("user").value='';
	   	 document.getElementById("fromdate").value='';
		 document.getElementById("altfromdate").value='';
		 document.getElementById("todate").value='';
		 document.getElementById("alttodate").value='';
		 document.getElementById("category").value='';
		 document.getElementById("groupby").value='';
	   	
	   	 }
			</script>
