<h1 class="title">Unsubmitted Reports By Month</h1><hr/>
<form action="" method="post" id="form1" name="form1" class="form-horizontal">
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Month:</label>
			<div class="controls">
				<select id="month" name="month">
					<option></option>
					<option value="1" <?php if($month==1){echo "selected=selected"; }?>>January</option>
					<option value="2" <?php if($month==2){echo "selected=selected"; }?>>February</option>
					<option value="3" <?php if($month==3){echo "selected=selected"; }?>>March</option>
					<option value="4" <?php if($month==4){echo "selected=selected"; }?>>April</option>
					<option value="5" <?php if($month==5){echo "selected=selected"; }?>>May</option>
					<option value="6" <?php if($month==6){echo "selected=selected"; }?>>June</option>
					<option value="7" <?php if($month==7){echo "selected=selected"; }?>>July</option>
					<option value="8" <?php if($month==8){echo "selected=selected"; }?>>August</option>
					<option value="9" <?php if($month==9){echo "selected=selected"; }?>>September</option>
					<option value="10" <?php if($month==10){echo "selected=selected"; }?>>October</option>
					<option value="11" <?php if($month==11){echo "selected=selected"; }?>>November</option>
					<option value="12" <?php if($month==12){echo "selected=selected"; }?>>December</option>
				</select>
		</div>
	</div>
	<div class="span4 control-group">
		<label class="control-label">Year:</label>
		<div class="controls">
			<select id="year" name="year">
				<option></option>
				<?php for($y=2011;$y<=date('Y');$y++){?>
				<option value='<?php echo $y?>'
				<?php if($year==$y){echo "selected=selected"; }?>>
					<?php echo $y?>
				</option>
				<?php }?>
			</select>
		</div>
	</div>
	<div class="span4 control-group">
		<label class="control-label">Report Type:</label>
		<div class="controls">
		<select name="byuser" id="byuser" tabindex="3">
		<option value="0" <?php if($reportType == 0){echo "selected";}?>>By Date</option>
		<option value="1" <?php if($reportType == 1){echo "selected";}?>>By User</option>
		<option value="2" <?php if($reportType == 2){echo "selected";}?>>Less Than 8hrs</option>
		</select>
<!--      	<input type="checkbox" name="byuser" id="byuser" title="ByUser" value="1" tabindex="3" checked="checked"
			<?php //if(isset($contact) && $contact['0']['isadmin']==1){echo 'checked="yes"';}?> />-->
		</div>
	</div>
</div>
<div class="row-fluid">
	<div class="span2 control-group">
		<div class="controls">
			<button id="btnsubmit" class="btn btn-success" name="btnsubmit">Submit</button>
		</div>
	</div>
</div>
</form>
	
<?php if(isset($responsebydate) && sizeof($responsebydate) > 0){?>
	<table class="table table-striped table-condensed">
	  <tr class="success">
	    <td style="width:10%;"><b>Date</b></td>
	    <td><b>User Who Not filled up Report</b></td>
	  </tr>
<?php foreach ($responsebydate as $rw){?>
	  <tr>
	    <td><?php echo $rw['date'];?></td>
	    <td> <?php echo $rw['reportNotSendBy'];?></td>
	  </tr>
<?php }?>
	</table>
	<?php }
	elseif(isset($userArrayById) && sizeof($userArrayById) > 0){?>
	<table class="table table-striped table-condensed">
	  <tr class="success">
	    <td style="width:20%;"><b>User Name</b></td>
	    <td><b>
	    	<?php if($reportType == 1){echo "Dates When Report Was Not Filled";}
	    		else{echo 'Dates With Report Of Less Than 8 Hours';}?>
    	</b></td>
	  </tr>
	<?php foreach($userArrayById as $user){?>
		<tr>
			<td><?php echo $user['name'];?></td>
			<td><?php echo $user['dates'];?></td>
		</tr>
	<?php }?>
	</table>
	<?php }?>	
