<?php  
use IntranetUtils\Common; $common=new Common(); 
use Zend\Authentication\AuthenticationService; 
$auth=new AuthenticationService();

?>
<h2 class="title">User Report</h2><hr/>

<form action="post" id="dashboard" class="form-horizontal">
	<div class="row-fluid">
		<div class="span3 control-group">
		    <label class="control-label">Start Date:</label>
		    <div class="controls">
				<input class="input-medium" type="text" id="strdate">
				<input type="hidden" id="altstrdate">
			</div>
		</div>
		<div class="span3 control-group">
		    <label class="control-label">End Date:</label>
		    <div class="controls">
			    <input class="input-medium" type="text" id="enddate">
			    <input type="hidden" id="altenddate">
		    </div>
		</div>
		
		<div class="span4 control-group">
				<label class="control-label">Company:</label>
				<div class="controls">
					<select id="company" name="company" title="Company">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($comanys);$i++){?>
						<option value='<?php echo $comanys[$i]['id'];?>'>
							<?php echo ucfirst($comanys[$i]['name']);?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="company_error" class="error"></div></div>
		</div>
		
		</div>
		<div class="row-fluid">
			
		<div class="span3 control-group">
		    <label class="control-label">Project:</label>
		    <div class="controls">
			    <select class="input-medium" id="project" name="project">
					
				</select>
			</div>
		</div>
			
		<div class="span3 control-group">
		    <label class="control-label">User:</label>
		    <div class="controls">
			    <select class="input-medium" id="user" name="user">
					<option value=""></option>
					<?php if(isset($user) && count($user)>0){ for($i=0;$i<count($user);$i++){ ?>
						<option value="<?php echo $user[$i]->__get('id');?>" <?php if(isset($user) && $user[$i]->__get('id')!=null && $user[$i]->__get('id')==$auth->getIdentity()->id){echo 'selected="selected"';}?>>
							<?php echo ucwords($user[$i]->__get('fname')." ".$user[$i]->__get('lname')); ?></option>
						<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
	
		
		<div class="span2 control-group">
			<div class="controls">
		    	<button id="dashboardreport" class="btn btn-success" name="dashboardreport">Report</button>
	    	</div>
		</div>
	</div>
</form>

<script>
$(document).ready(function(){

	$('#company').bind('change', function(ev) {
		 getProjectByCompany();
		 getUserByCompany();
	  });

	$("#dashboardreport")//.button()
	.click(function( event ) {
	    event.preventDefault();
	barchart();
	piechart();
	});
     $( "#strdate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altstrdate",  changeMonth: true,
	       changeYear: true,
		      altFormat: "yy-mm-dd 00:00:00" });
	$( "#enddate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altenddate",  changeMonth: true,
	       changeYear: true,
		      altFormat: "yy-mm-dd 00:00:00" });
    
});

function barchart(){
	var strdate = $('#altstrdate').val();
	var enddate= $('#altenddate').val();
	var userid= $('#user').val();
	var project_id=$('#project').val();
   $.ajax({
        type: "POST",
        url: "<?php echo $this->url('userreport');?>",
        dataType:"json",
        async: false,
        data:{"strdate" : strdate,"enddate":enddate,"userid":userid,"project_id":project_id},
        success: function(response){
        	//$("#chart1").empty();
    	    var legends = [];
   			var lineData = [];
   			var ticksLabel = [] ;
   			var pesttime = [];
   		 	var userspenttime = [];
   			var useresttime = [];
   			var mydata = response;
   			for(var i in mydata.legend) {
   	   	   	   	legends.push({label : mydata.legend[i]});
   	   	  	}
   			for(var i in mydata.pname) {
	   			ticksLabel.push(mydata.pname[i]);
   				pesttime.push(parseFloat(mydata.projectest[i]));
   				userspenttime.push(parseFloat(mydata.userspenttime[i]));
   				useresttime.push(parseFloat(mydata.userest[i]));
   	   	  	}
   			var title=response['title'];
   	   		var lineOptions = {
					'divTag':'chart1',
					'seriesLabel': legends,
					'ticksLabel' : ticksLabel,
					'xaxisLabel' : 'Projects',
					'yaxisLabel' :  'Hours',
					'legendPlacement' : 'outsideGrid',
					'legendShow' : 'true',
					'yFormatString' : '%.2f',
					'chartTitle' : title,
					};	
			if(userspenttime.length>0 && useresttime.length>0){
				lineData.push(userspenttime);
				lineData.push(useresttime);
				barCharts(lineData,lineOptions);
			}
	   		
        	},
	 	 
	    });
 
 	}

function piechart(){
	var strdate = $('#altstrdate').val();
	var enddate= $('#altenddate').val();
	var userid= $('#user').val();
   $.ajax({
        type: "POST",
        url: "<?php echo $this->url('piechart');?>",
        dataType:"json",
        async: false,
        data:{"strdate" : strdate,"enddate":enddate,"userid":userid},
        success: function(response){
        //	$("#chart1").empty();
        	var dataArray=new Array();
   			for(var i in response.data) {
	   			var tmp=new Array();			   			
	   			tmp.push(response.data[i]['categoryname']);
	   			tmp.push(parseFloat(response.data[i]['userspenttime']));
	   			dataArray.push(tmp);		   				
   	   	  	}
   			var title="Total Time "+response['totalspent'];
   	   		var lineOptions = {
					'divTag':'chart2',
					'dataLabelFormatString' : '%g',
					'chartTitle' : title,
					
					};
	   	   	if(dataArray.length>0){
				pieChart(dataArray,lineOptions);
	   	   	}
			
    		},
	 	 
	    });
 
 	}
function getProjectByCompany(){
	var companyId = $("#company").val();
	 var projectDropDown = document.getElementById('project');		     		     
	 projectDropDown.options.length=0;
     var op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
	    projectDropDown.options.add(op);
     $.ajax({	
    	 type: "POST",	      
    	 url: "<?php echo $this->url('getProjectByCompany');?>",
        data: {companyid: companyId},	
        dataType:"json",
        success: function(response)
         {
        	 if(response['returnvalue']=="valid"){
            var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    projectDropDown.options.add(op);
// 		    $("#company").removeAttr("disabled");
		    }	
        	 }else{
        		 alert("Project not found");
     	    }
         }       
     });

}


function getUserByCompany(){
	 var companyId ="";
	 var userDropDown="";
	 var op="";
		companyId = $("#company").val();
		userDropDown = document.getElementById('user');		     		     
		userDropDown.options.length=0;
    op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
	    userDropDown.options.add(op);
	
	
  $.ajax({	
 	 type: "POST",	      
 	 url: "<?php echo $this->url('getUserByCompany');?>",
     data: {companyid: companyId },	
     dataType:"json",
     success: function(response)
      {
     	 if(response['returnvalue']=="valid"){
           var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");

		    <?php if($auth->getIdentity()->isadmin==1){?>
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    userDropDown.options.add(op);
		    
		    <?php }?>}
	//	    $("#user").removeAttr("disabled");
	  	 }else{
//               bootbox.alert("User not found");
  	    }
      }       
  });

}
 	</script>
<hr/>
<div>
<div id="chart1" style="height:500px;width:500px;float:left "></div>
<div id="chart2" style="height:500px;width:500px;float:right "></div>
</div>
<div style="clear:both;"></div>





