<script type="text/javascript">
	$(document).ready(function(){

		$( "#fromdate" ).datepicker({
		constrainInput: true,  
		dateFormat:"dd/mm/yy",
		altField:"#altfromdate",  
		changeMonth: true,
	    changeYear: true,
		altFormat: "yy-mm-dd 00:00:00",
		showWeek: true,
	    firstDay: 1 
	     });

		 
	$( "#todate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#alttodate",  changeMonth: true,
	       changeYear: true,
		      altFormat: "yy-mm-dd 00:00:00" });

	$("#WeeklyReport")//.button()
	   .click(function( event ) {
		   $("#groupby_error").html("");
		   $("#todate_error").html("");
		   $("#fromdate_error").html("");
	       event.preventDefault();
	       WeeklyReport();
  });
	

	});

	function WeeklyReport(){
    	$.ajax({
	        type: "POST",
	        url: "<?php echo $this->url('weeklyreport');?>",
	        dataType:"json",
	        data:$("#rpt").serialize(),
	        success: function(response){
	        	for(var key in response.data){
                    if(response.data[key]=="null"){
                       
                        $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
                    }
	        	}
	        	  $("#reportphtml").html("");
		        $("#reportphtml").html(response['html']);
		       
	        	},

		    });
		}
			</script>



<h2 class="title">Weekly Summary Report</h2><hr/>
<form action="" method="post" id="rpt" name="report" class="form-horizontal">
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">Project:</label>
			<div class="controls">
				<select id="project" name="project">
					<option value=""></option>
					<?php if(isset($project) && count($project)>0){
						for($i=0;$i<count($project);$i++){
							?>
					<option value="<?php echo $project[$i]['id'];?>"
					<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null )?>>
						<?php echo ucwords($project[$i]['name']); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">User:</label>
			<div class="controls">
				<select id="user" name="user">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>">
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">Milestone:&nbsp;
				<input type="checkbox" name="milestone" id="milestone" title="Milestone" value="1" checked="yes">
			</label>
		</div>	
	</div>
	<?php $timePassed = (date('N')-1)* 24 * 3600; // time since start of week in days
		$startOfWeek = mktime(0,0,0,date('m'),date('d'),date('Y')) - $timePassed;
		$startOfWeekdisplay= date('d/m/Y',$startOfWeek);
		$startOfWeekhidden=date('Y-m-d',$startOfWeek);
		$endOfWeekdisplay =date('d/m/Y', strtotime($startOfWeekhidden. ' + 7 days'));
		$endOfWeekhidden=date('Y-m-d', strtotime($startOfWeekhidden. ' + 7 days'));?>
	
	<div class="row-fluid">
		<div class="span4 control-group">
			<label class="control-label">From Date:<sup style="color:#FF0000;">*</sup></label>
			<div class="controls">
				<input type="text" id="fromdate" title="From Date" value="<?php echo $startOfWeekdisplay;?>">
				<input type="hidden"  id="altfromdate" name="altfromdate" value="<?php echo $startOfWeekhidden;?>">
			</div>
			<div class="controls"><div id="fromdate_error" class="error"></div></div>
		</div>
		<div class="span4 control-group">
			<label class="control-label">To Date:<sup style="color:#FF0000;">*</sup></label>
			<div class="controls">
				<input type="text" id="todate" title="To Date" value="<?php echo $endOfWeekdisplay;?>">
				<input type="hidden"  id="alttodate" name="alttodate" value="<?php echo $endOfWeekhidden;?>">
			</div>
			<div class="controls"><div id="todate_error" class="error"></div></div>
		</div>			
		<div class="span4 control-group">
			<label class="control-label">ByUser:&nbsp;
				<input type="checkbox" name="user_time" id="user_time" title="User with Time" value="1" >
			</label>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span4 control-group">
			<div class="controls">
				<button id="WeeklyReport" class="btn btn-success" name="WeeklyReport">Submit</button>
			</div>
		</div>
	</div>
</form>
	<div id="reportphtml">
	
	</div>
	