<li class="active"><a href="<?php echo $this->url('holiday') ?>"><?php echo $this->translate('Holiday') ?></a></li>
<li><a href="<?php echo $this->url('activitystatuses') ?>"><?php echo $this->translate('Activity Status') ?></a></li>
<li><a href="<?php echo $this->url('activitycategories') ?>"><?php echo $this->translate('Activity Categories') ?></a></li>
<li><a href="<?php echo $this->url('projectstatuses') ?>"><?php echo $this->translate('Project Statuses') ?></a></li>
<li><a href="<?php echo $this->url('projects') ?>"><?php echo $this->translate('Projects') ?></a></li>