<?php
use IntranetUtils\Common;
use Zend\Authentication\AuthenticationService;
$common=new Common();
$auth = new AuthenticationService();
?>
<!-- CSS and JS for table fixed header -->
<link rel="stylesheet" type="text/css" href="/css/table-fixed-header.css" />
<script type="text/javascript" src="/js/table-fixed-header.js"></script>
<script type="text/javascript" src="/js/bootbox.min.js"></script>
<style type="text/css">
#scroller {
	/*width: 1600px;*/
	/*width: 80%;margin-left: 269px;*/
	overflow-x: scroll;
}

#scroller table {
	/* just a quick hack to make the table overflow the containing div
       your method may differ */
	/*width: 1826px;
	overflow-x: scroll;*/
}

#scroller .table.fixedCol {
	width: auto;
	position: absolute;
	/* below styles are specific for borderd Bootstrap tables
       to remove rounded corners on cloned table */
	-webkit-border-top-right-radius: 0px;
	-webkit-border-bottom-right-radius: 0px;
	-moz-border-radius-topright: 0px;
	-moz-border-radius-bottomright: 0px;
	border-top-right-radius: 0px;
	border-bottom-right-radius: 0px;
}

.table.fixedCol th,.table.fixedCol td {
	/* background is set to white to hide underlaying column
       of original table */
	background: white;
}

.odd {
	background-color: #FFFFFF ;
/* 	text-align: center; */
}

.even {
	background-color: #ADD8E6;
/* 	text-align: center; */
}

.abs {
	background-color: red;
}

.holiday {
	background-color: #997272;
}

.Orange {
	background-color: #FFA500;
}

.Yellow {
	background-color: #EEFF86;
}
.green{
	background-color: #2EFE2E ;
/* 	text-align: center; */

}

.row {
    	color: white; /*fallback color*/
/*     background-image: url(black.png); */
    background-size: 100% 50%; /*your percentage is the first one (width), second one (100%) is for height*/
/*     background-repeat: no-repeat; */
    background-color: #2EFE2E;
    font-weight: bold;
}

</style>

<?php 
$loginUserId=$auth->getIdentity()->id;

$totalDayInSelectedMonth = cal_days_in_month(CAL_GREGORIAN,$selectedMonth,$selectedYear);// 31
$dailyReportUser="";
$dailyReportDate="";
$currentYear=date('Y');
$currentMonth=date('m');
$currentDay=date("d");
	
$firstDayOfCurrentWeek=strtotime('this week', time());
$firstDayOfCurrentWeek=date("d",$firstDayOfCurrentWeek);
	
$lastDayOfCurrentWeek=$firstDayOfCurrentWeek+6;
	if($lastDayOfCurrentWeek>$totalDayInSelectedMonth && $selectedMonth==$currentMonth)
	{
		$lastDayOfCurrentWeek=$totalDayInSelectedMonth;
	}
	
	$id=""; if(isset($employeeponse[0]['company_id'])){$id=$employeeponse[0]['company_id'];}
		$companyName='';
		for($c=0;$c<count($viewCompanies);$c++){
			if($id==$viewCompanies[$c]['cid']){
				$companyName=$viewCompanies[$c]['name'];
			}
		 }
?>

<h2 class="title">Attendance Report <?php echo $companyName;?>
 <button id="btnAddResourceAllocation" style="float:right;"  class="btn btn-success" name="btnAddResourceAllocation" style="margin-bottom:1em;">Allocate New Resource</button>  
    <ul class="inline" style="float:right;display:inline;">
	    <li class="abs color-legend">Red- Absent</li>
	    <li class="Orange color-legend">Orange- Spent Hours less than 5</li>
	    <li class="Yellow color-legend">Yellow- Spent Hours between 5 and 7</li>
    </ul>

</h2>
 <hr/>
<form action="" method="post" id="form1" name="form1" class="form-horizontal">
	<div class="row-fluid">
		<div class="span3 control-group">
			<label class="control-label">Month:</label>
			<div class="controls">
				<select class="right-margin" id="month" name="month">
					<option></option>
					<option value="1" <?php if($selectedMonth==1){echo "selected=selected"; }?>>January</option>
					<option value="2" <?php if($selectedMonth==2){echo "selected=selected"; }?>>February</option>
					<option value="3" <?php if($selectedMonth==3){echo "selected=selected"; }?>>March</option>
					<option value="4" <?php if($selectedMonth==4){echo "selected=selected"; }?>>April</option>
					<option value="5" <?php if($selectedMonth==5){echo "selected=selected"; }?>>May</option>
					<option value="6" <?php if($selectedMonth==6){echo "selected=selected"; }?>>June</option>
					<option value="7" <?php if($selectedMonth==7){echo "selected=selected"; }?>>July</option>
					<option value="8" <?php if($selectedMonth==8){echo "selected=selected"; }?>>August</option>
					<option value="9" <?php if($selectedMonth==9){echo "selected=selected"; }?>>September</option>
					<option value="10" <?php if($selectedMonth==10){echo "selected=selected"; }?>>October</option>
					<option value="11" <?php if($selectedMonth==11){echo "selected=selected"; }?>>November</option>
					<option value="12" <?php if($selectedMonth==12){echo "selected=selected"; }?>>December</option>
				</select>
			</div>
		</div>
		<div class="span3 control-group">
			<label class="control-label">Year:</label>
			<div class="controls">
				<select id="year" class="right-margin" name="year">
					<option></option>
					<?php for($y=2011;$y<=date('Y');$y++){?>
					<option value='<?php echo $y?>'
					<?php if($selectedYear==$y){echo "selected=selected"; }?>>
						<?php echo $y?>
					</option>
					<?php }?>
				</select>
			</div>
		</div>
		
	
	<?php if($auth->getIdentity()->isadmin==1){  ?>
		<div class="span3 control-group">
			<label class="control-label">Company:</label>
			<div class="controls">
				<select id="company" class="right-margin" name="company">
					<option value='0'>All</option>
					<?php for ($c=0;$c<count($viewCompanies);$c++){?>		
					<option value='<?php echo $viewCompanies[$c]['cid'];?>'
					<?php  if($viewCompanies[$c]['cid']==$slectedCompany){?> 
					 selected="selected" 
					 <?php }?>'>
						<?php echo $viewCompanies[$c]['name'];?>
					</option>
					<?php }?>
				</select>
			</div>
		</div>
	<?php }?>
	
		<div class="span3 control-group">
			<label class="control-label">
				<button type="submit" value="Submit" id="btnsubmit" class="btn btn-success" name="btnsubmit" style="margin-top:-4px;">Submit</button>
			</label>
		</div>
		
		
	</div>
</form>
<hr />


<div>
	<?php 
	$totalAllocationInSelectedMonth=0;
	$allocationDoneInSelectedMonth=0;
	
	$totalAllocationInWeek=0;
	$allocationDoneInWeek=0;
	$totalResource=0;
	$currentWeekDayCount=0;
	
	$cIndex=0;
	?>
	
			
			<div style="display: inline;">
			<table class="table table-bordered ">
			<thead>
			<th>Allocation </th>
			<th>Till Month</th>
			
			<th id="tillWeek" style="display: block;">Till Week </th>
			</thead>
			<tr>
			<td >Allocated</td>
			<td id="allocationDoneInSelectedMonth"></td>
			<td id="allocationDoneInWeek" style="display: block;"></td>
			</tr>
			<tr>
			<td>Potential Hours<span id="totalResource"></span></td>
			<td id="totalAllocationInSelectedMonth"></td>
			<td id="totalAllocationInWeek" style="display: block;"></td>
			</tr>
			<tr>
			<td>Free Resources</td>
			<td id="freeResourceInSelectedMonth"></td>
			<td id="freeResourceInWeek" style="display: block;"></td>
			</tr>
			</table>
			</div>
<div id="scroller">

<table 	class="table table-fixed-header table-bordered table-condensed">
			
	<thead class="header" bgcolor="#909090" >
				<th style="height: 56px; background-color:#909090;"><font color="#FFFFFF">Name</font></th>
				<th bgcolor="#909090"><font color="#FFFFFF">Time</font></th>
				
				<?php for($i=1;$i<=$totalDayInSelectedMonth;$i++)
				{
					$date = "$i-$selectedMonth-$selectedYear";
					$dayName = date('D', strtotime($date));
				?>
				<th bgcolor="#909090"><font color="#FFFFFF">
					<?php if($i<=9){ echo "0".$i."<br/>".$dayName ; }else{ echo $i."<br/>".$dayName ;}?>
					</font></th>
				
				<?php }?>
				<th><font color="#FFFFFF">Total</font></th>
				<th><font color="#FFFFFF">Late</font></th>
	</thead>
				

<?php foreach ($response as $company){?>
	<tbody>
<?php 		 foreach($company['user'] as $employee){ 
				if($employee['needallocation']==1){
					$totalResource++;
				}
	
		 	$totalHolidayInSelectedMonth=0;
		 	$leavesInSelectedMonths=0;
		 	$presentDays=0;
		 	$lateCountInSelectedMonth=0;
		 	$avglateInSelectedMonth=0;
		 	$todayDayLate=0;
		 	$colorIt=true;?>
						 	
						 	
				<tr>
					<td>
							<a href=<?php $employeeHomePageLink="/".$employee['user_id']; echo $employeeHomePageLink; ?>> 
							 	<?php echo $employee['user_name']; ?>
							</a></td>
					<td><?php echo 'In' ?></td>
							
					<?php
							
					$workingDayInSelectedMonth = 0; //the number of days or halfdays, an employee has come to office
			
   for($i=1;$i<=$totalDayInSelectedMonth;$i++){
             		 	
						$formatedMonthDay=sprintf('%02d', $i);
						$date = "$i-$selectedMonth-$selectedYear";
						$dayName = date('D', strtotime($date));
						$yesterday=0;
						$tomorrow=0;
						
						//Leave Calculation
						if($employee[$formatedMonthDay]['intime']=="" && $employee[$formatedMonthDay]['outtime']=="" && $i<=$totalDayInSelectedMonth)
						{
							//condition is true :  day is not Holiday & not sunday for selected month
							if(!in_array($i,$holiday) && $dayName!="Sun" && $i<=$totalDayInSelectedMonth){
								//current month
								if($currentMonth==$selectedMonth && $i<=$currentDay){
									$leavesInSelectedMonths++;
								}//for past months
								elseif ($selectedYear<=$currentYear && $currentMonth > $selectedMonth){
									$leavesInSelectedMonths++;
								}
							}
				           elseif ($dayName="Sun" || in_array($i,$holiday) && $i<=$totalDayInSelectedMonth)
				           {
					           	$yesterday=$i;
					           	$tomorrow=$i;
					            
					            if ($dayName="Sun"){
					            	$yesterday=$i-1;
					            	$tomorrow=$i+1;
					            }
					           	while (in_array($yesterday,$holiday)){
					           		$yesterday=$yesterday-1;
					           }
					          
					           while (in_array($tomorrow,$holiday)){
					           	$tomorrow=$tomorrow+1;
					           }
					           $yesterday=sprintf('%02d', $yesterday);
					           $tomorrow=sprintf('%02d', $tomorrow);
					           
					           if ($yesterday<$tomorrow && $tomorrow<$totalDayInSelectedMonth && $yesterday!=0)
					           {
						           if($employee[$yesterday]['intime']=="" && $employee[$yesterday]['outtime']=="" && $employee[$tomorrow]['intime']=="" && $employee[$tomorrow]['outtime']==""  && $i<=$totalDayInSelectedMonth && !in_array($i,$holiday))
						           {
									//current month
						           	if($currentMonth==$selectedMonth && $i<=$currentDay){
							           		$leavesInSelectedMonths++;
							           	}//past month
							           	else if($selectedYear<=$currentYear && $currentMonth > $selectedMonth){
							           		$leavesInSelectedMonths++;
							           	}
						         
						           }
					           }
				        }
							if (in_array($i,$holiday) || $dayName=="Sun" && $i<=$totalDayInSelectedMonth){
								$totalHolidayInSelectedMonth++;
							}
						}
// 						leaves counte End	
						
// 						Present days in Selected Month
						$spentTime=$employee[$formatedMonthDay]['spenttime'];
						$spent = explode(":",$spentTime);
						$inTime = explode(':', $employee[$formatedMonthDay]['intime']);
						$outTime = explode(':', $employee[$formatedMonthDay]['outtime']);
						
						if($employee[$formatedMonthDay]['intime'] != "" && $employee[$formatedMonthDay]['outtime'] != "" 
							&& $i <= $totalDayInSelectedMonth && $spent[0] >= 5 && $inTime[0] < 11 && $outTime[0] > 16){
							$presentDays++;
						}
						elseif($employee[$formatedMonthDay]['intime'] != "" && $employee[$formatedMonthDay]['outtime'] != "" 
							&& $i <= $totalDayInSelectedMonth  ){
							$presentDays += 0.5;
						}
						
						
// 						Avg Late count
						if ($employee[$formatedMonthDay]['intime']!=""){
							$workingDayInSelectedMonth++;
							if($employee[$formatedMonthDay]['login']>=$employee[$formatedMonthDay]['cdate']+$employee['login_slot'] && $employee[$formatedMonthDay]['login']<=$employee[$formatedMonthDay]['cdate']+$employee['login_slot']+900){
								//if person comes between 9:10 and 9:00 than it will be considered earlt,so minus that much seconds in his avglate
								$avglateInSelectedMonth-=($employee[$formatedMonthDay]['cdate']+$employee['login_slot']+900)-$employee[$formatedMonthDay]['login'];
							}
							else if($employee[$formatedMonthDay]['login']>$employee[$formatedMonthDay]['cdate']+$employee['login_slot']+900 && $employee[$formatedMonthDay]['login'] <$employee[$formatedMonthDay]['cdate']+$employee['login_slot']+10800){
								//if person comes after 9:10 it will be considered late,so add that much seconds in his avglate 
								$avglateInSelectedMonth+=$employee[$formatedMonthDay]['login']-($employee[$formatedMonthDay]['cdate']+$employee['login_slot']+900);
								$lateCountInSelectedMonth++;
							}
							else{
								//if person comes before nine,calculate its average from 9,means if x comes at 8:45 than also he will be considered on 9 for in hours average calculations,
								//and he will get benifit of 10 mins(9:10) thus in seconds 10*60=600
								$avglateInSelectedMonth-=900;
							}
						}
						
// 						if ($res[$formatedMonthDay]['intime']!=""){
								
// 							if($res[$formatedMonthDay]['login']>=$res[$formatedMonthDay]['cdate']+$res['login_slot'] && $res[$formatedMonthDay]['login']<=$res[$formatedMonthDay]['cdate']+$res['login_slot']+900){
// 								//if person comes between 9:10 and 9:00 than it will be considered earlt,so minus that much seconds in his avglate
// 								$avglateInSelectedMonth-=($res[$formatedMonthDay]['cdate']+$res['login_slot']+900)-$res[$formatedMonthDay]['login'];
// 								$workingDayInSelectedMonth++;
// 							}
// 							else if($res[$formatedMonthDay]['login']>$res[$formatedMonthDay]['cdate']+$res['login_slot']+900){
// 								//if person comes after 9:10 it will be considered late,so add that much seconds in his avglate
// 								$avglateInSelectedMonth+=$res[$formatedMonthDay]['login']-($res[$formatedMonthDay]['cdate']+$res['login_slot']+900);
// 								$lateCountInSelectedMonth++;
// 								$workingDayInSelectedMonth++;
// 							}
// 							else{
// 								//if person comes before nine,calculate its average from 9,means if x comes at 8:45 than also he will be considered on 9 for in hours average calculations,
// 								//and he will get benifit of 10 mins(9:10) thus in seconds 10*60=600
// 								$avglateInSelectedMonth-=900;
// 								$workingDayInSelectedMonth++;
// 							}
// 						}
// 						avg late count End

// 						today late count
						$todayDateInYMD=date("Y-m-d");
						$todayStr=strtotime($todayDateInYMD)-19800;
						if ($employee[$formatedMonthDay]['intime']!="" && $employee[$formatedMonthDay]['cdate'] ==$todayStr){
							$todayDayLate=$employee[$formatedMonthDay]['login']-($employee[$formatedMonthDay]['cdate']+$employee['login_slot']+900);
				
							if ($todayDayLate>0){
								$todayDayLate=$common->convertSpentTime($todayDayLate);
							}else {
							    $todayDayLate="00:00";
							}
						}
						
						
						
					//$spent=explode(":",$spentTime);
					if($spent[0]<5 && $spentTime !=""){
						$spent="Orange";
					};
					if($spent[0]<7 && $spent[0]>=5 && $spentTime !=""){
						$spent="Yellow";
					}
				$loginBy=$employee[$formatedMonthDay]['loginByResult'];
				$allocatedPercentag="0%";
				?>
					
				
				<td  

				<?php if(($currentMonth==$selectedMonth && $currentDay<$i && $currentYear==$selectedYear) || ($currentYear==$selectedYear && $currentMonth<$selectedMonth) || ($currentYear<$selectedYear)){ ?>rowspan="3"<?php }?>  
				
				class=" 
				<?php if($colorIt){?>odd<?php }else{ echo "even";}?> <?php if(!is_array($spent)){echo $spent;}?> <?php echo $dayName;?> <?php if(in_array($i,$holiday)){ echo "holiday"; }?>  <?php if($employee[$formatedMonthDay]['intime']=="" && $employee[$formatedMonthDay]['outtime']=="" && $i<=$totalDayInSelectedMonth){ echo "abs";}?>"
			 
			  <?php if((!in_array($i,$holiday) && $dayName!="Sun")  && $employee['needallocation']==1 ){ 
			  	
			  	//current month allocation 
			  	if($currentMonth==$selectedMonth && $currentYear==$selectedYear && $currentDay<=$i){
			  		if($firstDayOfCurrentWeek<=$i && $i<=$lastDayOfCurrentWeek ){
			  			$currentWeekDayCount ++;
			  			$totalAllocationInWeek +=8;
			  			
			  			if (isset($employee[$formatedMonthDay]['totalallocated']) && $employee[$formatedMonthDay]['totalallocated']>0 ) {
			  				$allocationDoneInWeek +=$employee[$formatedMonthDay]['totalallocated'];
			  			}
			  			
			  		}
			  	}
			  	
			  		if (isset($employee[$formatedMonthDay]['totalallocated']) && $employee[$formatedMonthDay]['totalallocated']>0 ) {
			  			$allocationDoneInSelectedMonth +=$employee[$formatedMonthDay]['totalallocated'];
			  		}
			  		
			  		$totalAllocationInSelectedMonth +=8;
			  		
			  	if (isset($employee[$formatedMonthDay]['totalallocated']) && $employee[$formatedMonthDay]['totalallocated']>0 ) 
			  	{
			  		$allocatedPercentag=($employee[$formatedMonthDay]['totalallocated']/8)*100;
			  		if($allocatedPercentag>100){
			  			$allocatedPercentag=100;
			  		}
			  		$allocatedPercentag=$allocatedPercentag."%";
			  	}		
	if(($currentMonth==$selectedMonth && $currentDay>=$i && $currentYear==$selectedYear)  || ($currentYear>=$selectedYear && $currentMonth>$selectedMonth) || ($currentYear>$selectedYear)  ){ }else{?>
	
				style="background: linear-gradient(to top, rgb(0, 255, 0) <?php echo $allocatedPercentag; ?>, rgb(255, 255, 255) <?php echo "$allocatedPercentag"; ?>) repeat scroll 0% 0% transparent;" 			
				
	
	<?php }?>
	<?php  }?>			
								title="<?php  echo $dayName."-".date('d/m/Y',strtotime($date));
								if(isset($employee[$formatedMonthDay]['duration']) && count($employee[$formatedMonthDay]['duration'])>0){
										foreach ($employee[$formatedMonthDay]['duration'] as $arow){
                                          echo " | ".ucfirst($arow['project_name']).":".$arow['duration'];
									}}?>">
								
									
								<?php echo $employee[$formatedMonthDay]['intime'];
								 if((int)$allocatedPercentag>1 && $employee[$formatedMonthDay]['intime']==""){
									$allocatedPercentag="0%";
									}
								if($loginBy!=$employee['user_id'] && $employee[$formatedMonthDay]['intime']!=""){?><sup>*</sup><?php }?>
							
							</td>
							
	<?php } ?>
<!-- 	for loop end -->
	
							<td title="Leave"><?php echo $leavesInSelectedMonths;?></td>
							<td title="Late By. Today"><?php echo $todayDayLate;?></td>

	</tr>		 	
						 	
<!-- second rows of out time						 	 -->
<tr>
							<td height="20px;">&nbsp;</td>
							<td><?php echo "Out";?></td>
<?php 
 for($i=1;$i<=$totalDayInSelectedMonth;$i++){
             		 	
						$formatedMonthDay=sprintf('%02d', $i);
						$date = "$i-$selectedMonth-$selectedYear";
						$dayName = date('D', strtotime($date));

						$spentTime=$employee[$formatedMonthDay]['spenttime'];
						$spent=explode(":",$spentTime);
						if($spent[0]<5 && $spentTime !=""){
						$spent="Orange";
						};
						if($spent[0]<7 && $spent[0]>=5 && $spentTime !=""){
						$spent="Yellow";
						}
						$logoutBy=$employee[$formatedMonthDay]['logoutByResult'];
						?>
						<?php
						
						if(($currentMonth==$selectedMonth && $currentDay>=$i && $currentYear==$selectedYear)  || ($currentYear>=$selectedYear && $currentMonth>$selectedMonth) || ($currentYear>$selectedYear)  ){ ?>
							<td  
								class="<?php if($colorIt){?>odd<?php }else{ echo "even";}?> <?php if(!is_array($spent)){echo $spent;}?> <?php echo $dayName;?> <?php if(in_array($i,$holiday)){ echo "holiday"; }?> <?php if($employee[$formatedMonthDay]['intime']=="" && $employee[$formatedMonthDay]['outtime']=="" && $i<=$totalDayInSelectedMonth){ echo "abs";}?>"
								title="<?php echo $dayName."-".date('d/m/Y',strtotime($date));?>"><?php echo $employee[$formatedMonthDay]['outtime'];if($logoutBy!=$employee['user_id'] && $employee[$formatedMonthDay]['outtime']!="" ){?><sup>*</sup>
								<?php }?>
							</td>
							<?php } ?>
<?php }?>
<!-- out time for loop end							 -->
							<td title="Present Day/Working Day"><?php echo $presentDays;echo "/";echo $totalDayInSelectedMonth-$totalHolidayInSelectedMonth;
							?>
							</td>
							<td title="Avg.Late">
							<?php if ($workingDayInSelectedMonth>0){
								$avglateInSelectedMonth=$avglateInSelectedMonth/$workingDayInSelectedMonth;
							}
							if ($avglateInSelectedMonth>900){
								$avglateInSelectedMonth=$common->convertSpentTime($avglateInSelectedMonth);
								echo "<span class='abs'>".$avglateInSelectedMonth."</span>";
							}
							elseif ($avglateInSelectedMonth>0 && $avglateInSelectedMonth<=900){
								$avglateInSelectedMonth=$common->convertSpentTime($avglateInSelectedMonth);
								echo "<span class='Yellow'>".$avglateInSelectedMonth."</span>";
							}
							else { $avglateInSelectedMonth="00:00";
								echo "<span style='background-color: #3ADF00;'>".$avglateInSelectedMonth."</span>";
							} ?>
		</td>
	</tr>
	
	
<!-- third tr					 	 -->
<tr>
		<td style="border-bottom: 1px solid #000000;" height="21px;">&nbsp;</td>
		<td style="border-bottom: 1px solid #000000;"><?php echo "<b>Total</b>";?>
		</td>
		<?php 
		for($i=1;$i<=$totalDayInSelectedMonth;$i++){
		$formatedMonthDay=sprintf('%02d', $i);
		$date = $i."-".$selectedMonth."-".$selectedYear;
		$datedmy=$i."/".$selectedMonth."/".$selectedYear;
		$dateymd=$selectedYear."-".$selectedMonth."-".$i;
		$userName=$employee['user_name'];

		if($auth->getIdentity()->isadmin==1){ 
		$onClick="dailyReport('".$employee['user_id']."','".$dateymd."','".$datedmy."','".$userName."')";		
		}else {
			if($loginUserId==$employee['user_id']){
			$onClick="dailyReport('".$loginUserId."','".$dateymd."','".$datedmy."','".$userName."')";
			}else{
				$onClick="";
				}
			}
		$dayName = date('D', strtotime($date));
		$spentTime=$employee[$formatedMonthDay]['spenttime'];
		$spent=explode(":",$spentTime);
		if($spent[0]<5 && $spentTime !=""){
		$spent="Orange";
		};
		if($spent[0]<7 && $spent[0]>=5 && $spentTime !=""){
		$spent="Yellow";
		}
		
		if(is_array($spent)){
				}?>
				
<?php 	if(($currentMonth==$selectedMonth && $currentDay>=$i && $currentYear==$selectedYear)  || ($currentYear>=$selectedYear && $currentMonth>$selectedMonth) || ($currentYear>$selectedYear)  ){ ?>


		<td class="<?php if($colorIt){?>odd<?php }else{ echo "even"; }?>  <?php if(!is_array($spent)){echo $spent;}?> <?php echo $dayName;?> <?php if(in_array($i,$holiday)){ echo "holiday"; }?> <?php if($employee[$formatedMonthDay]['intime']=="" && $employee[$formatedMonthDay]['outtime']=="" && $i<=$totalDayInSelectedMonth){ echo "abs";}?>"
				<?php if ((!in_array($i,$holiday) && $dayName!="Sun") &&  isset($employee[$formatedMonthDay]['totalallocated']) && $employee[$formatedMonthDay]['totalallocated']>0 ){ 
			if(isset($employee[$formatedMonthDay]['totalallocated']) && $employee[$formatedMonthDay]['totalallocated']>0 ) {
					$totalAllocationPercentag=($employee[$formatedMonthDay]['totalallocated']/8)*100;
					if($totalAllocationPercentag>100){
					$totalAllocationPercentag=100;
					}
					$totalAllocationPercentag=$totalAllocationPercentag."%";
			}?>
				style="background: linear-gradient(to top, rgb(0, 255, 0) <?php echo $totalAllocationPercentag; ?>, rgb(255, 255, 255) <?php echo "$totalAllocationPercentag"; ?>) repeat scroll 0% 0% transparent;" 			
				<?php $totalAllocationPercentag="0%"; }?>					
				title="<?php echo $dayName."-".date('d/m/Y',strtotime($date));
								if(isset($employee[$formatedMonthDay]['duration']) && count($employee[$formatedMonthDay]['duration'])>0){
										foreach ($employee[$formatedMonthDay]['duration'] as $arow){
                                          echo " | ".ucfirst($arow['project_name']).":".$arow['duration'];
									}}?>">
									
								<span style="cursor:pointer;" onclick="<?php echo $onClick;?>"> <?php echo $employee[$formatedMonthDay]['spenttime'];
								if(isset($employee[$formatedMonthDay]['totalallocated']) && $employee[$formatedMonthDay]['totalallocated'] > 8 ){
										echo "*";
									}
								?> </span>

							</td>
							<?php  }}?>
							<td title="Total Working Time"><?php echo $common->convertSpentTime($employee['totalspenttime']); ?>
							</td>
							<td title="Late Count in month"><?php echo $lateCountInSelectedMonth;?></td>
						</tr>
						<?php if($colorIt){
							$colorIt=false;
						}
						else{
		$colorIt=true;
	}?>
									 	
						 
						
				<?php }?>
				</tbody>
				<?php }?>	
				</table>
			</div>
	
	</div>

	
	
<div id="dailyReportModal" class="modal hide fade" tabindex="-1" role="dialog" 
	data-backdrop="static" data-toggle="modal" aria-labelledby="myModalLabel" aria-hidden="true">
	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right: 5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:5px;">Daily Report</h6>
    </div>
	<!-- dialog contents -->
	<div class="modal-body">
			<div id="userDate"  title="UserName and Date"></div>
	    	<div id="dailyReport"  title="DailyReport"></div>
    </div>
    <!-- dialog buttons -->
    <div class="modal-footer">
    	<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			id="closemodeldilog" data-dismiss="modal">Close</button>
    </div>
</div>
	
	
	
	
	
<div id="addResourceAllocationModal" title="Add ResourceAllocation" class="modal hide fade" data-backdrop="static" 
	data-toggle="modal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right:5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:1px;">Enter Resource Allocation Details</h6>
    </div>
    <!-- dialog contents -->
	<div class="modal-body">
		<div id="addResourceAllocation" name="addResourceAllocation" title="Add Resource Allocation">
			<form  id="form" name="form" class="form-horizontal">
			<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Company:</label>
				<div class="controls">
					<select id="allocationCompany" name="allocationCompany" title="Company">
						<option value="">--Select--</option>
							<?php for ($c=0;$c<count($viewCompanies);$c++){?>
					<?php if($auth->getIdentity()->isadmin==1){?>				
					<option value='<?php echo $viewCompanies[$c]['cid'];?>'
					<?php  if($viewCompanies[$c]['cid']==$slectedCompany){?> 
					 selected="selected" 
					 <?php }?>'>
						<?php echo $viewCompanies[$c]['name'];?>
					</option>
					<?php }else{
					if($auth->getIdentity()->company_id==$viewCompanies[$c]['cid']){?>
					<option value='<?php echo $viewCompanies[$c]['cid'];?>'
					<?php  if($viewCompanies[$c]['cid']==$slectedCompany){?> 
					 selected="selected" 
					 <?php }?>'>
						<?php echo $viewCompanies[$c]['name'];?>
					</option>
					<?php }}}?>
					</select>
				</div>
				<div class="controls"><div id="allocationCompany_error" class="error"></div></div>
			</div>
		</div>
				<div class="row-fluid" style="display: inline;">
							<div class="control-group" style="float: left;">
							<label class="control-label" for="inputProject">Project:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
				<div style="float: left;">	
								<select id="allocationProject" name="allocationProject" title="Project" tabindex="1" disabled>
										<option value="">--Select--</option>
										<?php if(isset($project) && count($project)>0){
											for($i=0;$i<count($project);$i++){
												?>
										<option value="<?php echo $project[$i]['id'];?>"
										<?php if(isset($activityRecord) && $activityRecord->getProject_id()!=null && $activityRecord->getProject_id()==$project[$i]['id']){echo 'selected="selected"';}?>  >
											<?php echo ucwords($project[$i]['name']); ?>
										</option>
										<?php }?>
										<?php }?>
								</select>
					</div>			
						<div id="projectallocationAtAddForm" style="float: right; display: none;">
						<table   class="table-bordered" >
						<tr>
						<td>Project Estimate:<span id="projectEstimatedAtAddForm"></span></td>
						
						<td>Allocated: <span id="totalAllocatedAtAddForm"></span></td>
						
						<td>Spent:<span id="totalSpentAtAddForm"></span></td>
						</tr>
				        </table>
						</div>
				</div>
				<div class="controls"><div id="allocationProject_error"></div></div>
				</div>
				</div>
				
				
				<div class="row-fluid">
				<div class="control-group">
						<label class="control-label" for="inputProject">User:<sup style="color:#FF0000;">*</sup></label>
						<div class="controls">
						<div>
								<select id="allocationUserid" name="allocationUser" title="User" class="input-medium" disabled>
										<option value="">--Select--</option>
										<?php if(isset($users) && $users!=null && $users!=""){?>
										<?php if(isset($users) && count($users)>0){
											for($i=0;$i<count($users);$i++){?>
										<?php if($auth->getIdentity()->isadmin==1){?>	
										<option value="<?php echo $users[$i]->__get('id');?>"
										<?php if($currentuser==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
											<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
												echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
											}else{ echo ucwords($users[$i]->__get('fname'));
												} ?>
										</option>
										<?php }else{
											if($auth->getIdentity()->id==$users[$i]->__get('id')){
											?>
											<option value="<?php echo $users[$i]->__get('id');?>"
											<?php if($currentuser==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
												<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
													echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
											}else{ echo ucwords($users[$i]->__get('fname'));
												} ?>
										</option>
										<?php } }}?>
										<?php }?>
										<?php }?>
								</select>
							</div>
							<div id="userallocationAtAddForm" style="float: right;display: none;">
								<table   class="table-bordered">
									<tr>
										<td>Allocated:<span id="userAllocatedAtAddForm"></span></td>
										<td>Spent:<span id="userSpentAtAddForm"></span></td>
									</tr>
						       </table>
						</div>
						</div>
				</div>
				</div>
				
				<div class="row-fluid">
						<div class="control-group">
						<label class="control-label">Duration:<sup style="color:#FF0000;">*</sup> </label>
						<div class="controls">
							<input id="allocationDuration" name="Duration" title="Duration" type="text" value=""/>
						</div>
				<div class="controls small-margin "><div id="duration_error"></div></div>
					</div>
					<div class="control-group">
						<label class="control-label">Per Day Duration: </label>
						<div class="controls">
							<input id="allocationPerDayDuration" name="perDayDuration" title="perDayDuration" type="text" value=""/>
						</div>
				<div class="controls small-margin "><div id="duration_error"></div></div>
					</div>
					
				</div>
				<div class="row-fluid inline" style="display: inline">
						<div class="control-group">
						<label class="control-label">Start Date:<sup style="color:#FF0000;">*</sup> </label>
						<div class="controls">
							<input type="text" id="startdate" name="startdate" title="Date" value="" /> 
							<input type="hidden" id="altstartdate" name="altstartdate" title="Date" value="" />
						</div>
					</div>
					
						<div class="control-group" style="float: left;display: none;">
						<label class="control-label">End Date: </label>
						<div class="controls">
							<input type="text" id="enddate" name="enddate" title="End Date" value="" /> 
							<input type="hidden" id="altenddate" name="altenddate" title="Date" value="" />
						</div>
					</div>
						
				</div>
			</form>
		</div>
    </div>
    <div class="modal-footer">
    	<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="closemodeldilog" data-dismiss="modal" >Close</button>
	    <button class="btn btn-success" data-toggle="modal" style="margin-left:33px" 
	    	type="button" value="Ok" id="ok" name="ok" onclick="addResourceAllocation()">Submit</button>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){ 

	$("#month").bind('change',function(){
		$("#btnsubmit").click();
		});
	$("#year").bind('change',function(){
		$("#btnsubmit").click();
		});
	$("#company").bind('change',function(){
		$("#btnsubmit").click();
		});
	<?php if(($currentMonth!=$selectedMonth && $currentYear==$selectedYear) || ($currentMonth!=$selectedMonth && $currentYear=!$selectedYear)) { ?>
	
	$("#tillWeek").hide();
	$("#totalAllocationInWeek").hide();
	$("#allocationDoneInWeek").hide();
	$("#freeResourceInWeek").hide();
	<?php } ?>
	var totalResource = <?php echo "$totalResource";?>;
	
	$("#totalResource").html("(Resources: "+totalResource+")");
	var totalAllocationInSelectedMonth =<?php echo "$totalAllocationInSelectedMonth";?>;
	
	var allocationDoneInSelectedMonth =<?php echo "$allocationDoneInSelectedMonth";?>;
	var totalAllocationFreeInPer= Math.round(100-((allocationDoneInSelectedMonth/totalAllocationInSelectedMonth)*100))+"%";
	var totalAllocationFreeInHr=totalAllocationInSelectedMonth-allocationDoneInSelectedMonth;
	$("#totalAllocationInSelectedMonth").html(totalAllocationInSelectedMonth);
	
	$("#allocationDoneInSelectedMonth").html(allocationDoneInSelectedMonth);
	$("#freeResourceInSelectedMonth").html(totalAllocationFreeInPer+"( Hr: "+totalAllocationFreeInHr+" )");
	
	var totalAllocationInWeek= <?php echo "$totalAllocationInWeek";?>;
	var allocationDoneInWeek = <?php  echo "$allocationDoneInWeek";?>;
	$("#totalAllocationInWeek").html(totalAllocationInWeek);
	$("#allocationDoneInWeek").html(allocationDoneInWeek);
	var totalAllocationFreeInWeekPer = Math.round(100-((allocationDoneInWeek/totalAllocationInWeek)*100))+"%";
	var totalAllocationFreeInWeekHr= totalAllocationInWeek - allocationDoneInWeek;
	$("#freeResourceInWeek").html(totalAllocationFreeInWeekPer+" (Hr : "+totalAllocationFreeInWeekHr+")");
	
	$("#scroller").css('width',$(document).width()-40);
	$('#scroller table').each(function(){
	    var table = $(this),
	        fixedCol = table.clone(true),
	        fixedWidth = table.find('th').eq(0).width(),
	        tablePos = table.position();
	    
	    // Remove all but the first column from the cloned table
	    fixedCol.find('th').not(':eq(0)').remove();
	    fixedCol.find('tbody tr').each(function(){
	        $(this).find('td').not(':eq(0)').remove();
	    });
	    
	    // Set positioning so that cloned table overlays
	    // first column of original table
	    fixedCol.addClass('fixedCol');
	    fixedCol.css({
	        left: tablePos.left,
	        top: tablePos.top
	    });
	    // Match column width with that of original table
	    fixedCol.find('th,td').css('width',fixedWidth+'px');
	    fixedCol.find('th,td').attr('width',fixedWidth+'px');
	    $('#scroller').append(fixedCol);
	});
	//$('.table-fixed-header').fixedHeader();



	
	 getProjectByCompany('add');
	 getUserByCompany('add');
	 $('#allocationCompany').bind('click', function(ev) {
		 getProjectByCompany('add');
		 getUserByCompany('add');
	  });
// 	 $('#companyFilter').bind('change', function(ev) {
// 		 getProjectByCompany('filter');
// 		 getUserByCompany('filter');
// 	  });

		$("#startdate").datepicker({
		       changeMonth: true,
		       changeYear: true,
		       showSecond: false,
		       minDate: 0 ,
		       dateFormat: 'dd/mm/yy',
		       altField: "#altstartdate",
		       altFormat: "yy-mm-dd",
		    });
			$("#enddate").datepicker({
			       changeMonth: true,
			       changeYear: true,
			       showSecond: false,
			       minDate: 0 ,
			       dateFormat: 'dd/mm/yy',
			       altField: "#altenddate",
			       altFormat: "yy-mm-dd",
			    });

//		 	$("#perDayDuration").timepicker({timeOnly:true,showHour:8});
			$('#allocationProject').bind('change', function(ev) {
				getprojectallocationdetail();
				getuserallocationdetailbyproject();
			});
			$('#allocationUserid').bind('change', function(ev) {
				getuserallocationdetailbyproject();
			});
			$('#allocationDuration').bind('change', function(ev) {
				
				var duration = $("#allocationDuration").val();
				if(8<=duration ){
					$("#allocationPerDayDuration").val('08:00');
					}else {
						$("#allocationPerDayDuration").val(duration);
						}
				var allocated=0;
					allocated = $("#totalAllocatedAtAddForm").val();
				if(allocated ==""){
					allocated=0;
					}
				var projectEstimate= parseInt($("#projectEstimatedAtAddForm").val());
				var allocationRemain= 0;
				if(projectEstimate > allocated)
				allocationRemain = projectEstimate - allocated;

				var extraAllocation =0;
				if(allocated >projectEstimate )
				extraAllocation = allocated - projectEstimate;
				if(duration > allocationRemain &&  allocationRemain>0){
					bootbox.alert("Project remain allocation is "+allocationRemain+"Hr");
//		 			$("#duration").val(allocationRemain);
					}

				if(extraAllocation>0){
					bootbox.alert("Already allocated "+extraAllocation +"hr extra");
					}
			  });
			  
			$('#allocationPerDayDuration').bind('change', function(ev) {
				var duration = $("#allocationDuration").val();
				var perdayDuration=$("#allocationPerDayDuration").val();
				if( perdayDuration > duration || perdayDuration > 24  ){
					if(perdayDuration > 24 ){
						bootbox.alert("Per Day Duration is more than one day duration");
						if(duration > 24)
						$("#allocationPerDayDuration").val("24");

						if(duration <= 24)
							$("#allocationPerDayDuration").val(duration);
						}
					if(perdayDuration > duration ){
							bootbox.alert("Per Day Duration is more than duration");
							$("#allocationPerDayDuration").val(duration);
					}
				
				}
				});
			
			$("#btnAddResourceAllocation").click(function( event ) {
				$("#addResourceAllocationModal" ).modal({show:true});
				clrAddAllocationForm();
			});
	
});


function dailyReport(userid,dateymd,datedmy,userName){

	 $.ajax({
	        type: "POST",
	        url: "<?php echo $this->url('sendmail');?>",
	        dataType:"json",
	        data:{"activitydate" :dateymd,"flag":"getreport","userid":userid},
	        beforeSend: function () {
	 			$('.container-fluid').mask("Loading...");
	 	 	 },
	        success: function(response){
	        		if(response['returnvalue']=="valid"){
	        			$("#dailyReport").html();
	        			$("#dailyReportModal").modal({show:true});
	        			$("#dailyReportModal .modal-header").html("<b>Daily Report of "+userName+" For :"+datedmy+"</b>");
		                $("#dailyReport").html(response['html']);
		                
			    	}
		        	else{

		        		bootbox.alert("No report available of "+userName+" for :"+datedmy);
		                return false;

		            }
		        	
	        	},
		 	 	error: function(XMLHttpRequest,textStatus){
		 	 		bootbox.alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
			   	},
				complete: function(){
			    	setTimeout(function(){		    	
			    		$('.container-fluid').unmask();	
			    	},500);
				}
		    });
}

function addResourceAllocation(){
	var projectid = $("#allocationProject").val();
	var userid = $("#allocationUserid").val();
	var duration = $("#allocationDuration").val();
	var perDayDuration = $("#allocationPerDayDuration").val();
	var startdate = $("#altstartdate").val();
	var enddate = $("#altenddate").val();
	
	
	$.ajax({
		type: "POST",
		url: "<?php echo $this->url('addresourceallocation');?>",	         
		data: {projectid: projectid , userid :userid, duration :duration,perdayduration :perDayDuration ,startdate :startdate,enddate :enddate },
		dataType:'json',
	
		success: function(response)
		{
			if(response['returnvalue']=="valid"){
          	 	$( "#addResourceAllocationModal" ).modal('hide');
         		bootbox.alert("Record has been added Successfully");
         		$("#list").trigger("reloadGrid");
			}
		},
		error: function(XMLHttpRequest,textStatus){
			bootbox.alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		},
	});
	
}
function getProjectByCompany(flag){
	 var companyId ="";
	 var projectDropDown="";
	 var op="";
	if(flag=='add'){
		companyId = $("#allocationCompany").val();
		projectDropDown = document.getElementById('allocationProject');		     		     
		 projectDropDown.options.length=0;
      op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
	    projectDropDown.options.add(op);
	}
	else{
		 companyId = $("#companyFilter").val();
		  projectDropDown = document.getElementById('allocatedproject');		     		     
		 projectDropDown.options.length=0;
	      op = document.createElement("option");		     
		    op.value="";
		    op.text="--Select--";
		    projectDropDown.options.add(op);
		}
    $.ajax({	
   	 type: "POST",	      
   	 url: "<?php echo $this->url('getProjectByCompany');?>",
       data: {companyid: companyId},	
       dataType:"json",
       success: function(response)
        {
       	 if(response['returnvalue']=="valid"){
           var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");
		    
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    projectDropDown.options.add(op);
		    $("#allocationProject").removeAttr("disabled");
		    }	
       	 }else{
//                 alert("Project not found");
    	    }
        }       
    });

}

function getUserByCompany(flag){
	 var companyId ="";
	 var userDropDown="";
	 var op="";
	if(flag=='add'){
		companyId = $("#allocationCompany").val();
		userDropDown = document.getElementById('allocationUserid');		     		     
		userDropDown.options.length=0;
     op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
	    userDropDown.options.add(op);
	}
	else{
		 companyId = $("#companyFilter").val();
		 userDropDown = document.getElementById('allocateduserid');		     		     
		 userDropDown.options.length=0;
	      op = document.createElement("option");		     
		    op.value="";
		    op.text="--Select--";
		    userDropDown.options.add(op);
		}
   $.ajax({	
  	 type: "POST",	      
  	 url: "<?php echo $this->url('getUserByCompany');?>",
      data: {companyid: companyId },	
      dataType:"json",
      success: function(response)
       {
      	 if(response['returnvalue']=="valid"){
            var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");

		    <?php if($auth->getIdentity()->isadmin==1){?>
		    if(response.data[$i]['needallocation']==1){
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    userDropDown.options.add(op);
		    }
		    <?php }else{ ?>
		    
		    	if(<?php echo $auth->getIdentity()->id; ?>==  response.data[$i]['id']){
		    		 if(response.data[$i]['needallocation']==1){
					op.value=response.data[$i]['id'];
				    op.text=response.data[$i]['name'];
				    userDropDown.options.add(op);
		    	}
		    	}
		    	<?php }?>
		    }
		    $("#allocationUserid").removeAttr("disabled");
	  	 }else{
//                bootbox.alert("User not found");
   	    }
       }       
   });

}

function getprojectallocationdetail(){
	var projectId = $("#allocationProject").val();
	 $("#projectEstimatedAtAddForm").html("");
  	 $("#totalAllocatedAtAddForm").html("");
  	 $("#totalSpentAtAddForm").html("");
  	 
  	 $("#projectEstimatedAtAddForm").val("");
  	 $("#totalAllocatedAtAddForm").val("");
  	 $("#totalSpentAtAddForm").val("");
	   $.ajax({	
		   	 type: "POST",	      
		   	 url: "<?php echo $this->url('getprojectallocationdetail');?>",
		       data: {projectid: projectId},	
		       dataType:"json",
		       success: function(response)
		        {  
		       	 if(response['returnvalue']=="valid"){
			       	 $("#projectEstimatedAtAddForm").html(response.estimatedHours);
			       	 $("#totalAllocatedAtAddForm").html(response.allocated);
			       	 $("#totalSpentAtAddForm").html(response.totalSpent);
			       	 
			       	 $("#projectEstimatedAtAddForm").val(response.estimatedHours);
			       	 $("#totalAllocatedAtAddForm").val(response.allocated);
			       	 $("#totalSpentAtAddForm").val(response.totalSpent);
					if(parseInt(response.estimatedHours)>0 || parseInt(response.allocated) > 0 || parseInt(response.totalSpent) > 0){
						document.getElementById("projectallocationAtAddForm").style.display = "block";
						}
			       	 
		       	 }else{
//		                 bootbox.alert("User not found");
		    	    }
		        }       
		    });
	}

function getuserallocationdetailbyproject(){
	var projectId = $("#allocationProject").val();
	var userId= $("#allocationUserid").val();
	   $.ajax({	
		   	 type: "POST",	      
		   	 url: "<?php echo $this->url('getuserallocationdetailbyproject');?>",
		       data: {projectid: projectId,userid:userId},	
		       dataType:"json",
		       success: function(response)
		        {  
		       	 if(response['returnvalue']=="valid"){
		       		if(parseInt(response.allocated)>0){
					       	 $("#userAllocatedAtAddForm").html(response.allocated);
					       	 $("#userAllocatedAtAddForm").val(response.allocated);
		       			}else{
		       				$("#userAllocatedAtAddForm").html("0");
				       	 	$("#userAllocatedAtAddForm").val("0");
			       		}
		       		if(parseInt(response.totalSpent)>0){
					       	 $("#userSpentAtAddForm").html(response.totalSpent);
					       	 $("#userSpentAtAddForm").val(response.totalSpent);
		       		}else{
				       		 $("#userSpentAtAddForm").html("0");
					       	 $("#userSpentAtAddForm").val("0");
			       		}
			       	if(parseInt(response.allocated)>0 || parseInt(response.totalSpent)>0 ){
				     	document.getElementById("userallocationAtAddForm").style.display = "block";
						}
		       	 }else{
//		                 bootbox.alert("User not found");
		    	    }
		        }       
		    });	
}

function clrAddAllocationForm(){
	 $("#projectEstimatedAtAddForm").html("");
  	 $("#totalAllocatedAtAddForm").html("");
  	 $("#totalSpentAtAddForm").html("");
  	 
  	 $("#projectEstimatedAtAddForm").val("");
  	 $("#totalAllocatedAtAddForm").val("");
  	 $("#totalSpentAtAddForm").val("");
	
	 $("#userAllocatedAtAddForm").val("");
  	 $("#userSpentAtAddForm").val("");
  	 $("#userAllocatedAtAddForm").html("");
 	 $("#userSpentAtAddForm").html("");

 	$("#allocationProject").val("");
	$("#allocationUserid").val("");
	$("#allocationDuration").val("");
	$("#allocationPerDayDuration").val("");
	$("#startdate").val();
	$("#altstartdate").val("");
	$("#enddate").val("");
	$("#altenddate").val("");
	document.getElementById("userallocationAtAddForm").style.display = "none";
	document.getElementById("projectallocationAtAddForm").style.display = "none";
}

</script>