<button id="btnAddUser" style="float:right;" class="btn btn-success" name="btnAddUser" style="margin-bottom:1em;">Add New User</button>

<h2 class="title">Users</h2><hr>
<div style="height: 100%;" id="gridContainer">
	<table id="list">
	</table>
	<div id="pager"></div>
<input type="hidden" name="altdate" id="altdate"/>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$("#btnAddUser")//.button()
	.click(function( event ) {
	   event.preventDefault();
	  window.location.href = "<?php echo $this->url('addcontact');?>";
	});
	jQuery("#list").jqGrid({
		url:"<?php echo $this->url('griduser');?>",
		datatype: "json",
		mtype: 'POST',
		colNames:['Name','Designation','Email','Mobile','Dob','EmployeeId','Active','Admin','Action'],
		colModel :[
		{name:'name', index:'name',align:'right', editrules:{required:true}, editable:true},		
		{name:'designation', index:'designation',align:'right', editrules:{required:true}, editable:true},		
		{name:'email', index:'email',align:'right', editrules:{required:true}, editable:true},		
		{name:'mobile', index:'mobile', editable:true},
		{ name:'dob', index:'dob', label: 'Date', width: 80,
		    editable: true, edittype: 'text',
		    editoptions: {
		      size: 10, maxlengh: 10,
		      dataInit: function(element) {
		        $(element).datepicker({dateFormat: 'mm-dd-yy',changeMonth: true,changeYear: true,})
		      }
		    }
		  },		
		{name:'employeeid', index:'employeeid',align:'right', editrules:{required:true}, editable:true},		
		{name:'isactive', index:'isactive', editable:true,edittype:'checkbox', editoptions: { value:"1:0"},formatter: "checkbox",sortable:false},
		{name:'isadmin', index:'isadmin', editable:true,edittype:'checkbox', editoptions: { value:"1:0"},formatter: "checkbox",sortable:false},
		{name:'action', index:'action'},
		],
	  rowNum:100,
	    rowList:[100,200,500],
	    navigator:true,
	    pager: '#pager',
	    sortname: 'name',
	    viewrecords: true,
	    sortorder: "desc",
	    height:"auto",
	    width:"auto"
	    
	});
	   jQuery("#list").jqGrid('navGrid',"#pager",{add:false,edit:false,del:false, search:false, refresh:false},
	           {reloadAfterSubmit:true,url:"<?php echo $this->url('adduser');?>"}, // edit options
	           {reloadAfterSubmit:true,url:"<?php echo $this->url('adduser');?>",closeAfterAdd:true,
		       }, // add options
	           {reloadAfterSubmit:true,url:"<?php echo $this->url('deleteuser');?>"} // del options
	           );
	   jQuery("#list").setGridWidth($('#gridContainer').width(), true);
	});
resizegrid("gridContainer","list");

function deleteUser(id){
	if(window.confirm('Are you sure you want to delete this user?'))
	{
	 $.ajax({
	     type: "POST",
	     url: "<?php echo $this->url('deleteuser');?>",             
	     data: {id: id },
	     dataType:'json',
	     success: function(response)
	     {   
		     $("#list").trigger('reloadGrid');
		             },
 	 	
	   });
	}
}


function filterdata(reporttype) {
	var reporttype=$("#type123").val();
	//console.log(reporttype);return;
	jQuery("#list").jqGrid('setPostDataItem',"reporttype",reporttype);
	jQuery("#list").trigger("reloadGrid"); 
	jQuery("#list").jqGrid('removePostDataItem',"reporttype"); 
}

</script>

</script>

