<?php
use IntranetUtils\Common;
$common=new Common();
use Zend\Authentication\AuthenticationService;
$auth = new AuthenticationService();
$id=$auth->getIdentity()->id;
?>
<div id="addactivity">
<h1 class="title">Profile</h1><hr/>
<!--<form action="" method="post" id="frmeditcontact">-->
		<table id="editcontact" class="table table-striped table-condensed">
			<tr>
				<td style="width:15%;">First Name :</td><td>
				<label name="fname" id="fname" title="First Name"> <?php if(isset($contact) && $contact['0']['fname']!=""){?> <?php echo ucfirst($contact['0']['fname']);}?></label>
				</tr>
			<tr>
				<td>Last Name :</td>
				<td><label name="lname" id="lname" title="Last Name"> <?php if(isset($contact) && $contact['0']['lname']!=""){?> <?php echo ucfirst($contact['0']['lname']);}?></label>
				</td>
			</tr>
			
			<tr>
				<td>Company :</td>
				<td><label id="companyid" name="companyid" title="Company Name" >
					<?php if(isset($contact) && $contact['0']['companyname']!=""){?> <?php echo ucfirst($contact['0']['companyname']);} ?>
					</label>
				</td>
			</tr>
			<tr>
				<td>Employeeid :</td><td>
				<label name="employeeid" id="employeeid" title="employeeid"> <?php if(isset($contact) && $contact['0']['employeeid']!=""){?> <?php echo ucfirst($contact['0']['employeeid']);}else{ echo "Not Generated";}?></label>
					</tr>	
			
			<tr>
				<td>Designation :</td><td>
				<label name="designation" id="designation" title="Designation"> <?php if(isset($contact) && $contact['0']['designation']!=""){?> <?php echo ucfirst($contact['0']['designation']);}else{ echo "Not Define";}?></label>
					</tr>		
		
			<tr>
				<td>Email :</td><td>
				<label name="email" id="email" title="Email"> <?php if(isset($contact) && $contact['0']['email']!=""){?> <?php echo $contact['0']['email'];}?></label>
					</tr>
			<tr>
				<td>Joining Date :</td><td>
				<label name="joiningdate" id="joiningdate" Title="Joining Date"> <?php if(isset($contact) && $contact['0']['joindate']!=""){ ?> <?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$contact['0']['joindate']),"Asia/Calcutta","d/m/Y");}?> </label>
				</td>
			</tr>
			<tr>
				<td>Login Slot :</td>
				<td>
					<label name="loginslot" id="loginslot" Title="Login Slot">
						<?php if(isset($contact) && $contact[0]['login_slot']!=""){ ?> 
							<?php echo $contact[0]['login_slot'];
						}?>
					</label>
				</td>
			</tr>
			
			<tr>
				<td>DOB :</td><td>
					<label name="dob" id="dob" title="DOB"> <?php if(isset($contact) && $contact['0']['dob']!=""){ $dob=$contact['0']['dob'];?> <?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",$dob),"Asia/Calcutta","d/m/Y");}?> </label>
				</td>
			</tr>
			
			<tr>
				<td>Permanent address :</td>
				<td><div id="paddress" title="Parmanent Address"><?php if(isset($contact) && $contact['0']['paddress']!=""){echo $contact['0']['paddress'];}?></div>
			</tr>
			<tr>
				<td>Residential Address :</td>
				<td><div name="raddress" id="raddress" title="Residential Address"><?php if(isset($contact) && $contact['0']['raddress']!=" "){echo $contact['0']['raddress'];}?></div>
			</td>
			</tr>
			<tr>
				<td>Mobile No. :</td><td>
				<label name="mobile" id="mobile" title="Mobile No." ><?php if(isset($contact) && $contact['0']['mobile']!="" ){?> <?php echo $contact['0']['mobile'];}?></label>
		        </td>
			</tr>
			<tr>
				<td>Alt. contact no. :</td>
				<td><label name="altcontactnumber" id="altcontactnumber" title="Alt. Contact No."> <?php if(isset($contact)){ ?> <?php echo $contact['0']['altcontactnumber'];}?></label>
				 </td>
			</tr>
			
         
         	<tr>
				<td>
				</td>
				<td><a href='/editcontact/userid/<?php echo $id;?>'>Edit</a></td>
			</tr>
         	</table>
<!--			</form>-->
			</div>	

<!-- 			<script type="text/javascript"> 
			$(document).ready(function(){
				$("#edit").button()
				.click(function( event ) {
				   event.preventDefault();
				  window.open(<?php //echo $this->url('editmyprofile');?>);
				});

				});
			</script> -->