<script type="text/javascript" src="/js/bootbox.min.js"></script>
<?php
use IntranetUtils\Common;
$common=new Common();
?>

<div id="activitylog">
	<form action="" method="post" id="form1" class="form-horizontal">
		<input type="hidden" id="projectid" name="projectid" value="<?php if(isset($activityLog) && $activityLog->getProject_id() !=null){ echo $activityLog->getProject_id();}else{echo $projectId; }?>" />
		<input type="hidden" id="activityid" name="activityid" value="<?php if(isset($activityLog) && $activityLog->getActivity_id() !=null){ echo $activityLog->getActivity_id();}else{echo $activityId; }?>" />
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label small-label">Type:</label>
				<div class="controls small-margin">
	                <select id="category" name="category">
	                	<option value="">--Select--</option>
	                	<?php if(isset($category) && count($category)>0){
                			for($i=0;$i<count($category);$i++){?>	
	                			<option value="<?php echo $category[$i]['id'];?>" <?php if(isset($activityLog) && $activityLog->getCategory_id()!=null && $activityLog->getCategory_id()==$category[$i]['id']){echo 'selected="selected"';}?>><?php echo ucwords($category[$i]['name']); ?></option>
                			<?php }
	                	}?>
                	</select>
                </div>
            </div>
		</div>
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label small-label">Description:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls small-margin">
					<textarea id="desc" name="desc" title="Description" rows="6" 
						class="span12"><?php if(isset ($activityLog) && $activityLog->getDescription()!=null)
						{ echo $activityLog->getDescription();}?></textarea>
				</div>
				<div class="controls small-margin"><div id="desc_error"></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label small-label">Activity Date:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls small-margin">
					<input type="text" id="adate" name="adate" title="Activity date" 
						<?php if(isset ($activityLog) && $activityLog->getActivity_date()!=null){?> 
						value="<?php echo  $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$activityLog->getActivity_date()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="altadate" name="altadate" title="altadate" 
						<?php if(isset ($activityLog) && $activityLog->getActivity_date()!=null){?> 
						value="<?php echo  $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$activityLog->getActivity_date()),"Asia/Calcutta","Y-m-d");}?>"/>
				</div>
				<div class="controls small-margin"><div id="adate_error"></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label small-label">Spent Time:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls small-margin">
					<input id="spent" name="spent" title="Spent Time" type="text" 
					value="<?php if(isset ($activityLog) && $activityLog->getSeconds_spent()!=null)
					{echo $common->convertSpentTime($activityLog->getSeconds_spent());}?>"/>
				</div>
				<div class="controls small-margin"><div id="spent_error"></div></div>
			</div>
		</div>
	</form>
</div>
	<script type="text/javascript">
 $(document).ready(function(){	 
     $( "#adate" ).datepicker({dateFormat:"dd/mm/yy", changeMonth: true,changeYear: true,altField:"#altadate",altFormat: "yy-mm-dd" });
     $("#spent").timepicker({timeOnly:true}); 
     $("#btnaddactivitylog").unbind('click');   
     $("#btnaddactivitylog").bind('click',function(){add('<?php if(isset($activityLog) && $activityLog->getId()!="" && $activityLog->getId()!=null){ echo $activityLog->getId();}?>');});

     $('#assigneduser').bind('change', function(ev) {
		  getactivity();	
	  });
});
 
function add(id){ 
     $.ajax({
         type: "POST",
         url:  "<?php echo $this->url('addactivitylog'); ?>",
         dataType:"json",
         data: $("#form1").serialize()+"&id="+id,
         beforeSend: function () {
 			$('#addactivitylog').mask("Loading...");
 	 	 },
        
         success: function(response){
        	  
              if(response['returnvalue']=="valid"){
            	  $( "#addactivitylogModal" ).modal('hide');
                     <?php if(isset($activityLog) && $activityLog->getId()!=null){?>
                     bootbox.alert("Record has been update Successfully");
           	  <?php }else{?>
           	bootbox.alert("Record has been added Successfully");
           	  <?php }?>            	  
           	$("#list").trigger("reloadGrid");
                     return false;
              }   
                                   
              else if(response.returnvalue=="exception"){
            	  bootbox.alert("This Operation Could not be Completed,Please contact administrator");
                   return false;
              }
             
              else{
                   for(var key in response.data){
                       if(response.data[key]=="null"){
                    	   $("#"+key+"_error").attr("style","color:red");
                           $("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");                                   
                       }
                       else if(response.data[key]=="valid"){
                           $("#"+key+"_error").html(" ");                                   
                       }
                         else if(response.data[key]=="invalid"){
							$("#"+key+"_error").attr("style","color:red");
							$("#"+key+"_error").html("Invalid value for "+$("#"+key).attr("title"));                           
                           
                       }
                       else if(response.data[key]=="duplicate"){
                    	   bootbox.alert("field aleady exist");
                          }
                    }}
           },
       	error: function(XMLHttpRequest,textStatus){
       		bootbox.alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
	   	},
		complete: function(){
	    	setTimeout(function(){		    	
	    		$('#addactivitylog').unmask();	
	    		//unmaskloading('addProjects');
			},500);
		}
	
       });
      return false; 
}
</script>

