<h2 class="title">Log Spent Time</h2><hr/>
<form action="" method="post" id="formaddactivity" class="form-horizontal">
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">Project:</label>
			<div class="controls">
				<select id="project" name="project" title="Project">
					<option value="">--Select--</option>
					<?php if(isset($project) && count($project)>0){
						for($i=0;$i<count($project);$i++){
							?>
					<option value="<?php echo $project[$i]['id'];?>">
						<?php echo ucwords($project[$i]['name']); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
			<div class="controls"><div id="project_error"></div></div>
		</div>
		<div class="span6 control-group">
			<label class="control-label">Assigned User:</label>
			<div class="controls">
				<select id="assigneduser" name="assigneduser" title="Assigned User">
					<option value="">--Select--</option>
					<?php if(isset($assignee) && count($assignee)>0){
						for($i=0;$i<count($assignee);$i++){
							?>
					<option value="<?php echo $assignee[$i]->__get('id');?>">
						<?php echo ucwords($assignee[$i]->__get('fname')." ".$assignee[$i]->__get('lname')); ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
			<div class="controls"><div id="assigneduser_error"></div></div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">Milestone:</label>
			<div class="controls">
				<select id="milestone" name="milestone" title="milestone" disabled>
					<option value="">--Select--</option>
					<?php if(isset($milestone) && count($milestone)>0){
							 for($i=0;$i<count($milestone);$i++){?>
					<option value="<?php echo $milestone[$i]['id'];?>"
					<?php if(isset($milestone) && $milestone[$i]['id']!=null ){echo 'selected="selected"';}?>>
					</option>
					<?php }?>
					<?php }?>
				</select>
			<div class="controls"><div id="milestone_error"></div></div>
			</div>
		</div>
		<div class="span6 control-group">
			<label class="control-label">Activity:</label>
			<div class="controls">
				<select id="activityid" name="activityid" title="Activity">
					<option value="">--Select--</option>
					<?php if(isset($activity) && count($activity)>0){
							 for($i=0;$i<count($activity);$i++){?>
					<option value="<?php echo $activity[$i]['id'];?>"
					<?php if(isset($activity) && $activity[$i]['id']!=null ){echo 'selected="selected"';}?>>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
			<div class="controls"><div id="activityid_error"></div></div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<label class="control-label">Activity Date:</label>
			<div class="controls">
				<input type="text" id="activitydate" name="activitydate" title="Activity date" />
				<input type="hidden" id="altactivitydate" name="altactivitydate" title="altactiviydate" />
				<button id="clearadate" class="btn btn-success" name="clearadate">Clear Activity Date</button>
			</div>
			<div class="controls"><div id="activitydate_error"></div></div>
		</div>
		<div class="span6 control-group">
			<label class="control-label">Due Date:</label>
			<div class="controls">
				<input type="text" id="duedate" name="duedate" title="Due date" /> 
				<input type="hidden" id="altduedate" name="altduedate" title="altduedate" />
				<button id="clear" class="btn btn-success" name="clear">Clear Due Date</button>
				<div id="duedate_error"></div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6 control-group">
			<div class="controls">
				<button id="addnew" class="btn btn-success" name="addnew">Add Spent Time</button>
			</div>
		</div>
	</div>
</form>

<div id="addactivitylogModal" class="modal hide fade" tabindex="-1" role="dialog" 
	data-backdrop="static" data-toggle="modal" aria-labelledby="myModalLabel" aria-hidden="true">
	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right: 5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:5px;">Activity Log</h6>
    	
    </div>
	<!-- dialog contents -->
	<div class="modal-body">
		<div id="addactivitylog" name="addactivitylog" title="ActivityLog"></div>
    </div>
    <div class="modal-footer">
    <button class="btn btn-success" style="margin-left:33px;" type="button" value="Ok" id="ok" onclick="add('<?php if(isset($activityLog) && $activityLog->getId()!="" && $activityLog->getId()!=null){ echo $activityLog->getId();}?>')">Submit</button>
    </div>
    <!-- dialog buttons -->
</div>


<script type="text/javascript">
	 $(function() {
		 $( "#duedate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altduedate",altFormat: "yy-mm-dd" });
		 $( "#activitydate" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altactivitydate",altFormat: "yy-mm-dd" });

			// $( "#addactivitylog" ).dialog({ autoOpen:false} ,"option", "width", 1000 );
		 $("#clear")
		 .click(function( event ) {
		  event.preventDefault();
		  clr();
		});
		 $("#clearadate")
		 .click(function( event ) {
		  event.preventDefault();
		  clradate();
		});
			 $("#addnew")
			 .click(function( event ) {
			  event.preventDefault();
			  if($("#activityid").val()==""){
				  alert("Please select activity first");
				  return false;
			  }
			
			  $.ajax({
			       type: "POST",
			       url: "<?php echo $this->url('addactivitylog'); ?>",             
			       data: {flag: "view",activityid:$("#activityid").val(),projectid:$("#project").val()},
			       beforeSend: function () {
			 			//$('#formaddactivity').mask("Loading...");
			 	 	 },
			        
				       success: function(response)
			       {   
				      $("#addactivitylogModal").modal({show:true});
			          $("#addactivitylog").html(response);
			          $("#addactivitylog").append("<div><sup>*</sup>Please make sure that you have selected right activity from drop down,currently your selected activity is <b>"+$("#activityid option:selected").text()+"</b></div>");
			       },
			        	error: function(XMLHttpRequest,textStatus){
				    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
				   	},
					complete: function(){
				    	setTimeout(function(){		    	
				    		$('#formaddactivity').unmask();	
				    		//unmaskloading('addProjects');
						},500);
					}
			     });
			 });
		  $('#project').bind('change', function(ev) {
		     //getmilestone();
		     getactivity();	
		  });
		  $('#milestone').bind('change', function(ev) {
			  getactivity();	
		  });
		  $('#duedate').bind('change', function(ev) {
			  getactivity();	
		  });
		  $('#activitydate').bind('change', function(ev) {
			  getactivity();	
		  });
		  $('#assigneduser').bind('change', function(ev) {
			  getactivity();	
		  });
		  $('#activityid').bind('change', function(ev) {
			  activitydetail();
			    });
		   });
function getmilestone(){
	var value = $("#project").val();
	 var selectmilestone = document.getElementById('milestone');		     		     
     selectmilestone.options.length=0;
     var op = document.createElement("option");		     
	    op.value="";
	    op.text="--Select--";
     selectmilestone.options.add(op);
     $.ajax({	
    	 type: "POST",	      
    	 url: "<?php echo $this->url('getmilestone');?>",
        data: {projectid: value},	
        dataType:"json",
        beforeSend: function () {
			$('#formaddactivity').mask("Loading...");
	 	 },
        success: function(response)
         {	
            var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['name'];
		    selectmilestone.options.add(op);
		    $("#milestone").removeAttr("disabled");
		    }				    
         },
	 	complete: function(){
	    	setTimeout(function(){		    	
	    		$('#formaddactivity').unmask();	
	    		//unmaskloading('addProjects');
			},500);
	 	}        
     });
}
function getactivity(){
	var projectid = $("#project").val();
	var milestone = $("#milestone").val();
	var altduedate = $("#duedate").val();
	var altactivitydate = $("#activitydate").val();
	var assignee = $('#assigneduser').val();
	
	if(altduedate !="" && altduedate !='' ){ altduedate = $("#altduedate").val();
	}else{
		altduedate = "";
		}
	if(altactivitydate !="" && altactivitydate !='' ){ altactivitydate = $("#altactivitydate").val();
	}else{
		altactivitydate = "";
		}
	var selectactivity = document.getElementById('activityid');		     		     
    selectactivity.options.length=0;
    var op = document.createElement("option");		     
   op.value="";
   op.text="--Select--";
   selectactivity.options.add(op);
	    if(projectid!="" ){
    $.ajax({	
   	 type: "POST",	      
   	 url: "<?php echo $this->url('getactivity');?>",
       data: {projectid: projectid,altduedate:altduedate,altactivitydate:altactivitydate,assignee:assignee},	
       dataType:"json",
       success: function(response)
        {	
        if(response['returnvalue']=="invalid"){
            alert("Activity not found");
         } 	
       	 var $i;				    	
		    for($i=0;$i<response.data.length;$i++){
		    var op = document.createElement("option");
		    op.value=response.data[$i]['id'];
		    op.text=response.data[$i]['subject'];
		    selectactivity.options.add(op);
		    }				    
	     },
	     error: function(XMLHttpRequest,textStatus){
	    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
	   	},
    });
 }
}
function clr(){
	 document.getElementById("duedate").value='';
	 document.getElementById("altduedate").value='';
	    				}
function clradate(){
	 document.getElementById("activitydate").value='';
	 document.getElementById("altactivitydate").value='';
	    				}
function activitydetail(){
	 $.ajax({
	       type: "POST",
	       url: "<?php echo $this->url('logspenttime'); ?>",             
	       data: {activityid:$("#activityid").val()},
	       beforeSend: function () {
				$('#formaddactivity').mask("Loading...");
		 	 },
	       success: function(response){
	    	   $("#div1").html("");
	    	   $("#div1").html("<b>Selected Activity Detail</b><hr/>");
	    	   $("#div1").append("<b>Subject:</b> " +response.data[0]['subject']+ "<br/>");
	    	   $("#div1").append("<b>Description:</b> " +response.data[0]['description']+ "<br/>");
	    	   $("#div1").append("<b>Due Date:</b> " +response.data[0]['due_date']+ "<br/>");
	    	   $("#div1").append("<b>Assigned To:</b> " +response.data[0]['assigned_to_id']);
	    	   },
	  	     error: function(XMLHttpRequest,textStatus){
		    	 alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	},
			complete: function(){
		    	setTimeout(function(){		    	
		    		$('#formaddactivity').unmask();	
		    		//unmaskloading('addProjects');
				},500);
			}	
	        });
}

</script>
<div id="div1" name="div1">
</div>
