<?php
use IntranetUtils\Common;
$common=new Common();
?>
<div>
<h2 class="title">Add Milestone</h2><hr />
	<form action="" method="post" id="form1" class="form-horizontal">
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label">Name:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="name" name="name" title="Name"
					<?php if(isset($milestones) && $milestones->getId() !="null"){?>
						value="<?php echo $milestones->getName();}?>" />
				</div>
				<div class="controls"><div id="name_error"></div></div>
			</div>
			<div class="span6 control-group">
				<label class="control-label">Project:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="projectid" name="projectid" title="Project">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($projects);$i++){?>
						<option value="<?php echo $projects[$i]['id'];?>"
						<?php if(isset($milestones) && $milestones->getProject_id()!=null && $projects[$i]['id'] ==$milestones->getProject_id()){?>
							selected="selected" <?php }?>>
							<?php echo $projects[$i]['name'];?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="projectid_error"></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label">Estimated Startdate:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="esd" name="esd" title="Estimated startdate"
						<?php if(isset($milestones) && ($milestones->getEstimated_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$milestones->getEstimated_startdate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="altesd" name="altesd" title="altesd"
						<?php if(isset($milestones) && ($milestones->getEstimated_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$milestones->getEstimated_startdate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="esd_error" ></div></div>
			</div>
			<div class="span6 control-group">
				<label class="control-label">Estimated enddate:</label>
				<div class="controls">
					<input type="text" id="eed" name="eed" title="Estimated enddate"
						<?php if(isset($milestones) && ($milestones->getEstimated_enddate())){?>
							value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
							$milestones->getEstimated_enddate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="alteed" name="alteed" title="alteed"
					<?php if(isset($milestones) && ($milestones->getEstimated_enddate())){?>
					value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
					$milestones->getEstimated_enddate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="eed_error"></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label">Actual startdate:</label>
				<div class="controls">
					<input type="text" id="asd" name="asd" title="Actual startdate"
						<?php if(isset($milestones) && ($milestones->getActual_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$milestones->getActual_startdate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="altasd" name="altasd" title="altasd"
						<?php if(isset($milestones) && ($milestones->getActual_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$milestones->getActual_startdate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="asd_error"></div></div>
			</div>
			<div class="span6 control-group">
				<label class="control-label">Actual enddate:</label>
				<div class="controls">
					<input type="text" id="aed" name="aed" title="Actual enddate"
					<?php  if(isset($milestones) && ($milestones->getActual_enddate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$milestones->getActual_enddate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="altaed" name="altaed" title="altaed" class="datepicker"
						<?php  if(isset($milestones) && ($milestones->getActual_enddate())){?>
							value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
							$milestones->getActual_enddate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="aed_error"></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label">Estimated Hours:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="esthours" name="esthours" title="Estimated Hours(HH:mm)"
						<?php if(isset($milestones) && $milestones->getEstimated_hours() !="null" ){?>
						value="<?php echo $common->convertSpentTime($milestones->getEstimated_hours());}?>" />
				</div>
				<div class="controls"><div id="esthours_error"></div></div>
			</div>
			<div class="span6 control-group">
				<label class="control-label">Status:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="status" name="status" title="Status">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($status);$i++){?>
						<option value="<?php echo $status[$i]['id'];?>"
						<?php if(isset($milestones) && $milestones->getStatus_id()!=null && $status[$i]['id'] ==$milestones->getStatus_id()){?>
							selected="selected" <?php }?>>
							<?php echo $status[$i]['name'];?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="status_error" ></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<label class="control-label">Assigned User:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<textarea name="assigneduser" id="assigneduser" tabindex="7" title="Assigned User" rows="4" class="input-xlarge" style="margin-bottom:25px;"><?php if(isset($auName) && $auName!=null){echo $auName;}?></textarea>	
				</div>
				<div class="controls"><div id="assigneduser_error"></div></div>
			</div>
			<div class="span6 control-group">
				<label class="control-label">Description:</label>
				<div class="controls">
					<textarea id="description" name="description" title="Description" rows="4" 
					class="input-xlarge"><?php if(isset($milestones) && 
					$milestones->getDescription() !="null" ){?><?php echo 
					$milestones->getDescription();}?></textarea>
				</div>
				<div class="controls"><div id="description_error"></div></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span6 control-group">
				<div class="controls">
					<button class="btn btn-success" type="button" value="Ok" 
						style="margin-top:-25px;" id="btnaddmilestoneassignee" >Submit</button>
				</div>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
$(document).ready(function(){
	
	   $( "#esd" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altesd", changeMonth: true,
	       changeYear: true,
		       altFormat: "yy-mm-dd" });
	   $( "#eed" ).datepicker({dateFormat:"dd/mm/yy",altField:"#alteed", changeMonth: true,
	       changeYear: true,
		       altFormat: "yy-mm-dd" });
	   $( "#asd" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altasd", changeMonth: true,
	       changeYear: true,
		       altFormat: "yy-mm-dd" });
	   $( "#aed" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altaed", changeMonth: true,
	       changeYear: true,
		       altFormat: "yy-mm-dd" });

	 	  
		  $( "#assigneduser" )
	      // don't navigate away from the field on tab when selecting an item
	      .bind( "keydown", function( event ) {
	          if ( event.keyCode === $.ui.keyCode.TAB &&
	                  $( this ).data( "autocomplete" ).menu.active ) {
	               event.preventDefault();
	          }
	      })
	      .autocomplete({
	          source: function( request, response ) {
	              $.getJSON( "<?php echo $this->url('getmultiuser');?>", {
	                  term: extractLast( request.term )
	              }, response );
	          },
	          search: function() {
	              
	              var term = extractLast( this.value );
	              if ( term.length < 1 ) {
	                  return false;
	              }
	          },
	          focus: function() {
	              // prevent value inserted on focus
	              return false;
	          },
	          select: function( event, ui ) {
	              var terms = split( this.value );
	              // remove the current input
	              terms.pop();
	              // add the selected item
	              terms.push( ui.item.value );
	              // add placeholder to get the comma-and-space at the end
	              terms.push( "" );
	              this.value = terms.join( "," );
	              //$(this).css("height","150px;")
	              
	              return false;
	          }
	      });

		  $("#btnaddmilestoneassignee").unbind('click');
		   $("#btnaddmilestoneassignee").bind('click',function(){
		       add('<?php if(isset($milestones) && $milestones->getId()!="" && $milestones->getId()!=null){ echo $milestones->getId();}?>');
	       });
});

function split( val ) {
	return val.split( /,\s*/ );
}
function extractLast( term ) {
	return split( term ).pop();
}		 

function add(id){ 
     $.ajax({
         type: "POST",
         url:"<?php echo $this->url('addmilestones');?>",
         dataType:"json",
         data: $("#form1").serialize()+"&id="+id,
         success: function(response){   
			if(response['returnvalue']=="valid"){
				<?php if (isset($milestones) && $milestones->getId()!=null){?>
				bootbox.alert("Record has been updated Successfully");
					window.location.href = "/milestones";
				<?php }
				else{?>
				bootbox.alert("Record has been added Successfully");
					window.location.href = "/milestones";
				<?php }?>
				return false;
			}
			else if(response.returnvalue=="exception"){
				bootbox.alert("This Operation Could not be Completed,Please contact administrator");
				return false;
			}
            else{
	               for(var key in response.data){
		            if(response.data[key]=="null"){
		            	$("#"+key+"_error").css("color", "#FF0000");
		            	$("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");					               
		               }
		            else if(response.data[key]=="valid"){
		            	   $("#"+key+"_error").html(" ");					               
		               }
		            else if(response.data[key]=="invalid"){
		            	$("#"+key+"_error").css("color", "red");
		            	$("#"+key+"_error").html("Invalid value for "+$("#"+key).attr("title"));
			               }
		               else if(response.data[key]=="duplicate"){
		            	   bootbox.alert("Milestone aleady exist");
			              }

		               else if(response.data[key]=="estimatemore"){
		            	   bootbox.alert(" Total Milestone Estimate time is more than Project Estimate time");
			              }
		            }}
		   },
		   error: function(XMLHttpRequest,textStatus){
			   bootbox.alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   	},
       });
      return false; 
	}
/*	function viewmilestone(id){
		$.ajax({
			type: "POST",
			url: "<?php echo $this->url('addmilestones');?>",	         
			data: {flag: "view", id: id },
			success: function(response){
				$("#addmilestonesModal").modal({show:true});
				$("#addmilestones").html(response);
			},
			error: function(XMLHttpRequest,textStatus){
				alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
  		   	},
		});
	};
*/
</script>