<?php
// print_r($comanys);
use IntranetUtils\Common;
$common=new Common();
?>
<div id="addproject">
			<form  id="form1" method="post" class="form-horizontal">
			<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Company:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="company" name="company" title="Company">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($comanys);$i++){?>
							<option value="<?php echo $comanys[$i]['id'];?>"
						<?php if(isset($project) && $project->getCompany_id()!=null && $project->getCompany_id()==$comanys[$i]['id']){?>
							selected="selected" <?php }?>>
							<?php echo ucfirst($comanys[$i]['name']);?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="company_error" class="error"></div></div>
			</div>
		</div>
		
		
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Project Name:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="name" name="name" title="Name"
				<?php if(isset($project) && $project->getName()!=''){?>
					value="<?php echo ucfirst($project->getName());}?>">
				</div>
				<div class="controls"><div id="name_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Type:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="type" name="type" title="Type">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($ptype);$i++){?>
							<option value="<?php echo $ptype[$i]['id'];?>"
						<?php if(isset($project) && $project->getType_id()!=null && $project->getType_id()==$ptype[$i]['id']){?>
							selected="selected" <?php }?>>
							<?php echo ucfirst($ptype[$i]['name']);?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="type_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Estimated Start Date:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input type="text" id="esd" name="esd" title="Estimated startdate"
						<?php if(isset($project) && ($project->getEstimated_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getEstimated_startdate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="altesd" name="altesd" title="altesd"
						<?php if(isset($project) && ($project->getEstimated_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getEstimated_startdate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="esd_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Estimated End Date:</label>
				<div class="controls">
					<input type="text" id="eed" name="eed" title="Estimated enddate"
						<?php if(isset($project) && ($project->getEstimated_enddate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getEstimated_enddate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="alteed" name="alteed" title="alteed"
						<?php if(isset($project) && ($project->getEstimated_enddate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getEstimated_enddate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="eed_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Actual Start Date:</label>
				<div class="controls">
					<input type="text" id="asd" name="asd" title="Actual startdate"
						<?php  if(isset($project) && ($project->getActual_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getActual_startdate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="altasd" name="altasd" title="altasd"
						<?php  if(isset($project) && ($project->getActual_startdate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getActual_startdate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="asd_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Actual End Date:</label>
				<div class="controls">
					<input type="text" id="aed" name="aed" title="Actual enddate"
						<?php  if(isset($project) && ($project->getActual_enddate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getActual_enddate()),"Asia/Calcutta","d/m/Y");}?>" />
					<input type="hidden" id="altaed" name="altaed" title="altaed"
						<?php  if(isset($project) && ($project->getActual_enddate())){?>
						value="<?php echo $common->ConvertGMTToLocalTimezone(date("Y-m-d H:i:s",
						$project->getActual_enddate()),"Asia/Calcutta","Y-m-d");}?>" />
				</div>
				<div class="controls"><div id="aed_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Estimated Hours:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<input placeholder="HH:MM" type="text" id="esthours" name="esthours" title="Estimated Hours(HH:mm)"
						<?php if(isset($project) && $project->getEstimated_hours() !="null" ){?>
						value="<?php echo $common->convertSpentTime($project->getEstimated_hours());}?>" />
				</div>
				<div class="controls"><div id="esthours_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Status:<sup style="color:#FF0000;">*</sup></label>
				<div class="controls">
					<select id="status" name="status" title="Status">
						<option value="">--Select--</option>
						<?php for($i=0;$i<count($status);$i++){?>
						<option value="<?php echo $status[$i]['id'];?>"
						<?php if(isset($project) && $project->getStatus_id()!=null && $project->getStatus_id()==$status[$i]['id']){?>
							selected="selected" <?php }
							elseif (isset($defaultStatus) && $defaultStatus[0]['status_id']==$status[$i]['id']) {?>
								 selected="selected"
								 <?php }?>>
							<?php echo ucfirst($status[$i]['name']);?>
						</option>
						<?php }?>
					</select>
				</div>
				<div class="controls"><div id="status_error" class="error"></div></div>
			</div>
		</div>
		
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">BD:<sup style="color:#FF0000;">*</sup></label>
					<div class="controls">
				<select id="bussinessDeveloper" name="bussinessDeveloper" title="BD">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>"
					<?php if(isset($project) && $project->getBd()==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
				<div class="controls"><div id="bussinessDeveloper_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Escalation Manager:<sup style="color:#FF0000;">*</sup></label>
					<div class="controls">
				<select id="escalationManager" name="escalationManager" title="Manager">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>"
					<?php if(isset($project) && $project->getManager()==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
				<div class="controls"><div id="escalationManager_error" class="error"></div></div>
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="control-group">
				<label class="control-label">Project Coordinator:<sup style="color:#FF0000;">*</sup></label>
					<div class="controls">
				<select id="projectCoordinator" name="projectCoordinator" title="Coordinator">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>"
					<?php if(isset($project) && $project->getCoordinator()==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
					<?php }?>
				</select>
			</div>
				<div class="controls"><div id="projectCoordinator_error" class="error"></div></div>
			</div>
			<div class="modal-footer">
    	<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			type="button" id="closemodeldilog" data-dismiss="modal" >Close</button>
	    <button class="btn btn-success" data-toggle="modal" style="margin-left:33px" 
	    	type="button" value="Ok" id="ok" name="ok">Submit</button>
    </div>
		</div>
	</form>
</div>
<script type="text/javascript">
$(document).ready(function(){
		$( "#esd" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altesd",  changeMonth: true,
		       changeYear: true,
		      altFormat: "yy-mm-dd" });
	   $( "#eed" ).datepicker({dateFormat:"dd/mm/yy",altField:"#alteed", changeMonth: true,
	       changeYear: true,
		       altFormat: "yy-mm-dd" });
	   $( "#asd" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altasd",  changeMonth: true,
	       changeYear: true,
		      altFormat: "yy-mm-dd" });
	   $( "#aed" ).datepicker({dateFormat:"dd/mm/yy",altField:"#altaed", changeMonth: true,
	       changeYear: true,
		       altFormat: "yy-mm-dd" });

	   $("#ok")
	   .click(function( event ) {
           event.preventDefault();
          add('<?php if(isset($project) && $project->getId()!="" && $project->getId()!=null){ echo $project->getId();}?>');
    
          });
	});
	
function add(id){ 
	var company=$("#company").val();
	var name=$("#name").val();
	var type=$("#type").val();
	
	var altesd=$("#altesd").val();
	var eed=$("#eed").val();
	var alteed="";
	if(eed !=""){
	alteed=$("#alteed").val();
	}

	var asd=$("#asd").val();
	var altasd="";
	if(asd !=""){
		altasd=$("#altasd").val();
		}
	
	var aed=$("#aed").val();
	var altaed="";
	if(asd !=""){
		altaed=$("#altaed").val();
		}
	
	
	var esthours=$("#esthours").val();
	var status=$("#status").val();
	var bussinessDeveloper=$("#bussinessDeveloper").val();
	var escalationManager=$("#escalationManager").val();
	var projectCoordinator=$("#projectCoordinator").val();
	
	$.ajax({
         type: "POST",
         url: "<?php echo $this->url('addprojects');?>",
         dataType:"json",
         data: {'id':id,'company':company,'name':name,'type':type,'altesd':altesd,'eed':eed,'alteed':alteed,
             'asd':asd,'altasd':altasd,'aed':aed,'altaed':altaed,'esthours':esthours,'status':status,
             'bussinessDeveloper':bussinessDeveloper,'escalationManager':escalationManager,'projectCoordinator':projectCoordinator},
         beforeSend: function () {
   			$('#addproject').mask("Loading...");
   	 	 },    
         
         success: function(response)
         {   
              if(response['returnvalue']=="valid"){
            	    $("#addProjectsModal").modal('hide');
		<?php  if(isset($project) && $project->getId()!=""){?>
		        alert("Project has been updated Successfully");
              <?php    } else{?>
//               $("#addProjects").modal('hide');
             	alert("Project has been added Successfully");
              <?php }?>
                     $("#list").trigger("reloadGrid");
                     return false;
              }		               
              else if(response.returnvalue=="exception"){
            	 alert("This Operation Could not be Completed,Please contact administrator");
                   return false;
              }
              else if(response.returnvalue=="duplicate"){
            	  bootbox.alert("Project name aleady exist");
                  return false;
             }
             else{
				for(var key in response.data){
					if(response.data[key]=="null"){
						$("#"+key+"_error").css("color", "#FF0000");
						$("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");					               
					}
		            else if(response.data[key]=="valid"){
						$("#"+key+"_error").html(" ");	
						$("#addProjects").modal('hide');				               
					}
					else if(response.data[key]=="invalid"){
						$("#"+key+"_error").css("color", "#FF0000");
		            	$("#"+key+"_error").html("The value of "+$("#"+key).attr("title")+" is invalid");
					}
	               else if(response.data[key]=="duplicate"){
	            	   alert("Project aleady exist in selected company");
					}
	            }}
		   },
		   error: function(XMLHttpRequest,textStatus){
			   alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
		   },
			complete: function(){
		    	setTimeout(function(){		    	
		    		$('#addProjects').unmask();	
		    	},500);
			}
		 });
      return false; 
}
</script>