<h2 class="title">Project Types</h2><hr/>
<div style="min-height: 500px;" id="gridContainer">
	<table id="list">
	</table>
	<div id="pager" ></div>
</div> 
<div id="addProjecttypeModal" name="Modal" title="Add Project Type" 
	class="modal hide fade" data-backdrop="static" data-toggle="modal" 
	tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

	<button class="bootbox-close-button close" type="button" data-dismiss="modal" style="margin-right:5px;">×</button>
    <div class="modal-header">
    	<h6 class="title" style="margin-bottom:2px;">Add Project Type</h6>
    </div>
	<!-- dialog contents -->
	<div class="modal-body">
		<div id="addProjecttype" name="addProjecttype" title="Add Project Type"></div>
    </div>
    <div class="modal-footer">
    	<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;" 
			id="closemodeldilog" data-dismiss="modal">Close</button>
		<button class="btn btn-success" data-toggle="modal" style="margin-left:33px;"  
			id="ok" name="btnaddactivitylog">Submit</button>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	jQuery("#list").jqGrid({
		url:"<?php echo $this->url('gridprojecttype'); ?>",
		datatype: "json",
		mtype: 'POST',
		colNames:['Name','Color','Is Default'],
		colModel :[
		{name:'name',index:'name', editable:true},
		{name:'color',index:'color',editable:true},
		{name:'isdefault',index:'isdefault',sort:false},		
		],
	  	rowNum:100,
	    rowList:[100,200,500],
	    navigator:true,
	    pager: '#pager',
	    sortname: 'name',
	    viewrecords: true,
	    sortorder: "desc",
	    //width:"1000",
	    height:"400",
	});	
	 jQuery("#list").jqGrid('navGrid',"#pager",{add:false,edit:true,del:false, search:false, refresh:false}).navButtonAdd('#pager',{caption:"Add New", onClickButton:function(){
		$( "#addProjecttypeModal" ).modal({show:true});
		var id=jQuery('#list').getGridParam('selrow');
		$.ajax({
	         type: "POST",
	         url:"<?php echo $this->url('addprojecttype');?>",	         
	         data: {flag: "view", id: id },
	         success: function(response)
	         {   
	        	 $("#addProjecttype").html(response);
	        	 $("#list").trigger("reloadGrid");
	        	 //alert("record added");
			   }
	       });
	 }}).navButtonAdd('#pager',{caption:"Delete", onClickButton:function(){
		 var id=jQuery('#list').getGridParam('selrow');
		 $.ajax({
			 type: "POST",
	      	 url:"<?php echo $this->url('deleteprojecttype'); ?>",	         
	         data: {flag: "view", id: id },
	         beforeSend: function () {
 				$('#list').mask("Loading...");
 		 	 },
	         success: function(response)
	         {   
	        	  $("#list").trigger("reloadGrid");
	        	  alert("record deleted");
		        		   },
		        		   error: function(XMLHttpRequest,textStatus){
		        			   alert('This Operation Could not be Completed. Please check your Internet Connection and try Again. If problem persists please contact Support');
						   	},
							complete: function(){
						    	setTimeout(function(){		    	
						    		$('#list').unmask();	
						    		//unmaskloading('addProjects');
								},500);
	     		}
	       });

		 }});
	   resizegrid("gridContainer","list");
	   jQuery("#list").setGridWidth($('#gridContainer').width(), true);
	   $("#ok").click(function( event ) {
		   var id=jQuery('#list').getGridParam('selrow');
	     event.preventDefault();
	     add('<?php if(isset($projecttype)){echo $projecttype->getId();}?>');
	 });
	   $("#pager_left").css('width','130px');
	});	 
	</script>

