<?php 

use Zend\Authentication\AuthenticationService;
$auth=new AuthenticationService();
$currentuser= $auth->getIdentity()->id;
?>
<h2 class="title">Change Password</h2><hr/>
<div>
	<form action="" method="post" id="form1" class="form-horizontal">
		<div class="row-fluid">
			<?php if(isset($users) && $users!=null && $users!=""){?>
			<div class="span4 control-group">
			<label class="control-label">User:</label>
			<div class="controls">
				<select id="user" name="user" title="User" class="input-medium">
					<option value="">--Select--</option>
					<?php if(isset($users) && count($users)>0){
						for($i=0;$i<count($users);$i++){
							?>
					<option value="<?php echo $users[$i]->__get('id');?>"
					<?php if($currentuser==$users[$i]->__get('id')){echo 'selected="selected"';}?>>
						<?php if($users[$i]->__get('lname')!=null && $users[$i]->__get('lname')!=""){
							echo ucwords($users[$i]->__get('fname')." ".$users[$i]->__get('lname'));
						}else{ echo ucwords($users[$i]->__get('fname'));
							} ?>
					</option>
					<?php }?>
				</select>
						<?php }?>
			</div>
		</div>
		<?php }?>
		<?php if (!isset($users)){?>		
		<div class="span4 control-group">
			<label class="control-label">Old Password:</label>
			<div class="controls">
				<input type="password" id="opassword" name="opassword" title="Old Password" class="input-medium" />
			</div>
			<div class="controls"><div id="opassword_error"></div></div>
		</div>
		<?php }?>
		<div class="span3 control-group">
			<label class="control-label">New Password:</label>
			<div class="controls">
				<input type="password" id="npassword" name="npassword" title="New Password" class="input-medium" />
			</div>
			<div class="controls"><div id="npassword_error"></div></div>
		</div>
		<div class="span3 control-group">
<!--			<label class="control-label">-->
			<div class="controls">
			<button id="ok" class="btn btn-success" name="ok">Submit</button>
			</div>
<!--			</label>-->
		</div>
	</div>
	</form>

	<script type="text/javascript">
$(document).ready(function(){
	   $("#ok")//.button()
	   .click(function( event ) {
           event.preventDefault();
           changepassword();
       });
});
function changepassword(){

	if($("#list")){
	 id=jQuery('#list').getGridParam('selrow');
	}
     $.ajax({
         type: "POST",
         url: "<?php echo $this->url('changepassword');?>",
         dataType:"json",
         data: $("#form1").serialize(),
         success: function(response)
         {   
              if(response['returnvalue']=="valid"){
            	  alert("Password has been changed Successfully");
                     return false;
              }		               
              else if(response.returnvalue=="exception"){
            	  alert("This Operation Could not be Completed,Please contact administrator");
                   return false;
              }
             else{
	               for(var key in response.data){
		            if(response.data[key]=="null"){
		            	$("#"+key+"_error").html($("#"+key).attr("title")+" can not be left empty");					               
	               }
	               else if(response.data[key]=="invalid"){
	            	   alert("Invalid value for "+$("#"+key).attr("title"));
		           }
	               else if(response.data[key]=="duplicate"){
	            	   alert("field aleady exist");
		           }
		      }}
		   }
       });
      return false; 
}
</script>
</div>
